### ISSUE TITLE
Model receive funds screen for on-chain

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#100]
We do have receive funds screen for off-chain (Lightning) payments that is currently the same as for the initial funding, see https://github.com/get10101/10101/issues/70

The screen to receive on-chain payments is missing in the prototype.

**Comment by klochowicz** [comment]
@da-kami is this still planned? do we need it in the prototype or shall we just implement it in flutter?

**Comment by da-kami** [comment]
I am not sure it has to be part of the MVP, I think it's fair keep the limitation that we can only find from another Lightning wallet at the moment.

The `send on-chain` screen might become more important at some point, the limitation to let the user recover these funds with the seed phrase is somewhat of a bigger hurdle for me. 
I think this will become relevant after Q3.

CC @bonomat

**Comment by bonomat** [comment]
Let's close this for now and start planning wallet functionality separately a bit later.
