### ISSUE TITLE
Transaction history text cut short

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#1011]
The new text accompanying entries such as the matching fee is not really readable atm.

![image](https://github.com/get10101/10101/assets/9418575/4d694570-dec7-458c-9d8a-7d8a53a63a5b)

---

Running on iPhone SE.

**Comment by Restioson** [comment]
If you open the detailed balance view's tx/rx menu then you have a similar problem :sweat_smile:

**Comment by Restioson** [comment]
![image](https://github.com/get10101/10101/assets/6688948/14d704dd-f1e3-4212-aec2-091d72e5c2db)

This is an issue on my android

**Comment by Restioson** [comment]
Possibly replated: #346

**Comment by luckysori** [comment]
> Potential solution could be to change the text to just the type of event (fee, on-chain payment, off-chain payment, position open) , add some text wrapping to make sure that it's always displayed, and then add some kind of cue that shows that it can be expanded. Then, when the user clicks on it, they can get detailed info in a table, like the exact amount of sats (instead of just the rounded figure), exact time, order ID, other address, etc.

Thanks for thinking about this!

I think for now it would be good enough to prioritise the type of event like you say. The rest of the information could appear on a pop-up screen or we could just expand the transaction history item in place.
