### ISSUE TITLE
Prevent screen from sleeping

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1013]
During executing a trade we should prevent the phone from going into sleep mode as the protocol might get interrupted. 

There seems to be a simple plugin for that: 

https://pub.dev/packages/wakelock

**Comment by Restioson** [comment]
Related: #820 and #1152

**Comment by holzeis** [comment]
@bonomat given that the trade is now executed much faster - I think we don't have to action this ticket. wdyt?

**Comment by Restioson** [comment]
Are there any edge cases still in which trades may not resolve so quickly? Or possible, future edge cases (e.g being robust to loss of connectivity and retrying automatically) ?

**Comment by holzeis** [comment]
Potentially! It may still take a longer time depending on your proximity to the server.

So maybe it still makes sense, although setting the screen to sleep aren't typically that aggressive, meaning if we can execute the trade under 1 minute we should be fine.

**Comment by bonomat** [comment]
> So maybe it still makes sense, although setting the screen to sleep aren't typically that aggressive, meaning if we can execute the trade under 1 minute we should be fine.

Mine is very the shortest you can go: 30 seconds. 

Screen lock is also annoying during wallet sync btw :) 

I would add it, it's a very easy thing to add and adds some value. :)

**Comment by holzeis** [comment]
It looks like this is the way to go for flutter

https://pub.dev/packages/wakelock

**Comment by bonomat** [comment]
I believe this can be closed now that we sync the wallet in the background and processing orders is much faster
