### ISSUE TITLE
Orderbook and LSP health show as unknown on android emulator

### ISSUE THREAD

**Issue by Restioson** [get10101/10101#1027]
This might be related to `run-local-android` as opposed to the app itself.

**Comment by Restioson** [comment]
I don't see `Cannot update orderbook status` in the logs anywhere, which is weird, since I'd expect that. Additionally, the orderbook itself seems to be working fine and I am regularly receiving new messages from the orderbook. It seems like either the receiving end of the watch channel got dropped, there is a UI issue, or some issue with the bridge.

**Comment by bonomat** [comment]
Cannot reproduce this: 
<img width="310" alt="image" src="https://github.com/get10101/10101/assets/224613/6a1dbfab-9bf2-4129-be00-3a4aa9b14c5e">

All services are online. 
Please re-open if this still happens to you @Restioson

**Comment by bonomat** [comment]
I also ran it in an emulator :/

**Comment by Restioson** [comment]
Which emulator did you run it with and with which commands?

**Comment by bonomat** [comment]
I used `Android Studio` with Pixel 6 API 33 and `just run-local-android`

**Comment by klochowicz** [comment]
is the coordinator working fine, ie. can you ping the 'health' endpoint manually?

**Comment by Restioson** [comment]
I'll try that on the emulator - locally was working I believe.

**Comment by Restioson** [comment]
![image](https://github.com/get10101/10101/assets/6688948/28138085-b2ec-4550-8040-a9aafcab29e4)

Seems to work fine on the emulator's browser

**Comment by Restioson** [comment]
With #1048 in, this works. It seems like I had some ancient version of the native crate which hadn't been updated and this didn't work on that version. Strange that no other issues were encountered because of that so far by me :sweat_smile:
