### ISSUE TITLE
Automatically closing expired positions is too inconspicuous

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1028]
A user checking their position does not notice that their position is expired and therefore might close the app while the collaborative closure is happening.

Closing the app during this phase is still critical and may result into failures e.g. force closures (see also #874).

Automatically closing an expired position should be more visible to the user.

**Comment by holzeis** [comment]
related to https://github.com/get10101/10101/issues/988

**Comment by bonomat** [comment]
Closed in favor of https://github.com/get10101/10101/issues/1071
