### ISSUE TITLE
Give app user an indication that their channel is being closed on-chain

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1031]
Instead of trying to get back into a recoverable mode of the app we want go for an emergency scenario: 

If the app detects that the DLC channel has been force closed (or is currently being force closed), we show an emergency screen. The emergency screen shows something like this: 

> Your DLC channel has been force closed. Don't you worry, you will be able to get your funds. Please keep the app open or come back to check when the transactions have been included. You can then recover your funds in a new app using your seed phrase. 

Recovering from the seed phrase is covered in https://github.com/get10101/10101/issues/1079

**Comment by bonomat** [comment]
To be precise: we should only remove the position once the corresponding CET was successfully spent (or is spendable), i.e. once the oracle attests to the price. Before that we do not know the PnL.

**Comment by bonomat** [comment]
Deemed as not critical for now and de-prioritized. We want to move forward with features that increase trading and enable perpetuals. 
Removed from the milestone.
