### ISSUE TITLE
Release binaries separately

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1034]
Our release process currently releases: 

- the maker
- the coordinator
- a testflight app

We should split the release process, so that we can release each binary separately.

**Comment by klochowicz** [comment]
what's your reasoning? if you're in control the deployments / release / access, is there any harm in keeping them together? or is the turnaround time problematic?

**Comment by bonomat** [comment]
It's mostly a matter of time.

**Comment by bonomat** [comment]
Not strictly necessary for the milestone.

**Comment by bonomat** [comment]
I still want this :)
