### ISSUE TITLE
Add more `prometheus` metrics

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1036]
- [x] maker-coordinator status: is the coordinator online: https://github.com/get10101/10101/pull/1180
- [x] orderbook status: is the orderbook online: https://github.com/get10101/10101/pull/1180

*outside* the scope of this ticket, but related:
- [ ]  #1222

**Comment by holzeis** [comment]
Do we really need those metrics in prometheus?

> position metrics (PnL, size, direction, duration)

Isn't it sufficient to have this data in the database?

**Comment by bonomat** [comment]
Yes please, it's helpful to have an overview (e.g. for warnings) at any point of time.

**Comment by holzeis** [comment]
Well you can get an overview at any point in time also from the database.

**Comment by bonomat** [comment]
Yes, I want to have the alerting functionality to warn us if things are in the red zone.

**Comment by klochowicz** [comment]
is having a Postgresql data source in grafana still something we're considering?
it seems that having a periodic query on that database and including it as time series would be a better way to gather position data in the long run:
https://grafana.com/docs/grafana/latest/datasources/postgres/

(in the meantime, I'm doing the position data as prometheus metrics).

**Comment by bonomat** [comment]
> is having a Postgresql data source in grafana still something we're considering?

Potentially, our data is now a better structured than it was with itchysats. 

>  it seems that having a periodic query on that database and including it as time series would be a better way to gather position data in the long run:

I did some research a while ago and to my understanding grafana's sql connection expects the metrics in a timestamp format in the db to query them, i.e. a table somthing like this 

<table>
<tr>
 <td>timestamp</td>
 <td>value</td>
</tr>
<tr>
 <td>2023-08-28 21:05</td>
 <td>1<td>
</tr>

<tr>
 <td>2023-08-28 21:10</td>
 <td>2<td>
</tr>
<tr>
 <td>2023-08-28 21:15</td>
 <td>3<td>
</tr>
</table>


My understanding is that you cannot query something periodically and use the timestamp from when you queried it. Just think about it, Grafana would need to store this data _again_ in a database and add a timestamp to it. 
The data in the db needs to have the timestamp added to make suitable graphs

Most of our tables have this structure already so we could reconsider it but Grafana is not meant to be used for business metrics. 

There are other tools which could do this job better: I looked into a few and [metabase](https://www.metabase.com/), or  [redash](https://redash.io/help/open-source/setup) was most promising which can be run on our machine. 

But I guess that's something for a different day :D

**Comment by klochowicz** [comment]
I've extracted #1222 outside the scope of this ticket as my PR didn't address that part of the metrics.
cc: @holzeis who was interested in taking over some of the metrics.
