### ISSUE TITLE
Tx fee is 0 for funding transaction

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1043]
We opened a channel this morning but the tx_fee for the funding transaction was 0.
This should not be possible.

* txid = [`0504c4f4cabd14cf4a94f3e84afc1da50a4780db9c980eb2b03953a76beed8d9`](https://mempool.space/tx/0504c4f4cabd14cf4a94f3e84afc1da50a4780db9c980eb2b03953a76beed8d9)
* channel = `d9d8ee6ba75339b0b20e989cdb80470aa51dfc4ae8f3944acf14bdcaf4c40405`
* counterparty = `02ee82c4ac513d82f4ff9889c3db0ff19f818913aea6aba525eca84f3453f393ac`

**Comment by holzeis** [comment]
Did the shadow channel sync task run?

**Comment by bonomat** [comment]
Yes, runs like clock-work every 10 minutes.

**Comment by holzeis** [comment]
Can you add the logs of a run to the ticket?

**Comment by bonomat** [comment]
Do you want this line?

```
{"timestamp":"2023-07-31T08:23:29.330504929Z","level":"DEBUG","fields":{"message":"Syncing 25 shadow transactions"},"target":"ln_dlc_node::shadow"}
```
If not, can you be more precise what logs you want please?

**Comment by holzeis** [comment]
Well the logs around that line. It should show if the shadow channel gets updated resp. if something went wrong.

**Comment by holzeis** [comment]
But it should actually say something about shadow channels.

**Comment by luckysori** [comment]
> We opened a channel this morning but the tx_fee for the funding transaction was 0. This should not be possible.
> 
>     * txid = [`0504c4f4cabd14cf4a94f3e84afc1da50a4780db9c980eb2b03953a76beed8d9`](https://mempool.space/tx/0504c4f4cabd14cf4a94f3e84afc1da50a4780db9c980eb2b03953a76beed8d9)
> 
>     * channel = `d9d8ee6ba75339b0b20e989cdb80470aa51dfc4ae8f3944acf14bdcaf4c40405`
> 
>     * counterparty = `02ee82c4ac513d82f4ff9889c3db0ff19f818913aea6aba525eca84f3453f393ac`

This is my channel! My app just failed to pay the channel-opening fee (although the logs aren't very clear). I think we can close this given https://github.com/get10101/10101/pull/1052.

In any case I think it would be less error-prone for the app to remember that this fee is owed until the payment is claimed. There are too many reasons why this payment might fail on the first attempt.

**Comment by bonomat** [comment]
I think this was wrongly closed @luckysori : the field `fee` in the `transactions` table should be the on-chain fee. 

See here: 
https://github.com/get10101/10101/blob/81aa911cf08494f3dfd6b6df8b9c8410c425fd87/crates/ln-dlc-node/src/shadow.rs#L50-L68
