### ISSUE TITLE
Add support for local notifications

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#1045]
We should support sending push notifications based on local events.
One obvious situation where it can be plugged in is receiving a payment via LN.

Some point to get it started:
-   <https://dev.to/carminezacc/flutter-notifications-without-firebase-33d2>

It would be great if it would be done in a way that coexists with #1044

**Comment by holzeis** [comment]
> One obvious situation where it can be plugged in is receiving a payment via LN.

Does that mean the local notifications look like native notifications?

**Comment by holzeis** [comment]
If that's the case, they are too generic in my opinion to show that a payment was received. 

But maybe I feel differently when I've seen an example 🙂

**Comment by klochowicz** [comment]
> > Does that mean the local notifications look like native notifications?
> 
> I believe so, they would just originate from the app itself and not from a remote server a la push notifications.
> 
> PS: this package also exists https://pub.dev/packages/flutter_local_notifications

🙃 this is literally the package in the link I've posted

**Comment by klochowicz** [comment]
> If that's the case, they are too generic in my opinion to show that a payment was received.
> 
> But maybe I feel differently when I've seen an example 🙂

This is how you have it in bank apps, isn't it?

**Comment by holzeis** [comment]
Not in my bank app. But it's even worse there 🙈. You'll see a grey bar on the top that has a small white message that you can click. (If the app is open)

**Comment by Restioson** [comment]
> 🙃 this is literally the package in the link I've posted

🙈

**Comment by Restioson** [comment]
> If that's the case, they are too generic in my opinion to show that a payment was received.

We can put any content in it, though, so in what sense would it be too generic?

**Comment by holzeis** [comment]
> > If that's the case, they are too generic in my opinion to show that a payment was received.
> 
> 
> 
> We can put any content in it, though, so in what sense would it be too generic?

IMHO it's too generic in the context of a received payment. E.g. Breez is showing confetti, Zeus is showing a lightning and I think phoenix shows a dialog which depicts whether the payment for the created invoice was received.

**Comment by Restioson** [comment]
> IMHO it's too generic in the context of a received payment. E.g. Breez is showing confetti, Zeus is showing a lightning and I think phoenix shows a dialog which depicts whether the payment for the created invoice was received.

We could always expand on it inside the app itself, but it could be useful if the app is running in the background and the user receives the payment. The notification would then prompt them to re-open the app to see the fancy animations

**Comment by klochowicz** [comment]
Can we please move the discussion *how they will look* into #179  ?
this ticket is about local notifications feature, and there are many other use-cases for this. this was just an *example*
