### ISSUE TITLE
Assess correctness of derivation of seeds from mnemonic

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#106]
I was surprised to see that we were using the `hkdf` library to transform the mnemonic seed into the LDK and on-chain wallet seeds. Furthermore, we weren't sure about the way we appear to be "tagging" the mnemonic seed to generate LDK and on-chain seeds.

**Comment by holzeis** [comment]
@luckysori this ticket seems to be important. What is the issue with using the hkdf lib?

**Comment by luckysori** [comment]
Can't say I remember what I had in mind when I wrote this ticket 5 months ago 🤷 I'll assign myself and add the `grooming` label for now.

**Comment by bonomat** [comment]
Can we define what we want to achieve with this ticket? _Correctness_ can have multiple meanings and different wallets implement different derivation paths. 

My understanding is that the goal is to import the seed phrase in a different wallet and recover the on-chain funds.

We should be aware that not all wallets support the same derivation approach, e.g. [I've read](https://electrum.readthedocs.io/en/latest/seedphrase.html#motivation) that the mnemonic phrase of electrum is not compatible with a bip39 seed phrase. 

I guess a good start would be testing against [bip39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) [test vectors](https://github.com/trezor/python-mnemonic/blob/master/vectors.json).

I gave it a try in this [branch](https://github.com/get10101/10101/compare/test/bip39-comp?expand=1). 
As one can see, we are not compatible with the test vectors.
