### ISSUE TITLE
Rollover DLC

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1068]
In order to have perpetual futures (CFDs) we need to extend our DLCs. 

In a nutshell, a rollover is closing the current DLC and reopening it again with a new expiry and the same values.
Note: _same_ is not 100% correct but for this ticket the funding rate is out of scope.  

Funding rate ticket: https://github.com/get10101/10101/issues/1069

Note: we only rollover a non-expired position.

**Comment by holzeis** [comment]
`rust-dlc` already exposes an API to update a dlc channel. see also https://github.com/p2pderivatives/rust-dlc/blob/master/dlc-manager/src/channel_updater.rs#L954.

Using that API we don't have to collaboratively close and reopen the position, which simplifies the protocol significantly. The api also expects a `payout_amount` parameter which can come in handy when implementing the funding rate.

**Comment by holzeis** [comment]
```mermaid
sequenceDiagram

actor u as User
participant a as App
participant c as Coordinator

Note right of a: Position is about to expire. e.g. in 2 hours

c->>u: Push notification: Come online to rollover your position.
u->>a: Starts 10101 app
a-->>u: Show dialog for extending position

alt Extend position 
a->>c: extend position
c->>a: Renew offer
a-->>c: Renew accept
c->>a: Renew confirm
a-->>c: Renew finalize
c->>a: Renew revoke
a->>a: Update position
a-->>u: Show finished extending position
else Close position
a->c: collaborative close position
a->>a: Remove position
a-->>u: Show finished close position
end






```
