### ISSUE TITLE
`just fund` skipping is unreliable

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#1072]
the recent addition to `justfile` is not reliable; faucet was broken on my machine and it proceeded forward, making it unnecessarily hard to find true cause why things weren't working

Previous code would detect that something was wrong with the faucet, and fail hard at the spot.

I'm for removing this workaround  - we can brainstorm if this is a huge pain to fund it every time; I believe it's good as it mines blocks, and between subsequent runs we're closer to production, especially if we restart with an open position.

**Comment by klochowicz** [comment]
cc: @Restioson

**Comment by Restioson** [comment]
> faucet was broken on my machine and it proceeded forward

`just fund` queries the faucet to see how much balance it has (`localhost:8080/lnd/v1/balance/channels`). So, I guess if this endpoint is not reporting correctly, it wouldn't work. 

> Previous code would detect that something was wrong with the faucet, and fail hard at the spot.

Maybe something could be added to also force fund if something is wrong. 

What was the actual issue in the end, and how would it fail if there was an issue previously?

**Comment by klochowicz** [comment]
In the end the app  wasn't working, I could not pay an invoice. I spent 30 mins debugging it because I would assume that the funding script would work if it let me start the app (and it always did).

this has happened to me again on Friday.

I will proceed with removing this skipping, because the few seconds we saved with this was not worth it in my opinion ☹️

**Comment by klochowicz** [comment]
@Restioson I went with the quickest way of addressing this issue. Without a doubt if we invested more effort it could become reliable, but I don't think it's worth it at this stage.

I also wonder whether the delay you've experienced (original reason for proposing it) was due to cache invalidation due to different target being built perhaps? in case this was happening to you on Android, you're welcome to do something similar to what I've recently done for iOS here: #1090  - hope it helps!

**Comment by Restioson** [comment]
Currently the slowdown happens on every call to `just services` 😅

**Comment by klochowicz** [comment]
> Currently the slowdown happens on every call to `just services` 😅

but you can just call whatever you wish selectively - there's no pressure to use `just all` if it doesn't work for you. 
It seems to me like you could run `just run` in your scenario

**Comment by Restioson** [comment]
Indeed, hence I don't really mind if it gets reverted - what I meant by my original comment was that it is not an android-exclusive issue that I'm having, but I worded it poorly. That being said, you're right, it's not such a big deal in general

**Comment by klochowicz** [comment]
happened to me today again.

example of misbehaviour:

```
Lightning faucet balance is <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.23.3</center>
</body>
; skipping funding. Pass -f or --force to force.
```

**Comment by Restioson** [comment]
Huh, wonder why this compares less than in this case.

If this is the only way it can misbehave, should be a relatively simple fix, but not sure if worth it
