### ISSUE TITLE
API to force-close DLC channel

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1076]
We should add an HTTP API to the coordinator which allows us to force-close a DLC channel.

**Comment by bonomat** [comment]
cc @luckysori : this should now be possible right?

**Comment by luckysori** [comment]
This already exists e.g.

```
curl -X DELETE "localhost:8000/api/admin/channels/33baa0151906ac947475956b987fb06749d67c283f6021343a87c0696974d911?force=true"
```

**Comment by bonomat** [comment]
You are correct. The API is there, I haven't verified it if it works yet. Will proceed with https://github.com/get10101/10101/issues/1077
