### ISSUE TITLE
Collaborative closure of the LN-DLC channel (when DLC subchannel is open)

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#1085]
### Context

We currently only allow collaboratively closing the Lightning channel if there is no active subchannel associated with it. If there is a subchannel, we instruct the parties to first collaboratively close the subchannel.

This is acceptable, unless the subchannel is stuck in an intermediate state[^1] (it's neither open nor closed). If the subchannel is stuck, the parties will not be able to close the subchannel collaboratively, so they will have to force-close instead. Force-closing is much less convenient as it involves long timelocks and higher transaction fees.

### Solution

Let's permit the collaborative closure of the LN-DLC channel via LDK under the right circumstances i.e. if the subchannel is stuck.

Things to consider:

- Both parties need to be online. This suggests to me that it should be initiated by the app, but that could lead to it being abused! As a solution I think we should let the app call a coordinator endpoint so that the coordinator can propose the collaborative closure of the LN-DLC channel. The coordinator would then have final say on whether to do so or not. We could even let the coordinator decide then and there if the channel should be force-closed instead.

- We need to patch `rust-lightning`, as we currently build an invalid `closing_transaction` if we try to collaboratively close when the subchannel is open. This is because we wrongly use the `glue_txo` as an input instead of the `funding_txo`.

- Closing collaboratively through LDK will ignore the state of the DLC channel. This would probably be desirable if the subchannel got stuck when opening a position as we can safely ignore the DLC that was never actually created, but in all other cases (currently only when closing a position) this would be bad. To deal with this we could further extend `rust-lightning` to allow collaboratively closing the channel with a custom split, but it might be simpler to only allow collaborative closure in specific scenarios.

[^1]: This should never happen, but this is still beta software so it does actually happen.

**Comment by holzeis** [comment]
Still relevant and should probably be tackled sooner than later.
