### ISSUE TITLE
Numbers don't always add up after funding in e2e tests

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#1087]
See e.g.: https://github.com/get10101/10101/actions/runs/5801924993/job/15727244113) (had different tests exhibiting this behaviour).

before it fails at the assertion, we print out what's the actual value - in this case: 

`2023-08-08T21:18:13.559000Z  INFO tests_e2e::setup: Successfully funded app with faucet funded_amount=49847 ln_balance=49779`

grepping for this string shows that other tests (which pass) get slightly more into their lightning wallet;

`2023-08-08T21:17:39.712423Z  INFO tests_e2e::setup: Successfully funded app with faucet funded_amount=49847 ln_balance=49847`

To unblock myself i'll plaster over this by temporarily relaxing the assertion.

**Comment by luckysori** [comment]
I think this is just caused by the app having to pay the channel-opening fee, right?

**Comment by bonomat** [comment]
> I think this is just caused by the app having to pay the channel-opening fee, right?

would have also been my assumption.

**Comment by luckysori** [comment]
I'm fixing it with my next PR.
