### ISSUE TITLE
Change the logging framework

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#1092]
Public comparison of frameworks: https://fluttergems.dev/debugging-logging/

F_logs is troublesome, because it didn't get updated in oner a year (15 months), including recently to `intl 0.18`, which became a roadblock in integrating #114 .

After researching it, I recommend switching to `logger`, as it's definitely the most maintained and used logging solution for Flutter.

sample code: 
```
Because get_10101 depends on f_logs ^2.0.1 which depends on intl ^0.17.0, intl
  ^0.17.0 is required.
So, because get_10101 depends on intl ^0.18.0, version solving failed.

```

it would be great if we could add a wrapper to allow easy change in the feature (we didn't need to expose FLogs everywhere ;/ )

**Comment by klochowicz** [comment]
I've plastered over the problem by using a `dev_override` in #1113 .
we might not need to address it for a while, so closing it.

**Comment by klochowicz** [comment]
@bonomat was there a reason to reopen this issue?

**Comment by bonomat** [comment]
> @bonomat was there a reason to reopen this issue right now?

Mhmm... I think it was a mistake.

**Comment by Restioson** [comment]
I imagine we can close this with the merging of #1477
