### ISSUE TITLE
Create app backup

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#1098]
If we don't do this then the only safe way to delete the app is to ensure that all the coins are owned by the on-chain wallet which is actually backed up through the mnemonic seed phrase.

Provide an easy way of backing up (in an encrypted way) all the relevant data, with an option to import *everything* after providing the backed up mnemonic seed at the first startup of the app.

The data we want to backup:
- [ ] seed phrase
- [ ] Lightning data (channel monitor, chain monitor, )
     - if it's simple to use VSS, we could consider using it
- [ ] rust-dlc data (sled DB)
- [ ] trades history (the sqlite DB)

_Originally posted by @luckysori in https://github.com/get10101/10101/issues/1079#issuecomment-1676739667_

**Comment by klochowicz** [comment]
are you thinking of VSS?

**Comment by luckysori** [comment]
> are you thinking of VSS?

I wasn't thinking of anything specific solutions although VSS might be the best option, yeah.

**Comment by bonomat** [comment]
@luckysori : please describe the Acinq idea

**Comment by bonomat** [comment]
If we follow the Acinq idea we should do this at the same time: https://github.com/get10101/10101/issues/1255

**Comment by klochowicz** [comment]
if the backups would be encrypted, perhaps it might be easier to use the OS native cloud backup solution? e.g. iCloud on iOS?
it could still work exactly the same way, but without the added risk needing to store the data.

**Comment by klochowicz** [comment]
instead of manually specifying the events when to send, it might be easiest to use some sort of file watcher (or roll out our own that):
a) computes and stores the hashes of all the relevant places we back up quite often
b) if the hash is different, send an updated version to the server and store new bunch of hashes

**Comment by bonomat** [comment]
> if the backups would be encrypted, perhaps it might be easier to use the OS native cloud backup solution? e.g. iCloud on iOS?

This would require a google account on android which many don't have.

**Comment by bonomat** [comment]
> instead of manually specifying the events when to send, it might be easiest to use some sort of file watcher (or roll out our own that):

Is that deciding between polling vs pushing? 

The downside of checking regularly for file changes might be that we end up in-between two changes where one file was fully written and another one not yet.

**Comment by holzeis** [comment]
> > instead of manually specifying the events when to send, it might be easiest to use some sort of file watcher (or roll out our own that):
> 
> 
> 
> Is that deciding between polling vs pushing? 
> 
> 
> 
> The downside of checking regularly for file changes might be that we end up in-between two changes where one file was fully written and another one not yet. 

Isn't it pretty simple with the events? IMHO after the following events we have to send a backup to the coordinator.

- Payment Sent
- Payment Claimed (also captures implicitly the ln channel opening)
- Position opened
- Position closed / changed
- Ln channel closed

Am I missing something?

**Comment by bonomat** [comment]
> Am I missing something?

From the LN perspective, basically whenever the commitment tx changes: 
- whenever there was a fee bump of the commitment transaction
- when there was a payment attempted, i.e. an htlc added
- when ever an HTLC was removed (failed or succeeded)

**Comment by holzeis** [comment]
Hmm.. that indeed sounds a bit more complex than a few events.

**Comment by bonomat** [comment]
Let's look into https://github.com/lightningdevkit/vss-server and how Mutiny does it.

**Comment by holzeis** [comment]
It seems the most straightforward way of doing this is to hook into the storage interface, encrypt every KV store update for rust-lightning and rust-dlc and send the backup immediately to the coordinator. 

Optionally we could go with the vss model, but I am not sure if this will help us a lot. However, sticking to some kind of standard is definitely worth evaluating.

In terms of our database, I think in theory we do not have to do a backup as the coordinator should be able to reconstruct the apps view from its own database. (position, order, channel, etc). I will see if this is the case and pivot if not feasible.
