### ISSUE TITLE
`OrderSubmissionStatusDialog` can hang forever

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#1108]
If the subchannel open/close protocol does not finish (either successfully or unsuccessfully), the `OrderSubmissionStatusDialog` will remain open indefinitely.

This is a problem because the same dialog says that the user should not close the app, but that's the only way to move forward.

**Comment by luckysori** [comment]
> I feel like this is technically not a dialog/UI issue, but rather a backend issue. We need some kind of timeout to prevent this, and I think it should come in the form of an event or failure type from the backend to the frontend.

Good point. @holzeis and I did discuss this yesterday and I think we didn't come to a consensus on whether this should be solved in the UI or the backend.

I tend to agree with you that it should be driven by the backend though.

**Comment by Restioson** [comment]
The issue I have with it being driven from the frontend is that it's difficult to tell whether it's just hanging or really just taking a long time. I feel like the logic for introspecting the backend (and deciding whether hang or taking long) should live there and not in the frontend. 

For _now_ it might just be "is it taking longer than 1 minute", but in the future there may be indicators of progress.

**Comment by bonomat** [comment]
@holzeis : I've unnasigned you and move it into `todo`. Imho it is clear what todo here.

**Comment by klochowicz** [comment]
> @holzeis : I've unnasigned you and move it into `todo`. Imho it is clear what todo here.

Is it clear? with the recent changes the whole existance of the Dialog is questionable - perhaps it would be enough to have just a  dismissible dialog with the result of the operation? then the problem goes away entirely.

**Comment by bonomat** [comment]
> Is it clear? 

If it is not clear to you, feel free to ask and we can add more context

> with the recent changes the whole existance of the Dialog is questionable - perhaps it would be enough to have just a dismissible dialog with the result of the operation? then the problem goes away entirely.

As long as the protocol execution is not instant I'm in favor of having this dialog while it is being executed.

**Comment by luckysori** [comment]
Did you fix this recently, @holzeis?

**Comment by holzeis** [comment]
Not for the order submission, but it should be fairly easy to add.

However that would be on the frontend side, but I guess that's the best we can do.
