### ISSUE TITLE
Subscribe to lightning and dlc events

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#111]
With https://github.com/get10101/10101/pull/105 we introduced an `event_handler` that is processing all lightning events. dlc will introduce a similar handler.

There are multiple situations where it would be handy to be able to subscribe to theses events so that follow up processing can happen.

1. Testing: Currently we poll for a certain state to imply that an event might have happened. By simply subscribing to the expected event this could be done much cleaner.
2. Payment notifications: Informing the user about an incoming payment, when the event actually arrives.

Additionally it would be nice if the `event_handler` could be separated into individual handlers for e.g. larger events. Done correctly we could leverage that for a more flexible testing approach. e.g. mocking certain events, etc.

**Comment by bonomat** [comment]
Handing over this to @luckysori and @holzeis . :)

**Comment by luckysori** [comment]
Removing assignment of @holzeis and me since we have not worked on it and it's low priority.

**Comment by luckysori** [comment]
To be fair to us, this has already been done to some extent, so I will close it as done haha.
