### ISSUE TITLE
Can't trade: order times out

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1116]
Version: 1.2.0
Build: 1818

```
| 2023-08-18 09:21:12.122 | LogLevel.ERROR | Failed to execute trade for order Some(43066fbf-2f63-4587-9dbe-5db2564a434e): TradeRequest: Failed to register with coordinator: error sending request for url (http://46.17.98.29/api/trade): operation timed out: operation timed out  
```

I believe this has to do with the coordinator not being responsive during wallet syncs.

**Comment by Restioson** [comment]
This would make sense since `sync` will lock the wallet, so nothing else that involves the wallet will be able to progress during a sync

**Comment by klochowicz** [comment]
I believe this will only get properly addressed with https://github.com/get10101/10101/issues/788

**Comment by bonomat** [comment]
Note: we did not have the problem in earlier versions (or we did not notice it). If we did not have this problem in earlier version it would rather point to a regression we introduced with one of our updates

**Comment by Restioson** [comment]
Interesting point!

Is it also possible that this is just something that happens now that there is more state to sync, so it takes longer, or is it very consistently reproducible unlike before?

**Comment by bonomat** [comment]
My investigation lead to that the released version with this commit breaks it
- 4461818494d5392d86efe1bdd41b9fea13e3b297
- build: 1849

and the released version with this commit still works:
- 262330e9108a9ee25eaa5a9f6debeb4bf2c261a0
- build: 1839

Meaning, the breaking change must be in between those 10 commits.

**Comment by holzeis** [comment]
@bonomat Could it be that those order time out have been unlucky instances of where the order has been submitted while the coordinator was restarting? I think there have been significantly more restarts due to #1141.

**Comment by bonomat** [comment]
I would not rule this out.
