### ISSUE TITLE
Can't open account overview

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1129]
On regtest (build 1868) I can't open the account overview anymore. If I click on the drop down, nothing happens.

**Comment by bonomat** [comment]
Can't reproduce it on `master` using simulator nor deploying right to the phone. :/ Same commit hash as used on the phone also works on the simulator. :/

**Comment by klochowicz** [comment]
what's the 'account overview'? the settings screen?

**Comment by bonomat** [comment]
The wallets/accounts in the wallet overview, i.e. bitcoin and lightning

![image](https://github.com/get10101/10101/assets/224613/3eb4cb1c-00f3-4918-a48a-fa3b6fdc8dd5)

**Comment by Restioson** [comment]
Possibly related: #1131

**Comment by klochowicz** [comment]
> Possibly related: #1131. I reckon this is the same routing issue

if it is indeed the same, then we should see whether #1137 will fix this one too.

**Comment by Restioson** [comment]
hmm, this is actually an expansion panel so it shouldn't interact with routing :thinking:

**Comment by bonomat** [comment]
It did not fix it.

**Comment by bonomat** [comment]
I'm currently testing removing the feedback plugin again and see if this fixes the issue.

**Comment by bonomat** [comment]
Unfortunately the PR #1144 did not fix it :/ 
I found this ticket https://github.com/flutter/flutter/issues/132759 which seems to be related and verified that locally I'm running flutter version `3.10.6` and on CI we used `3.13.`

**Comment by Restioson** [comment]
Hm, I am experiencing this locally - wonder if it's because I updated my flutter? :grimacing:

**Comment by klochowicz** [comment]
> Hm, I am experiencing this locally - wonder if it's because I updated my flutter? 😬

yes, that is most likely the case.

**Comment by Restioson** [comment]
It's somewhat worrying that this doesn't work on later flutter though - presumably we'll need to upgrade at some point

**Comment by klochowicz** [comment]
> It's somewhat worrying that this doesn't work on later flutter though - presumably we'll need to upgrade at some point

it might be a temporary regression - might be worth reporting somewhere. 
I don't think it's a great cause to worry as we have done the biggest upgrade (Dart 3) and the other part can stay solid for a while.
it would be great to use `fvm` or some other way to pin the flutter version for all the contributors, otherwise we can get more bug reports like that. ;/
