### ISSUE TITLE
Add synthetic usd screen - simplified position summary

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1130]
The idea is to have a separate screen which shows an overview of the Synthetic USD. 
It is basically a simplified version of our trading screen.

```[tasklist]
### Tasks
- [x] Update figma mocks (so that things stay up2date)
- [x] Implement in flutter
```

**Comment by holzeis** [comment]
below a simplified proposal to get synthetic usd into 10101

![stablize-sats](https://github.com/get10101/10101/assets/382048/15326d90-3de8-4725-b762-a47b4d047517)
