### ISSUE TITLE
App stuck on fill order success dialog

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1131]
After opening a position the app just stuck on the success dialog. see screenshot.

Branch: main
Commit: 03e0b844fdf60ada6c8c41cd851e6ac8e1271927
Build Number: 1880
Build Version: 1.2.0

![IMG_C77F3F3148DD-1](https://github.com/get10101/10101/assets/382048/60b14fd6-f005-471e-87f3-f744795cba4c)

**Comment by Restioson** [comment]
Related error message: `No GoRouter found in context`

**Comment by Restioson** [comment]
Bisected to 13d1a48b1c03d9c699464526088e8b2f692b84d1

**Comment by klochowicz** [comment]
> Bisected to [13d1a48](https://github.com/get10101/10101/commit/13d1a48b1c03d9c699464526088e8b2f692b84d1) (cc @klochowicz).
> 
> Side note: bisecting this took _forever_ because of all the recompiles & wipes I needed to do. Not likely to do it again 😅 I think just searching for a cause would have been faster. However, the error message was incredibly vague so I didn't really know where to start.

 Thanks, I'll look into it.
It might be easiest to try to reproduce these things on different versions of 10101-test app (unfortunately only in iOS's TestFlight).

**Comment by holzeis** [comment]
Sorry for not sharing the logs earlier.

https://nextcloud.holzeis.me/s/EfJ5T7nxPps5dTW
