### ISSUE TITLE
CI fails randomely with "No space left on device"

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1138]
The e2e-tests fail every now and then with "No space left on device" - see github actions run logs below.

https://github.com/get10101/10101/actions/runs/5930860557/job/16081510190

A simply rerun without any changes fixed the issue.

https://github.com/get10101/10101/actions/runs/5925998043/job/16069790092

**Comment by bonomat** [comment]
I don't think there is something we can do about.

**Comment by bonomat** [comment]
We could add a `df -h` into the action though, next time we would see where the space is going and we could compare actions with each other.

**Comment by klochowicz** [comment]
looking at the CI caches, we use almost 30GB of our 10GB limit 😅 it might have something to do with it.

**Comment by bonomat** [comment]
> I don't think there is something we can do about.

I take that back. We can apparently remove some unneeded stuff, e.g. by using this action: 
https://github.com/easimon/maximize-build-space

**Comment by klochowicz** [comment]
> > I don't think there is something we can do about.
> 
> I take that back. We can apparently remove some unneeded stuff, e.g. by using this action: https://github.com/easimon/maximize-build-space

I'll give it a crack, because I can't get things merged. thanks for the idea!

**Comment by klochowicz** [comment]
Hopefully solved with the CI modifications that went along  #1136 in order to merge it.

**Comment by holzeis** [comment]
Happened again

https://github.com/get10101/10101/actions/runs/6335328615/job/17206943887?pr=1392

**Comment by bonomat** [comment]
Some insights: 
before running unit tests: 
```
/dev/root        84G   64G   20G  77% /
```

After running unit tests (including all the setup)
```
/dev/root        84G   81G  2.9G  97% /
```

This was a successful run. Another run, we had at the end 

```
/dev/root        84G   83G  341M 100% /
```

which failed. 

Weird... 
Eitherway, we can estimate we need about 20G storage for our CI build

**Comment by bonomat** [comment]
This has been improved.
