### ISSUE TITLE
Ensure that broadcasted transactions are re-broadcasted

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1139]
If a transaction was not included yet in the mempool, the app/coordinator should try to rebroadcast the transaction, e.g. on restart.

Alternatively, we could store all broadcasted transactions in the DB and do it manually when needed.

**Comment by bonomat** [comment]
Critical because if we do not do this yet we might lose the posibility to broadcast old transactions. Our logs get pruned after 30 days.

**Comment by holzeis** [comment]
@bonomat is this really fixed? your change only stores the raw transaction but does not try to re-broadcast them, or does it?

**Comment by bonomat** [comment]
Correct. I descoped this part and only focused on storing it so that we can manually re-broadcast when needed.
