### ISSUE TITLE
Show failed transactions in transaction history

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1140]
It looks like we are not showing failed off-chain transactions in the wallet. It would be good to see them.

**Comment by klochowicz** [comment]
we do store them in the DB, so it should be a relatively easy one.

**Comment by Restioson** [comment]
Seems related-ish to the ongoing work in #1111 & #1103. Happy to look at this after those unless someone gets to it first - no reason it can't be done in parallel imo

**Comment by Restioson** [comment]
Just going to roll this into #1111
