### ISSUE TITLE
Invoice descriptions should not be trusted

### ISSUE THREAD

**Issue by Restioson** [get10101/10101#1147]
Currently, we trust the invoice description to correctly identify the type of transaction as well as any associated data, such as an order id (an example of [CWE-502](https://cwe.mitre.org/data/definitions/502.html)).

https://github.com/get10101/10101/blob/65f4a2fb766885ffa9e5ec528d9b5305d7fe8c85/mobile/native/src/ln_dlc/mod.rs#L351-L356

What happens if the user creates their own invoice with the description `taker-fee-NotAnOrderId?!/.sidfj`? Or, worse, what if the user pays an invoice without looking at the description? These would both show up as trade-related payments in the history. This is bad UX at best, and a security vulnerability at worst.

Imagined social engineering attack:
> Scammer: hey, do you want to make a bet on the price of bitcoin with me?
> User: sure! Shall I open a position on 10101 to bet against you?
> Scammer: I'm actually running my own maker! The software is still in beta, so you need to just transfer me the money directly and the app will set up a DLC for us.
> User: okay, I'm not sure about this, so can we try with 1000 sats first?
> Scammer: sure, here is the invoice!
> [User pays invoice]
> Scammer: check your wallet history and see the matching fee has been paid! The open position will show in the history soon. _(ed: it will not)_
> User: okay, I'll transfer you $1000 now for the bet :)

This is slightly contrived, as we do not expect any of our users to fall for this especially since the beta users should have some idea of how the app works. Note that this scam can still progress to the point of paying 1000 sats in the above example even if this is fixed.

Furthermore, in general, parsing untrusted data is not recommended to be done lightly (see [OWASP - Deserialization of untrusted data](https://owasp.org/www-community/vulnerabilities/Deserialization_of_untrusted_data)). Most parsers are not designed to handle untrusted data. What we are doing is probably fine for now (just stripping the prefix), but this could change and introduce a vulnerability.

There should be another way to figure out the type of payment from a trusted source. Perhaps this could be stored in the database? Presumably order info is already stored there.

If we can authenticate that the invoice was created by the user themselves, then we can also trust the description. This might be a bit brittle, though, since it might seem as though we can trust the description in all cases (when in reality we can only trust it if we know the user generated the payment). Maybe, in that case, it is best to also store the associated data in the database.

**Comment by Restioson** [comment]
cc @luckysori, from our discussion on #1103

**Comment by Restioson** [comment]
Alright, sounds good! Should we not keep this open until then? It just seems like it could be forgotten otherwise :sweat_smile: as it seems a little orthogonal to those two tickets (correct me if I'm wrong)

**Comment by holzeis** [comment]
Will be closed once the referenced tickets are resolved.
