### ISSUE TITLE
Dialog can now be clicked away

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1152]
Changing the `useRootNavigator` to `false` broke the feature of not being able to click away the loading dialog while a position is being opened. 

Differently said, you can now click on the bottom bar to navigate away from the loading dialog and warning will be closed. 

https://github.com/get10101/10101/assets/224613/b82dacff-e1b6-437e-a8c1-f6454bc551c2

**Comment by bonomat** [comment]
I found [this](https://stackoverflow.com/questions/60349741/what-is-the-use-of-rootnavigator-in-navigator-ofcontext-rootnavigator-true) stackoverflow answer. 
Unfortunately I do not fully understand it yet but it looks like changing `useRootNavigator` has some impact on how screens behave.

**Comment by klochowicz** [comment]
quick googling shows that this might fix it - perhaps worth a try? 

 https://stackoverflow.com/questions/50635395/how-to-prevent-alertdialog-from-not-closing-by-clicking-outside

a

**Comment by holzeis** [comment]
> quick googling shows that this might fix it - perhaps worth a try? 
> 
> 
> 
>  https://stackoverflow.com/questions/50635395/how-to-prevent-alertdialog-from-not-closing-by-clicking-outside
> 
> 
> 
> a

I think we are already this setting this property.
