### ISSUE TITLE
Add minimum channel size

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1162]
Due to the risk of having to force close a dlc channel and not being able to renegotiate the fee rate after a channel has been created it makes sense that we are setting the fee rate higher than the normal fee rate at the moment.

However that higher fee rate wouldn't be economical for smaller channels. Consequently we can increase the minimum channel size to e.g. 50k sats (ideally this boundary can be configured equally to the upper bound).

**Comment by bonomat** [comment]
This ticket should be one after https://github.com/get10101/10101/issues/1163
