### ISSUE TITLE
Add Firebase crashlytics

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#1165]
In order to release on Android, we should gather data on crashes (similar to TestFlight). 
To do it in a cross-platform and unified way, we could use Firebase Crashlytics:

https://firebase.google.com/products/crashlytics

note: it can be also configured to share info on *non-fatal* crashes (e.g. uncaught exception), something we don't get with TestFlight.

**Comment by bonomat** [comment]
Blocked pending discussion: https://github.com/get10101/meta/discussions/218
