### ISSUE TITLE
Add perpetual constraints to trading

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#118]
We never modeled the position to be perpetual in the prototype; from the top of my head these are missing:

When opening a position:

- expiry
- initial fee costs (first 24h)

When rolling over a position:

- next funding event
- current funding rate
- timeline of fees for the position / trade history
    - Note on that: We removed the trade history in favor of integrating the "trades" into the order history. But, with perpetuals we will have changes over time that come *after* the order was filled. I think we will need a separate trade history to be able to depict this information after a position was closed.

**Comment by da-kami** [comment]
@bonomat What is the vision for presenting this to the user?
E.g. should the funding rate be called funding rate and should we explain what it is in the app?

**Comment by bonomat** [comment]
> expiry

I would like to hide that their is an expiry which we only have to due technical constraints. 

> initial fee costs (first 24h)

I would not design an `initial fee` for the first 24h but do it retrospectively, i.e. you don't pay for the funding when you open the position, but when the funding happens, e.g. every X/h.

> next funding event and rate

we should display this somewhere. Potentially at the top of the trade screen?

> Note on that: We removed the trade history in favor of integrating the "trades" into the order history. But, with perpetuals we will have changes over time that come after the order was filled. I think we will need a separate trade history to be able to depict this information after a position was closed.

Good call, I guess we need this tab after all? 
A simple solution would be to pack it into the `history` of the order?

> timeline of fees for the position

I would not display the funding fee in the position but just have it in the `trade history` - this is more inline what other platforms do.
