### ISSUE TITLE
Use background tasks to notify users about expired position

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1185]
Periodically check whether the user has an open position and alert the user when the position is about to expire or has already expired, so that they can open the app and react to it appropriately.

**Comment by bonomat** [comment]
If this works, we can replace https://github.com/get10101/10101/issues/1070

**Comment by klochowicz** [comment]
After quite a bit of research and experimenting, these are my findings:

I managed to have a solution that stored position expiry time (if there was one) inside shared preferences (which can be accessed from a separate isolate in a background handler), which was checked inside a handler that was triggered by the "background fetch" mechanism that iOS supports and then display a notification to the user.


Unfortunately, this is just not reliable enough for our use-case :( background fetches can be scheduled "at some point, but not more often than 15 mins" by the device, and depending on how quickly you've completed your previous one (and some other undisclosed factors), next one might be scheduled sometime soon.

This was a rather frustrating debugging experience; I couldn't get it to be triggered reliably outside of XCode 😭 (only sometimes it would be triggered)

Note that this problem only concerns  iOS, Android is super chilled; one can schedule periodic tasks that do whatever you'd like.

**Comment by klochowicz** [comment]
I was hoping to at least have a data message being sent once every 12h or so from FCM to trigger the data task, but alas only notifications can be sent when an app is force-closed on iOS, not data messages.

**Comment by klochowicz** [comment]
I'm closing this issue in favour of https://github.com/get10101/10101/issues/1070 , because I actually managed to reliably de-risk and de-scope the other one.
