### ISSUE TITLE
Testing document for mobile

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#12]
A document which describes what and how we are testing our mobile app.
E.g. do we need to run a simulator, do we write unit tests for the front end, do we write integration tests, etc.

**Comment by bonomat** [comment]
I propose to not write this completely alone as the discussion on the PR can be unsatisfying. Instead, grab a sparring partner and discuss before hand.

**Comment by luckysori** [comment]
I cannot find the matching document, but this was done.
