### ISSUE TITLE
Store app logs in UTC timezone

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#1202]
it's really tricky to debug things and see the interactions with the coordinator when we look at the app logs, because FLogs stores the logs in local time - and there seems to be no way to change it.

One quick way to fix this would be having our own wrapper,  something like this:

```dart
import 'package:f_logs/f_logs.dart';

void log(String message) {
  FLog.logThis(
    text: message,
    type: LogLevel.INFO,
    dataLogType: DataLogType.DEVICE.toString(),
    timestamp: DateTime.now().toUtc().toIso8601String(),  // Manually set UTC time
  );
}
```

we could make it fancy and have one function per log level.

Note that this would also greatly reduce our exposure to the deprecated FLogs package, and would make it easier to switch it sameday - see #1092 .

**Comment by bonomat** [comment]
Nothing wrong about this :D
