### ISSUE TITLE
No pending funding transaction found!

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1205]
I just opened a new JIT channel on mainnet and did not pay JIT channel opening fees, because the transaction could not be found upon the channel ready event.

The following error happened when trying to register the funding transaction to get payed.

```
Failed to fetch transaction: 5430bccdf192cf1df8475e9d72bb6403cd8d714e2fad064fcdc6795bffb7c44a from esplora. Error: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) } 
```

This results in no funding transaction getting registered and thus when trying to pay for it, it fails because we do not know how much fees we have to pay.

**Comment by holzeis** [comment]
I think @luckysori suggestion to generally setup an async task that is regularly checking if fees have to be paid may be the less failure prune approach here.

**Comment by holzeis** [comment]
Maybe as well fixed, when running our own esplora instance.

**Comment by bonomat** [comment]
I assume the problem was that we checked too fast for the transaction. It was eventually confirmed. 
https://mempool.space/tx/5430bccdf192cf1df8475e9d72bb6403cd8d714e2fad064fcdc6795bffb7c44a


I wonder if we should bother with this or try to build out the proper LSP flow https://github.com/get10101/10101/issues/843?

**Comment by bonomat** [comment]
Unasigning myself again. I believe this requires a different fix than just using our self-hosted esplora instance. 
I propose to 
- make the fetching more robust, i.e. retry
- look into if we can use the LSP flow from #843

**Comment by holzeis** [comment]
> I assume the problem was that we checked too fast for the transaction. It was eventually confirmed. 

The broadcast should have happened over the same explora endpoint and it was definitely broadcasted before we make the query. Why do you think that we checked too fast? Shouldn't we also be able to fetch unconfirmed transactions?

**Comment by holzeis** [comment]
My guess is that we run into a 429 too many requests error.

**Comment by bonomat** [comment]
I don't think so, we would have seen this in the log as shown here: https://github.com/get10101/10101/issues/658#issue-1717224782

**Comment by holzeis** [comment]
> I don't think so, we would have seen this in the log as shown here: https://github.com/get10101/10101/issues/658#issue-1717224782

I don't think so look at the error

Error: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }

The response couldn't be parsed. We do not check if the http request was actually successful. My guess is that if we would check that we would have seen a 429 error.

**Comment by bonomat** [comment]
> Error: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }

Well, I guess we won't be able to determine who is right or wrong because in both cases a response is returned which cannot be parsed into JSON.

In case of 429  we get: 

```
<html>\r\n<head><title>429 Too Many Requests</title></head>\r\n<body>\r\n<center><h1>429 Too Many Requests</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n
```

in case of 404 (tx not found), we get

```
Transaction not found
```

So let's just hope this was fixed in https://github.com/get10101/10101/pull/1236 or when using our own esplora instance :)

p.s. I wrote a little client and bombarded them with requests... now I believe they blacklisted me forever 😅

```
Caused by:
    0: error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
    1: dns error: failed to lookup address information: nodename nor servname provided, or not known
    2: failed to lookup address information: nodename nor servname provided, or not known
```
