### ISSUE TITLE
App gets stuck when processing `SubChannelCloseConfirm`

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#1238]
Full context in https://github.com/get10101/10101/issues/1230.

### Observations

We don't yet know where the app hangs exactly, but, given that the app encountered a stale `ChannelManager` compared to the `ChannelMonitor` on startup, the app must have completed the `ChannelMonitor` update, but _not_ the corresponding `ChannelManager` update. This might help locate the problem area.

Timebox investigation 1 day

**Comment by holzeis** [comment]
@luckysori and I were able to manually reproduce that issue. Our strong assumption is that while we were processing the `SubChannelCloseConfirm` message we were also processing the `periodic_check` at the same time.

Both try to acquire the `channel_monitor.lock`. We suspect that for this issue to happen, the `periodic_check` acquired the lock first and blocked the processing of the `SubChannelCloseConfirm` message. The `periodic_check` is then calling esplora for the block at the next known height. *Note, this seems only to be an issue if the `chain_monitor` is not up to date with the latest blocks.* Depending on how many blocks need to be catched up and how responsive esplora was this could take a long time. During that time the processing of the dlc message is blocked, until the periodic check is done.

We concluded the following two next steps.

- [ ] Add start and end timestamp logs around the periodic check to verify if that is the case if the app gets stuck again
- [ ] Finish the PR https://github.com/p2pderivatives/rust-dlc/pull/122/ (already opened sometime ago by @luckysori ) and get rid of the expensive `chain_monitor.lock` when processing the `periodic_check`.

However, we also suspect that this issue should have already been mitigated by using our own esplora instance.

**Comment by luckysori** [comment]
I think we can close this ticket because we understand why it was happening and we have not experienced it since we migrated away from using Blockstream's Esplora instance.

Once we merge https://github.com/p2pderivatives/rust-dlc/pull/122 and update to a new version of `rust-dlc`, we ensure that we hold onto the `ChainMonitor` lock for as little as possible, so it will be very unlikely that opening and closing positions will be slowed down by waiting on acquiring said lock.
