### ISSUE TITLE
Address non-standardness of on-chain wallet seed

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#1241]
We currently use BIP39 to generate a mnemonic phrase, but instead of using it directly we hash it in two different ways to derive one seed for the on-chain wallet and another for LDK's `KeysManager`. The advantage of this is that we only have to back up one seed for two purposes. In practice this is not actually useful because (1) we have not yet implemented a way to [recover a 10101 wallet using this seed](https://github.com/get10101/10101/issues/1079) and, more importantly, (2) you would not be able to recover the whole 10101 wallet just with this seed[^1].

The main disadvantage of the current approach is that a user cannot use their mnemonic phrase to recover their on-chain funds using a different wallet. If they do want to recover their on-chain funds they would need to use something like https://github.com/get10101/bip39-to-bip32/ to learn the BIP32 key of their on-chain wallet. Then they could import it into a tool such as Sparrow. This whole process is unnecessarily complicated.

I would propose to simply generate one BIP39 seed for the on-chain wallet and a separate seed for LDK and to **only expose the on-chain seed to the user in the `Back up your wallet` screen**. The LDK seed is not useful on its own AFAIK and we should probably back it up with the rest of the LDK data[^1].

[^1]: We need to start by addressing https://github.com/get10101/10101/issues/1098.

_Originally posted by @luckysori in https://github.com/get10101/10101/issues/1079#issuecomment-1701993222_

**Comment by klochowicz** [comment]
As discussed with @luckysori , I'm removing it from the epic, because we can finish the epic without addressing this.

Furthermore, our seed is doing more than regular on-chain wallet recovery, so it can be considered a feature to encourage recovery with a fresh instance of 10101 (e.g. so one can claim all the off-chain funds, close positions etc.).

I would recommend closing the ticket altogether for now.

**Comment by bonomat** [comment]
Agreed.
