### ISSUE TITLE
Never panic on startup

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#1247]
**Describe the bug**

Currently there is a number of things that we panic on in the backend during startup; instead, we should throw an exception in Flutter and allow the frontend to react appropriately instead of crashing the app.

One of the most unfortunate things about it is lack of logs we have experienced recently (Apple crash report did not include the cause of the crash at startup, and the user can't do anything about it).

**To Reproduce**

-Not sure whether it's easy to reproduce a fatal crash like that, but I'll keep trying.-

Easiest way to reproduce a crash at startup is to turn off mobile data before starting the app - 10101 does not start without internet :( 

**Expected behavior**

Even if there's a showstopper bug, the user should be able to see:
1) what went wrong
2) be able to send 

**Additional context**

it should be possible to inspect the code manually to ensure we're not crashing at startup in any case, and instead handle it gracefully.

I've added `critical` label to this issue as the user can't access their funds and it's hard to be able to help them in any meaningful way as they cannot share their logs easily.

**Comment by bonomat** [comment]
> Currently there is a number of things that we panic on in the backend during startup; 

It sounds like you know what could panic. Can you mention them here please?

**Comment by holzeis** [comment]
There is an open discussion on https://github.com/get10101/10101/pull/1206. Lets get to a conclusion there, and decide whether or not to keep that ticket or close it.
