### ISSUE TITLE
When building for Android getting error : "Execution failed for task ':app:processLocalDebugGoogleServices'"

### ISSUE THREAD

**Issue by lgleasain** [get10101/10101#1250]
**Describe the bug**
When building for Android, I'm getting the error "Execution failed for task ':app:processLocalDebugGoogleServices'" and the app will not install on a device.

**To Reproduce**

Build the app for Android using 

just all-android

on the command line. 

**Expected behavior**
The app should install on an Android device

**Screenshots**

**Smartphone (please complete the following information):**

Sunmi V2s and a emulator running Android api 33

** Logs
Android app will connect to 172.21.0.241 for 10101 services
Using hardware rendering with device sdk gphone64 x86 64. If you notice graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...

FAILURE: Build failed with an exception.

Execution failed for task ':app:processLocalDebugGoogleServices'.
> No matching client found for package name 'finance.get10101.app.local'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Additional context**

This is happening on MacOs

**Comment by Restioson** [comment]
Please provide additional info - was this a mistake?

**Comment by Restioson** [comment]
Circling back to this since its been updated with details - could you try this again and see if it's reproducible? Android support has come a way since the ticket was opened.

**Comment by Restioson** [comment]
Now I am getting this on linux :sweat_smile:

**Comment by Restioson** [comment]
Think I found a fix, will open a PR
