### ISSUE TITLE
Sync should not block the whole app

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1258]
Currently we show the app as syncing after the startup and thus hiding the transaction history and also rendering the usable balance as 0 (preventing the user from trading).

The only thing that we have to check upon startup is if the channel is still open (meaning that the funding transaction hasn't been spend) if so the user should be free to use the app. We don't have to wait for the whole on-chain sync to finish.

**Comment by bonomat** [comment]
Not 100% if this is the case, but we can syn the on-chain wallet separately from the off-chain wallet and display it respectively. We should be able to continue once the off-chain wallet is synced which is usually just a couple of requests.

**Comment by bonomat** [comment]
Assumption is this is an easy win: timbox to 2h or move into future iteration.
