### ISSUE TITLE
Integrate in-app waiting list

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1259]
We want to be able to control who can use our app (meaning, who can acquire in-bound liquidity)
1. With the end of this month, we will move away from ViralLoops stopping us from receiving more sign-ups
2. We want to launch Android which can be heavily simplified by simply publishing an APK
3. It would be cool to simply let users download our app and only get access once there is space - this is also in preparation for our public launch

To do this, we want an in-app waiting list. 
A simple version could look like this: 

1. user starts the app and see the well-known `enter email` field.
2. user enters his email address
  1. if user is on the waiting list and enabled for beta, the user can proceed
  2. if the user is not on the waiting list, we add him to the waiting list
  3. if the user is on the waiting list but not yet enabled for beta, the user cannot proceed (or may not fund the wallet etc.)

Ideally we have an email verification process which enforces real emails aswell as ensures that the user is in control of the email, e.g. we could send a magic link to the user which he has to click to open the app. 
Otherwise we have two challenges: 

1. a user could enter an invalid email defeating the purpose of having an email in the first place
2. a user could share his email or use one of someone else to enter the app

**Comment by klochowicz** [comment]
@bonomat how about adding one more table into our database?
We could prepopulate it it off by copying all the emails from the current users table, with a POST request to add new email to the beta users.

**Comment by bonomat** [comment]
Yes, I'd imagine a simple table like this: 

<table>
<tr>
 <td>email
 <td>is_enabled_for_beta
 <td>timestamp
</table>

and then add all existing users with `is_enabled_for_beta=true` and all our waiting list users with `is_enabled_for_beta=false`

**Comment by holzeis** [comment]
@bonomat how will the flag be displayed in the app if the user is not enabled?

**Comment by bonomat** [comment]
Do you want me to give you a design or a rough idea? 

The flow idea is mentioned in the ticket and it could be a simple message as: 

```
Sorry mate, you are not part of the beta yet, come back tomorrow.
```

Note: this ticket was created before our meeting yesterday and I hope @klochowicz took that into account.

**Comment by holzeis** [comment]
A rough idea should be enough.

I was wondering if the user would be blocked out directly at the welcome screen or can browse around but not fund the wallet.

**Comment by klochowicz** [comment]
> Note: this ticket was created before our meeting yesterday and I hope @klochowicz took that into account.

Could you be more clear please? Does this change anything in terms of scope of the ticket or whether we'd want to do it or not?

**Comment by klochowicz** [comment]
> A rough idea should be enough.
> 
> I was wondering if the user would be blocked out directly at the welcome screen or can browse around but not fund the wallet.

I'll see whether I can pull off easily a way to allow browsing without funding - I've got a plan for that :-)

**Comment by bonomat** [comment]
> Could you be more clear please? Does this change anything in terms of scope of the ticket or whether we'd want to do it or not?

Yes, it would change the scope of this ticket. In the planning call we said that we don't want an in-app waiting list but simply tell the user that there is not enough liquidity available at the moment and they should try again later. 

Please correct me if I remember this wrongly @holzeis / @luckysori

**Comment by klochowicz** [comment]
> > Could you be more clear please? Does this change anything in terms of scope of the ticket or whether we'd want to do it or not?
> 
> Yes, it would change the scope of this ticket. In the planning call we said that we don't want an in-app waiting list but simply tell the user that there is not enough liquidity available at the moment and they should try again later.
> 
> Please correct me if I remember this wrongly @holzeis / @luckysori

I assumed that was for the 'open' beta time, and that this ticket is relevant for the purposes of closed beta, especially with Android release getting traction.

**Comment by bonomat** [comment]
I we have this feature as described in the ticket, we can simply use it in the public beta as well to control access to the app. 
My understanding is that for the closed beta time we don't need this feature. We can simply add users to the google play store.

**Comment by bonomat** [comment]
Replaced by #1398
