### ISSUE TITLE
Paying an already-paid invoice doesn't create a failed payment history item

### ISSUE THREAD

**Issue by Restioson** [get10101/10101#1260]
Paying an invoice that the app recently paid doesn't leave any failed history item.

**To Reproduce**
1. Fund wallet with 100 000 sats from the faucet
2. Grab an invoice from the coordinator: http://localhost:8000/api/invoice?amount=9999
3. Click 'send' and input the invoice
4. Pay the invoice
5. Click 'send' and input the same invoice
6. Click back to history - no failed payment will be there

**Expected behavior**
There should be a failed payment history item

**Comment by bonomat** [comment]
Unfortunately LDK does not guarantee that an invoice is being paid twice. 

https://github.com/lightningdevkit/rust-lightning/blob/448b191fec4c6d1e9638c82aade7385b1516aa5d/lightning/src/events/mod.rs#L481C2-L482

We will need to implement this logic on our side to prevent paying the same invoice twice.

**Comment by Restioson** [comment]
I mean this in the other way around - this is for outbound payments. It correctly stops us from paying it but the failed payment doesnt show up

**Comment by holzeis** [comment]
Do we really want to pollute the history for this failed payment? IMHO not having failed attempts in the history is ok.

**Comment by bonomat** [comment]
> Do we really want to pollute the history for this failed payment? IMHO not having failed attempts in the history is ok.

I guess it's fine to not have these failed payments in our history. Let's close this ticket.

**Comment by Restioson** [comment]
> Do we really want to pollute the history for this failed payment? IMHO not having failed attempts in the history is ok.

I'm not sure, I feel like the user might want to know that they attempted to make a payment and it failed for some reason. Maybe specifically with double payments it's okay, especially if the user is the one who paid it already.
