### ISSUE TITLE
Generate liquidation CETs so we can force close on liquidation events

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1263]
This might need some research, but in ItchySats we had the idea to have liquidation CETs for every hour on the hour added to our DLC so that we can liquidate on-chain in the worst case. 

https://github.com/get10101/10101/issues/1264 might be the better solution for now.

**Comment by holzeis** [comment]
> https://github.com/get10101/10101/issues/1264 might be the better solution for now. 

I guess we will need both
