### ISSUE TITLE
Settings shows branch `head` not `main`

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1266]
I swear it used to say `main` and not `head` in here. Did we (me) mess something up somewhere?

![Image](https://user-images.githubusercontent.com/224613/266696120-08a1f63e-19cc-4930-a36e-50ba36ea7002.png)

**Comment by holzeis** [comment]
Mine shows `main`. Can we close that ticket?

![image](https://github.com/get10101/10101/assets/382048/e72f8f9d-acb2-49e1-aedd-80a2ca5c45af)
