### ISSUE TITLE
Register the maker as user

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1269]
We currently can't reference our database `trader_id` model to our user table as the maker is not registered.

**Comment by bonomat** [comment]
We can do this manually by inserting it directly into the DB

**Comment by holzeis** [comment]
Now that I think of it we will have to do it also for our regtest maker and local setup, otherwise the foreign key will fail on these environments. :/

**Comment by Restioson** [comment]
maybe a simple SQL or bash script?
