### ISSUE TITLE
Limit order may be deleted when set to taken

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1272]
At the moment we load all open limit orders with the opposite direction of the market order and try to find a match.

Once the match is found we set the limit order to taken.

It could happen that the order gets deleted in between reading the order and setting it to taken.

We should prevent that from happening!

**Comment by bonomat** [comment]
If we don't fix this it could happen that a trader takes an order which was already deleted.

**Comment by holzeis** [comment]
Closing as we do not delete the makers order anymore.
