### ISSUE TITLE
Receiving on-chain funds should not direct to the receive lightning screen

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1274]
![image](https://github.com/get10101/10101/assets/382048/8be3bee8-98e2-466e-bca1-3927daee80a6)

**Comment by bonomat** [comment]
Wouldn't call it a bug... it's just not implemented 😅

**Comment by bonomat** [comment]
Shall we close this in favor of https://github.com/get10101/10101/issues/1177 ?

**Comment by holzeis** [comment]
Closed in favor of #1177
