### ISSUE TITLE
Model position resizing in trade history

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1275]
Mock resized contracts to implement the frontend. Maybe add the test that @luckysori  never added.

**Comment by bonomat** [comment]
Simplest solution is to not add any changes to the frontend at all: re-sizing a position is done buy simply hitting the buy/sell button again and the position updates accordingly. 
The trade history should then only show the new order. 

I think we can safely close this unless I'm forgetting something.

**Comment by luckysori** [comment]
> Simplest solution is to not add any changes to the frontend at all: re-sizing a position is done buy simply hitting the buy/sell button again and the position updates accordingly. The trade history should then only show the new order.
> 
> I think we can safely close this unless I'm forgetting something.

Haha you had already written this and then I said the same thing in our meeting.
