### ISSUE TITLE
Candlestick chart in trade tab

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#128]
A (simple) candlestick chart that shows the BTC/USD price over time.
I recommend using the [`canldestick` flutter package](https://pub.dev/packages/candlesticks/example); I pushed the example code to this branch: https://github.com/get10101/10101/tree/candlestick-chart - see:

https://github.com/get10101/10101/blob/candlestick-chart/mobile/lib/features/trade/candlestick_chart.dart#L1-L47

Scope: 

- [ ] Periodically fetch data from BitMEX
- [ ] Convert data into format needed for candlestick chart (it's based on Binance data)
- [ ] Integrate candlestick chart in UI

Open questions:

- Should the market price of our orderbook be reflected in the chart for the MVP, or is it good enough to display BitMEX price data? CC @bonomat

**Comment by da-kami** [comment]
note: candlestick package words on iOS, mac, android:

Screenshot from my android phone:

![image](https://user-images.githubusercontent.com/5557790/218606468-912c607f-79e7-4922-8d46-9e6f138ca1d2.png)

iOS simulator:

![image](https://user-images.githubusercontent.com/5557790/218606536-a230c0b6-a482-45aa-ad89-105e756e49d5.png)

**Comment by holzeis** [comment]
It would be nice if the candlestick could also show a red line indicating the liquidation price. I've heard that request in one of our user interviews and seen that feature in lnmarkets and kollider. If too much for this ticket, I can create a separate ticket for it.

**Comment by bonomat** [comment]
>  Periodically fetch data from BitMEX

It might be worth to use the [websocket connection](https://www.bitmex.com/app/wsAPI#Subscriptions) from Bitmex for that.

> Should the market price of our orderbook be reflected in the chart for the MVP, or is it good enough to display BitMEX price data? CC @bonomat

Mhm, there is no such thing as a `Market price`, we could display mid-market, which is half-way between best bid and ask. I'd say it depends on how _good_ or _bed_ our rates are 😬
