### ISSUE TITLE
Enable resizing for trading

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1285]
Stitch all resizing logic up to support it e2e

**Comment by jooray** [comment]
Resizing position is basically taking a new position and then refresh only the resulting one. No need for special logic there.

If I'm $100 long and want to resize it to $50, I can open another short for $50. And when it comes to renewal, I reopen only $50 long.

**Comment by Restioson** [comment]
Right now I do not believe that we allow multiple positions but this could be a valid implementation strategy

**Comment by jooray** [comment]
I hope there will be other pairs (like BTC/EUR), so I think multiple positions are required long-term anyway.

The advantage is that you will not close before expiry, that makes the market work a bit better - you need to find a price when resizing according to current market prices. 

There are pros and cons of both (you need more collateral if you do it this way), but it makes pairing longs and shorts and market dynamics much more straightforward.

**Comment by Restioson** [comment]
> I hope there will be other pairs (like BTC/EUR), so I think multiple positions are required long-term anyway.

This is a bit further off than position resizing but I think given it was possible in ItchySats it will likely be on the roadmap (@bonomat correct me if I'm wrong)

**Comment by bonomat** [comment]
Blocked on https://github.com/get10101/10101/issues/1283

**Comment by bonomat** [comment]
This should be done together with #1543
