### ISSUE TITLE
Design Update UI to open bigger channels

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1286]
This ticket is about updating Figma mocks for allowing users open a bigger channel. 

See here: https://github.com/get10101/10101/issues/1280

**Comment by holzeis** [comment]
![open-channel](https://github.com/get10101/10101/assets/382048/9d223d19-aa72-4efa-8ce2-374f2b10f4b5)
![Receive Funding](https://github.com/get10101/10101/assets/382048/0569fc87-cada-415f-bea0-bee90e0625b9)
![Receive Funding-1](https://github.com/get10101/10101/assets/382048/d0b41a7f-cf4b-47f3-b4ee-ede833255625)
