### ISSUE TITLE
Share on-chain wallet address to receive payments

### ISSUE THREAD

**Issue by Restioson** [get10101/10101#1291]

**Comment by Restioson** [comment]
Is there a way to share the address via QR code? Should the QR code just have the address as its value?

**Comment by holzeis** [comment]
Have a look how it is done in zeus. I propose to do it the same way. It looks like a standard? but couldn't find it on a quick search.

### lightning
lightning:[invoice]

### bitcoin
bitcoin:[address]?amount=[btc]

**Comment by holzeis** [comment]
> > bitcoin:[address]?amount=[btc]
> 
> Ah, so we can include the amount? Nice! Seems to be covered by [en.bitcoin.it/wiki/BIP_0021](https://en.bitcoin.it/wiki/BIP_0021)

Thanks for sharing the BIP :)

**Comment by Restioson** [comment]
I also found https://bitcoinqr.dev/
