### ISSUE TITLE
Make use of Rapid Gossip Sync

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#1304]
**Is your feature request related to a problem? Please describe.**

it takes up to 2 mins to sync network graph. This is a problem when initialising lightning node, especially on mobile.

**Describe the solution you'd like**
RGS should save both bandwidth and time

**Describe alternatives you've considered**

Not sure if there are any?

**Additional context**

https://www.notion.so/get10101/TABConf-report-42f7343fd8224381bb4dd6db464038c7?pvs=4

I'm proposing using LDK RGS server, no need to roll out our own for now.

**Comment by bonomat** [comment]
We want to look into this after #1472
