### ISSUE TITLE
Re-design the position screen

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1317]
The idea is to make it simpler: 
- [x] define requirements
- [x] mock them in figma

**Comment by bonomat** [comment]
Designs can be found in Figma

The idea is to show only minimal but crucial information in the default overview. When clicking on it, a modal opens from the bottom which shows more details. The close button leads to the well-known "swipe to confirm screen".

https://github.com/get10101/10101/assets/224613/4cec06bf-71f3-469c-9a0f-217e3e4d7c80

**Comment by holzeis** [comment]
One caveat though is that the close button is again hidden 🙈

Since we do not support resizing yet how about showing a hovering close button instead of the buy and sell button (when a position is open)
