### ISSUE TITLE
Run push notification experiment

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1321]

**Comment by klochowicz** [comment]
description of the experiment is here: https://github.com/get10101/meta/issues/235

@bonomat @holzeis please review it and give feedback whether it has a green light.

**Comment by holzeis** [comment]
Can we close this ticket? I think we don't need to experiment if push notifications should be added. The proposed experiment can be run as a campaign.

**Comment by bonomat** [comment]
Closing as this can be run as a campaign.
