### ISSUE TITLE
Recover from a intermediate rollover protocol state

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1322]
Our current logic for recovering from a stuck rollover state is not ideal. It is based on the logic that both sides will rollback to their last "stable" state and retry to rollover. However, there are the following caveats to that approach

1. It is based on the assumption that both parties rollback, depending on the state this might be risky to do.
2. If the coordinator already processed the `RenewFinalize` message, but the app failed to process the `RenewRevoke` message the coordinator can't rollback anymore and the contract state can't be recovered. The app though would still rollback to the last "stable" state and can only close the position afterwards.

This is not optimal and should be properly fixed in `rust-dlc`. The discussed solution approach entails the following key points.

- Extend the sub channel recovery logic in the `sub_channel_manager::on_channel_reestablish`
- Add reestablish flags to the channel to indicate which side needs to take actions.

**Comment by holzeis** [comment]
Reopening to cover a proper fix in rust-dlc.

**Comment by bonomat** [comment]
@holzeis please update the description and mention what needs to be done. Feel free to copy over from the PR.
