### ISSUE TITLE
Funding Rate feed and handling updates in the UI

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#133]
Scope: 

- [ ] Funding Rate feed in Rust backend that streams funding rate changes to UI
- [ ] ChangeNotifier for funding rate 
- [ ] Handle funding rate updates in `TradeValuesChangeNotifier` 
- [x] TODO: decide on where the funding rate is coming from. Note: in the past we said the maker defines the funding rate using BitMEXes funding rate and adding a spread. 

I would opt to keep this separate from price updates (https://github.com/get10101/10101/issues/132) this time, because I think it is a different concern.

**Comment by bonomat** [comment]
> I would opt to keep this separate from price updates (https://github.com/get10101/10101/issues/132) this time, because I think it is a different concern.

Definitely, please keep it separate.

**Comment by klochowicz** [comment]
@bonomat when do you see us adding funding rates?

**Comment by bonomat** [comment]
As soon as we have perpetuals.

**Comment by da-kami** [comment]
We need them in preparation for stablesats, but knowing ItchySats perpetuals added some complexity. 
Will perpetuals get priority within Q3?

**Comment by bonomat** [comment]
> Will perpetuals get priority within Q3?

Yes, definitely

**Comment by holzeis** [comment]
> ** TODO: decide on where the funding rate is coming from. Note: in the past we said the maker defines the funding rate using BitMEXes funding rate and adding a spread.

Let's use the bitmex funding rate for now until we have more volume on the orderbook.

**Comment by holzeis** [comment]
show funding rate on the trading screen.
