### ISSUE TITLE
Payment shown as successful even though it's not yet done

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1337]
When sending a lightning payment we immediately see a success dialog but the payment was not yet successful nor did it fail. 

After some time, the payment in the history is shown as success or as failed. 

- production setup: iOS
- commit hash `843f205452af6a972eb10deddaea68e9425c221d`
- build number: 2139
- version 1.2.6

Error in logs says: no route found.

We could simply change the dialog or block until the payment succeeded or failed.

**Comment by holzeis** [comment]
Fixed on main!
