### ISSUE TITLE
Could not delete `order`

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1347]
Logs from the database: 

- setup: regtest VM

`2023-09-21 19:41:14.059 UTC [123] ERROR:  update or delete on table "orders" violates foreign key constraint "matches_order_id_fkey" on table "matches"`

Could find relevant logs in the coordinator yet, maybe we are swallowing the error?

**Comment by holzeis** [comment]
I'd argue we don't have to delete the makers order anyways, as with 

https://github.com/get10101/10101/blob/b8def79fb05f2ae608f6878483528e74b9028de6/coordinator/src/orderbook/trading.rs#L157-L161

we are anyways setting all expired limit orders to `Failed` before looking for a match.
