### ISSUE TITLE
User has no fcm token

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1348]
I re-installed the regtest app and registered a new user but the user db does not show me having an fcm token.

- regtest
- iPhone
- build 2152
- commit  8fa4e95bf25d3287d2a95e1d2e569058c33abc33
- node  id: 036a564b61ee0e74c34751a42f910beded04cdb65cad67c9104eb0fee5ab96ce03

logs: 

[2023-09-22_064343.log](https://github.com/get10101/10101/files/12696858/2023-09-22_064343.log)

**Comment by holzeis** [comment]
related log message, just found in my logs.

```
Error storing FCM token: FfiException(RESULT_ERROR, NODE is not initialised yet, can't retrieve node info, null)
```

**Comment by holzeis** [comment]
another source for that issue. It appears the register beta endpoint will overwrite the fcm token if it happens later that the fcm token update. That is very likely if the user takes some time to enter her email before proceeding, because we are already initializing the app in the background.
