### ISSUE TITLE
Failed payment lead to force-closed channel

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1349]
Here is what happened in a nutshell

1. User (userid see below) funds JIT channel using Lightning invoice (payment hash see below)
2. JIT channel gets created correctly (funding tx see below)
3. User opens a DLC position
4. User wants to receive more using a Lightning invoice
5. The HTLC gets added as in-bound and out-bound (from coordinator's perspective)
6. User goes offline: It looks like we never recieved `Received a valid revoke_and_ack` and this payment does not fully succeed
7. The coordinator's neighboring node force-closes the channel on the coordinator due to the payment timeing out and is able to claim back his funds (refund the HTLC)
8. We still have a valid channel, and valid sub_channel with our user

- User id: `0367199f1c9e29f72adf87ec5f33efe3a26c79382e7fbd64c3afbd6d94c3e6d827`
- initial channel opening id: `2f1caf9afa469f65a230481bb8729366ca66ad0bec8ba76a9a406913dad849e3`
- payment hash of failed payment: `fc8a5836ded0012bcd0f436e3f20d130143c95fa39d62d026932431a60ddb5ff`
- User channel: `e349d8da1369409a6aa78bec0bad66ca669372b81b4830a2659f46fa9aaf1c2e`
- force-closing txid: `4d19849d2a3a3346f2da2d117c02f5facc2679a3a4f7762ec137eadb2d0be421`

In this case, I believe we should have force-closed the channel on our user as well because we run into the danger that if the user comes back online, he will be able to claim the HTLC "stealing" funds from us. 

[Useful grafana query](https://itchysats.grafana.net/explore?orgId=1&panes=%7B%22B-_%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22coordinator%5C%22,setup%3D%5C%22get10101-production%5C%22%7D%20%7C~%20%5C%2240000000%5C%22%20%7C~%20%5C%22amount%5C%22%7C%20json%22,%22editorMode%22:%22code%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D%7D%5D,%22range%22:%7B%22from%22:%221694896346038%22,%22to%22:%221694975422891%22%7D%7D%7D&schemaVersion=1)

**Comment by bonomat** [comment]
I've asked in the LDK discord https://discord.com/channels/915026692102316113/996090062779469974/1154648361048211557

**Comment by bonomat** [comment]
My assumption that we should have force-closed the outgoing channel the latest when the in-coming channel was force-closed by the other party.

**Comment by bonomat** [comment]
Given the user did not come online so far, we should probably force-close his channel.
Any thoughts on this @holzeis / @luckysori ?

**Comment by holzeis** [comment]
Is it a regular ln channel without dlc? Then let's go for it and give the user a heads up.

**Comment by bonomat** [comment]
It still has a DLC attached to it and the position looks ok expiring on `2023-09-23 00:00:00`

**Comment by holzeis** [comment]
Maybe we could reach out to the user to close the position and channel, collaboratively?

**Comment by bonomat** [comment]
> Maybe we could reach out to the user to close the position and channel, collaboratively?

Then we can just wait until the expiry. No, I wanted to avoid that he comes back online and claims the funds from the HTLCs and robs us 40k sats 😅

**Comment by bonomat** [comment]
Ok, the latest theory is that the HTLC was actually **not** fully added to the outgoing channel meaning we should have failed back the HTLC to the in-bound channel. 

The latest message we sent over to the other party _might_ have been the signed commitment transaction. 
I.e. we see `Handling UpdateHTLCs event in peer_handler` in the logs which is just before the messages are queued to be sent. However, shortly after wards we say we dropped the connection, meaning, maybe he never received the message. 

I propose to force-close this channel to see if the HTLC is attached.
- If it is, then we have an issue where we did not force-close a channel
- If it is not, then we have an issue where we did not fail back the HTLC

**Comment by bonomat** [comment]
Actually, let's not force close it, the fee rate for this channel is `10 sats/vbyte` 🙈

```
 {
    "channel_id": "e349d8da1369409a6aa78bec0bad66ca669372b81b4830a2659f46fa9aaf1c2e",
    "dlc_channel_id": "a8901d539e1efb7323e50ba868111524d8e5481fff860a62ba198056eeee34b9",
    "counter_party": "0367199f1c9e29f72adf87ec5f33efe3a26c79382e7fbd64c3afbd6d94c3e6d827",
    "update_idx": 281474976710655,
    "state": "Signed",
    "fee_rate_per_vb": 10,
    "fund_value_satoshis": 200000,
    "is_offer": true,
    "user_email": "noyaho@gmail.com"
  },
```

**Comment by bonomat** [comment]
Actually, let's not force close it, the fee rate for this channel is `10 sats/vbyte` 🙈

```
 {
    "channel_id": "e349d8da1369409a6aa78bec0bad66ca669372b81b4830a2659f46fa9aaf1c2e",
    "dlc_channel_id": "a8901d539e1efb7323e50ba868111524d8e5481fff860a62ba198056eeee34b9",
    "counter_party": "0367199f1c9e29f72adf87ec5f33efe3a26c79382e7fbd64c3afbd6d94c3e6d827",
    "update_idx": 281474976710655,
    "state": "Signed",
    "fee_rate_per_vb": 10,
    "fund_value_satoshis": 200000,
    "is_offer": true,
    "user_email": "hidden"
  },
```

**Comment by bonomat** [comment]
Looking more into this: 
it looks like this is only the symptom of another error which happened earlier: 

[Grafana logs](https://itchysats.grafana.net/explore?orgId=1&panes=%7B%22B-_%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22coordinator%5C%22,setup%3D%5C%22get10101-production%5C%22%7D%20%7C~%20%5C%22Failed%20to%20update%20ChannelMonitor%5C%22%20%7C%20json%22,%22editorMode%22:%22code%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1)

`
{"timestamp":"2023-09-22T23:28:54.311743401Z","level":"ERROR","fields":{"message":"Failed to update ChannelMonitor for channel e349d8da1369409a6aa78bec0bad66ca669372b81b4830a2659f46fa9aaf1c2e.","log.target":"lightning::chain::chainmonitor","log.module_path":"lightning::chain::chainmonitor","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-bee3233422fa4387/3b69cec/lightning/src/chain/chainmonitor.rs","log.line":700},"target":"lightning::chain::chainmonitor"}

{"timestamp":"2023-09-22T23:28:54.313458559Z","level":"DEBUG","fields":{"message":"Persistence of ChannelMonitorUpdate for channel e349d8da1369409a6aa78bec0bad66ca669372b81b4830a2659f46fa9aaf1c2e completed","log.target":"lightning::chain::chainmonitor","log.module_path":"lightning::chain::chainmonitor","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-bee3233422fa4387/3b69cec/lightning/src/chain/chainmonitor.rs","log.line":717},"target":"lightning::chain::chainmonitor"}

{"timestamp":"2023-09-22T23:28:54.313508467Z","level":"ERROR","fields":{"message":"Closing channel e349d8da1369409a6aa78bec0bad66ca669372b81b4830a2659f46fa9aaf1c2e due to monitor update ChannelMonitorUpdateStatus::PermanentFailure","log.target":"lightning::ln::channelmanager","log.module_path":"lightning::ln::channelmanager","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-bee3233422fa4387/3b69cec/lightning/src/ln/channelmanager.rs","log.line":5093},"target":"lightning::ln::channelmanager"}

...

{"timestamp":"2023-09-22T23:28:54.314650051Z","level":"TRACE","fields":{"message":"Updating ChannelMonitor: channel force closed, should broadcast: false","log.target":"lightning::chain::channelmonitor","log.module_path":"lightning::chain::channelmonitor","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-bee3233422fa4387/3b69cec/lightning/src/chain/channelmonitor.rs","log.line":2351},"target":"lightning::chain::channelmonitor"}
`

It's weird that the channel failed and was aparetnly force-closed but was still usable - he tried to receive a payment and closed the position a week later.

**Comment by holzeis** [comment]
Maybe related to https://github.com/get10101/10101/issues/1230
