### ISSUE TITLE
Localication for text values in the UI

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#135]
Introduce localization: https://docs.flutter.dev/development/accessibility-and-localization/internationalization
Identify all the text labels to be localized and pull them into a separate file.

**Comment by klochowicz** [comment]
@Restioson this could be related to one of your proposals? proper internationalisation would require:
- texts
- currencies
- dates

**Comment by Restioson** [comment]
> @Restioson this could be related to one of your proposals? proper internationalisation would require:
> 
>     * texts
> 
>     * currencies
> 
>     * dates

This would be related to #804, yes
