### ISSUE TITLE
Coordinator cannot send FCM notification on 10101 test app

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1350]
Error message in the logs: 

`
2023-09-22 06:49:30 DEBUG coordinator::notifications: Sent notification. Response: FcmResponse { message_id: None, error: None, multicast_id: Some(7791820302399795787), success: Some(0), failure: Some(1), canonical_ids: Some(0), results: Some([MessageResult { message_id: None, registration_id: None, error: Some(InvalidApnsCredential) }]) }
`

- token was an iPhone token

**Comment by holzeis** [comment]
```
2023-09-22 14:01:02 DEBUG coordinator::notifications: Sent notification. Response: FcmResponse { message_id: None, error: None, multicast_id: Some(7228435932288675776), success: Some(0), failure: Some(1), canonical_ids: Some(0), results: Some([MessageResult { message_id: None, registration_id: None, error: Some(InvalidRegistration) }]) }
```

**Comment by bonomat** [comment]
> InvalidRegistration

Seems to come from trying to run it on the simulator.

**Comment by klochowicz** [comment]
> > InvalidRegistration
> 
> Seems to come from trying to run it on the simulator.

Simulator cannot have a valid token, because APNS (Apple Push Notification Service) does not work there. :/

**Comment by holzeis** [comment]
@klochowicz what about the other error we get when using a token from the regtest app?

`InvalidApnsCredential`

**Comment by klochowicz** [comment]
> @klochowicz what about the other error we get when using a token from the regtest app?
> 
> `InvalidApnsCredential`

I suspect that it might be caused by our FCM token being issued for a different AppId.

**Comment by bonomat** [comment]
> I suspect that it might be caused by our FCM token being issued for a different AppId.

So you are saying we cannot test push notification on our regtest setup?

**Comment by bonomat** [comment]
> > I suspect that it might be caused by our FCM token being issued for a different AppId.
> 
> So you are saying we cannot test push notification on our regtest setup?

Answering my own question: 

we need a different GoogleService-info.plist (generated from Firebase) for each target/schema. [This describes](https://stackoverflow.com/a/60786452) how to do it.

**Comment by klochowicz** [comment]
or we can use our regtest setup with the same appId. I have proposed this ages ago, and even created a PR.

**Comment by holzeis** [comment]
> or we can use our regtest setup with the same appId. I have proposed this ages ago, and even created a PR.

Didn't we agree that having separate apps for test and prod is better, because you might want to delete the test app, but not the prod app?

**Comment by bonomat** [comment]
> Didn't we agree that having separate apps for test and prod is better, because you might want to delete the test app, but not the prod app?

Yes, this was the general consent.

**Comment by bonomat** [comment]
Got a working version for iOS in branch 'feat/flavors'
