### ISSUE TITLE
Store users last login to the users database

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1357]
`fcm_tokens` are deemed stale if they haven't changed in the last 2 months. For this reason and that its generally interesting how active are our users it would make sense to add a last login column to the users table.

_Originally posted by @bonomat in https://github.com/get10101/10101/pull/1355#discussion_r1334625081_

**Comment by holzeis** [comment]
@klochowicz are you still working on this ticket? if not, can you please change the status? thanks

**Comment by klochowicz** [comment]
> @klochowicz are you still working on this ticket? if not, can you please change the status? thanks

thanks for reminding me, I've created the PR.
