### ISSUE TITLE
Add tests for functions calculating margin, quantity, liquidation price

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#136]
Should be able to copy these over from ItchySats, because that's where the code came from.

**Comment by klochowicz** [comment]
This should be trivial to address

**Comment by da-kami** [comment]
Yes, I'll add it to the project as simple filler ticket - it's not urgent but it's tech debt that should be removed. If we ever touch the calculations again there should be tests that ensure nothing breaks.

**Comment by da-kami** [comment]
CC @bonomat - if you don't agree feel free to remove this ticket again.
