### ISSUE TITLE
Improve settings screen UI design

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1369]
I found this early design in our figma and was immediately reminded how ugly our settings screen is looking. I think investing a few hours could improve this already significantly.

![Image](https://github.com/get10101/10101/assets/382048/2c8daccf-b9da-4806-ab79-a357e7869aa5)

**Comment by taanii** [comment]
Can I work on this issue?

**Comment by holzeis** [comment]
> Can I work on this issue?

Hey @taanii, yes! Our settings currently look like that.

![image](https://github.com/get10101/10101/assets/382048/b66ba472-3303-455b-9ce8-fee6ac3aee28)

The attached screenshot in the ticket description should give you a hint on how we would like to improve the UI, but feel free to propose your own suggestions.

**Comment by bonomat** [comment]
> Can I work on this issue?

Definitely, feel free to join our public chat on matrix https://matrix.to/#/#tentenone:matrix.org or ping me or @holzeis directly.

**Comment by taanii** [comment]
Sure, thank you

**Comment by holzeis** [comment]
Leaving this here also as inspiration on how our settings screen could look like.

![image](https://github.com/get10101/10101/assets/382048/30647358-9f13-4e0b-b698-99cdb479c8d0)

![image](https://github.com/get10101/10101/assets/382048/e3d8d295-52c0-418c-8c97-ccc73a3fc4ac)

**Comment by bikraj2** [comment]
can you assign me this issue?

**Comment by holzeis** [comment]
> can you assign me this issue?

Done

**Comment by bonomat** [comment]
For now, I would only restructure what is already there and make it look "nice". Here a rough idea on how to structure the settings. 



- (Future[^1]) Editable settings:
  - Electrum/Esplora endpoint
- Node info: 
  - Node id
- Build details
  - Build version
  - Build number
  - Commit hash
  - Branch
- Coordinator
  - peer id
- Danger Zone: 
  - Close channel
  - Force-close channel
  - Share logs


Current settings screen: 

![image](https://github.com/get10101/10101/assets/224613/39e61e82-5a30-47c5-93ae-39032b0c886e)



[^1]: For now it will be read-only, but in the future this can be configurable
