### ISSUE TITLE
Send push notification when rollover windows starts

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1370]
Currently we only send a push notification about 1h before the position expires. That's very late given that the rollover window is the whole weekend.

We should notify the user when the rollover window starts and then probably every day once, until the user either rolls over or the position expired.

**Comment by klochowicz** [comment]
blocked by #1375

**Comment by bonomat** [comment]
I'm unblocking this ticket. 
https://github.com/get10101/10101/issues/1375 is an improvement we could do in addition but we want this feature now and there is no need to overdiscuss things.

**Comment by bonomat** [comment]
Unassigned you @klochowicz so that it can be picked up by anyone.

**Comment by klochowicz** [comment]
@bonomat I guess the simplest way is to adjust the constants `START_OF_EXPIRING_POSITION` and `END_OF_EXPIRING_POSITION a bit? and perhaps the text of the notification. 

I'm not sure whether we need more notifications before the expiry, as long as that one gets delivered?
