### ISSUE TITLE
cannot build on Xcode 15

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#1372]
**Describe the bug**

I was forced to update XCode to be able to build 10101 for my device running iOS 17.
10101 doesn't compile :(

**To Reproduce**

Bump XCode to the latest version and try to build the project

**Comment by bonomat** [comment]
I guess the recommendation is to not bump the version until we know it's not a problem anymore. 

cc @holzeis

**Comment by klochowicz** [comment]
> I guess the recommendation is to not bump the version until we know it's not a problem anymore.
> 
> cc @holzeis

it turned out to be fairly simple fix, updating cocoapods version locally + `pod update` in relevant directories seem to have solved it.

**Comment by klochowicz** [comment]
note: it still produces a scary warning (which I've reported to Apple), but it works file:

```
2023-09-25 14:45:16.948 xcodebuild[73842:699524] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22267/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
Function: createItemModels(for:itemModelSource:)
Thread:   <_NSMainThread: 0x6000008e0380>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
```
