### ISSUE TITLE
Add a mechanism for scheduling push notifications

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#1375]
Tokio scheduler is not ideal for "timed" tasks. 

It might be best if we set up daily jobs like #1370 and other "daily" notifications externally to our async runtime, namely by exposing a simple REST API and configuring an entry in crontab with a simple script to exercise it.

other considerations:
- at the very least, we'd need one more `RolloverWindowStart` notification kind. 
- we could make it flexible enough to "nudge" users who did not trade in X amount of time or were online/offline for Y time.

**Comment by holzeis** [comment]
> It might be best if we set up daily jobs like #1370 and other "daily" notifications externally to our async runtime, namely by exposing a simple REST API and configuring an entry in crontab with a simple script to exercise it.

It feels odd to put that kind of logic external to the app into a script.

Why not use something like https://github.com/mvniekerk/tokio-cron-scheduler or implement a scheduler ourselves? Shouldn't be that hard and the schedule pattern can be stored to the database so that we could easily change that if we wanted to (without a new release).

We could switch to a single schedule task that is running every few milliseconds and spawn tasks that need to be running. I think that will also improve our existing pattern of spawning a new task with sleeps for every little thing we have to do.

**Comment by klochowicz** [comment]
> > It might be best if we set up daily jobs like #1370 and other "daily" notifications externally to our async runtime, namely by exposing a simple REST API and configuring an entry in crontab with a simple script to exercise it.
> 
> It feels odd to put that kind of logic external to the app into a script.
> 
> Why not use something like https://github.com/mvniekerk/tokio-cron-scheduler or implement a scheduler ourselves? Shouldn't be that hard and the schedule pattern can be stored to the database so that we could easily change that if we wanted to (without a new release or restart).

that's a pretty nifty idea, I didn't see this project before! I guess the downside of this approach would be that we'd poll that scheduler every `100ms`, burning a lot of CPU cycles for no reason (if we're running this task once a day). That's the same problem why I didn't initially wanted to use tokio for this.

The obvious upside is ergonomics. And we don't need to be too precious with the 

It would have been awesome, if we could communicate failures somehow ergonomically from such job scheduler - it doesn't seem to be the case though ;/

> 
> We could switch to a single schedule task that is running every few milliseconds and spawn tasks that need to be running. I think that will also improve our existing pattern of spawning a new task with sleeps for every little thing we have to do.

in terms of raw efficiency it's more efficient right now, especially that in the worst case we can't let them pile on top of each other (that should never be the case, ideally we should not keep the runtime busy for nowhere near as long).

However, it might be way more ergonomic! especially if all these futures are being kept by the scheduler, freeing us from keeping all the remote handles. It might become a bit unwieldy if we pass the scheduler in, but at least we could try to see how it pans out and it's impact on performance.

**Comment by bonomat** [comment]
I'm giving this a try in #1370

**Comment by bonomat** [comment]
https://github.com/mvniekerk/tokio-cron-scheduler has been used in #1370
