### ISSUE TITLE
Received no PositionSoonToExpire push notification

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1376]
My position expired at 2am, but I only got PostionExpired notifications.

Environment: test

**Comment by bonomat** [comment]
![image](https://github.com/get10101/10101/assets/224613/101df1c4-072e-41b4-9ba8-98975eac479e)

I received it twice that my position had expired

**Comment by holzeis** [comment]
You received twice that your position has expired (https://github.com/get10101/10101/issues/1371), but none, that the position is soon to expire 😉

**Comment by bonomat** [comment]
@klochowicz : the ticket is still in TODO. I'm unassigning you so that it can also be picked up by other.
