### ISSUE TITLE
Wallet history does not show position openings and closings correctly

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1379]
Only one opening position is shown although I have multiple orders.

![image](https://github.com/get10101/10101/assets/382048/21e65725-d790-435f-9022-410b9bc6e630)

![image](https://github.com/get10101/10101/assets/382048/8d24eebe-9a61-422f-873a-5dc096868135)

**Comment by holzeis** [comment]
Not reproducible.

**Comment by holzeis** [comment]
Happened again on the latest test app version.

**Comment by Restioson** [comment]
Would you be able to show the info screens for the matching fees? Looks like they are there, but not the orders?

**Comment by holzeis** [comment]
Do you mean the details of the matching fee record?

![IMG_B353D58B03FF-1](https://github.com/get10101/10101/assets/382048/938544e0-089b-4673-a133-93c36f9ff80b)
