### ISSUE TITLE
Make fee only trading fee related

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#139]
Our Figma screenshot depicts a `Fee` which also ended up in the code (obviously). 

I think this is the `taker`/`maker`-fee, i.e. the fee you pay to the orderbook when adding or taking something from the orderbook.

<img width="410" alt="image" src="https://user-images.githubusercontent.com/224613/218881885-0b9c7fcd-7ce2-4a6a-9d58-97ba78c44664.png">

The action of this ticket is to think this through one more time and depict in the UI accordingly, potentially using an info popupt. 

_Originally posted by @da-kami in https://github.com/get10101/10101/pull/104#discussion_r1105239135_

**Comment by bonomat** [comment]
> @bonomat What about the fee for publishing the transaction. the rust-dlc dependency is calculating that fee on top of the margin. see also #193

I was not aware that the transaction fee is on top of the margin. I guess we will need to mention it here as well.

**Comment by luckysori** [comment]
This is either obsolete or covered in #224.
