### ISSUE TITLE
Dev environment is unusable - can't fund.

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#1390]
**Describe the bug**

doing `just all` fails *every single time* on my mac.

```
2023-09-28T03:48:39.742974Z  INFO fund: Manually broadcasting node announcement and waiting for a few seconds...
thread 'main' panicked at 'to be able to fund: Could not verify channel is open. Please wipe and try again', crates/tests-e2e/examples/fund.rs:44:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**

1. Run `just all`

**Expected behavior**

Funding should work, it did work for me *all the time* until recently.

**Comment by bonomat** [comment]
Might be worth pointing out that this is coming from `just fund`. 
The issue is that LND does not find/accept the node announcement of our coordinator. 

@holzeis : made it work on his machine and testnet setup. Maybe he can describe his (manual) steps to get it work?

**Comment by klochowicz** [comment]
it got fixed for me with #1387 - can you try if it works for you @bonomat @holzeis ?

**Comment by klochowicz** [comment]
I'm going to close it, as I am unblocked. if anyone still experiences this on master, please feel free to re-open :-)

**Comment by bonomat** [comment]
> it got fixed for me with #1387 - can you try if it works for you @bonomat @holzeis ?

just worked for me as well 🤷‍♂️

**Comment by klochowicz** [comment]
it started failing for me again, and after looking into it a bit, it was only due to the peer_alias not being populated 🤔 which has no impact on the ability to use the channel.

**Comment by holzeis** [comment]
Documenting some pitfalls that will fail your faucet payment, but isn't a bug

- lnd will set the flag `sync_to_graph` to `false` if the hasn't been a new block for quite some time. Mine a few new blocks or use the auto mining script to fix that issue.
- lnd will quickly give up on a channel if a payment failed, ensure your are resetting the mission control, before retrying payments.

**Comment by klochowicz** [comment]
I'm closing this, as it works on my machine. If it fails for anyone else, please re-open.
