### ISSUE TITLE
Allow paying on-chain through faucet

### ISSUE THREAD

**Issue by Restioson** [get10101/10101#1396]

**Comment by Restioson** [comment]
Blocked on #1289

**Comment by holzeis** [comment]
is this really needed? why not use the web interface at http://localhost:8000/faucet ?

**Comment by bonomat** [comment]
Deemed not needed at the moment. We can't use on-chain funds at the moment and hence won't need to fund the wallet.

**Comment by Restioson** [comment]
> why not use the web interface at http://localhost:8000/faucet ?

You absolutely can do that - I just added this so that we could keep track of feature parity between on & off chain

> Deemed not needed at the moment. We can't use on-chain funds at the moment and hence won't need to fund the wallet.

Fair enough!
