### ISSUE TITLE
Rollover failed, position stuck

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#1401]
**Describe the bug**
On Friday a position I opened on version 1.2.6 started a rollover after updating to version 1.3.0. The rollover failed and all further attempts to close the position failed.

**Expected behavior**
Rollover should work. Closing a position after failing to roll over should also be possible.

**Smartphone (please complete the following information):**

- Device: iPhone SE
- OS: iOS
- Version: 16.6.1

**Logs**

Shared privately.

**Comment by holzeis** [comment]
Judging from the coordinator (and the apps) logs, it looks like a rollover has been proposed but never finished (Last message sent / received was `ChannelRenewConfirm`), thus your position remains in state rollover, which prevents you from closing your position. But the `ChannelRenewFinalize` never got sent.

```
{"timestamp":"2023-09-29T17:12:02.475755943Z","level":"INFO","fields":{"message":"Sending message","to":"020f0f44a72fe30cad2a280cfd1802b087eab258db1abc418478fb7e7ab1b000e7","kind":"ChannelRenewConfirm"},"target":"coordinator::node"}
{"timestamp":"2023-09-29T17:12:02.34837494Z","level":"INFO","fields":{"message":"Processing message","from":"020f0f44a72fe30cad2a280cfd1802b087eab258db1abc418478fb7e7ab1b000e7","kind":"ChannelRenewAccept"},"target":"coordinator::node"}
{"timestamp":"2023-09-29T17:12:00.995688954Z","level":"INFO","fields":{"message":"Sending message: Rollover","trader_id":"020f0f44a72fe30cad2a280cfd1802b087eab258db1abc418478fb7e7ab1b000e7"},"target":"coordinator::message"}
{"timestamp":"2023-09-29T17:12:00.99536426Z","level":"DEBUG","fields":{"message":"Proposing to rollover users position","trader_id":"020f0f44a72fe30cad2a280cfd1802b087eab258db1abc418478fb7e7ab1b000e7","position_id":164},"target":"coordinator::node::rollover"}
```

I guess this bug is related to this open ticket https://github.com/get10101/10101/issues/1322.

**Comment by holzeis** [comment]
potentially also related to https://github.com/get10101/10101/issues/1238

**Comment by holzeis** [comment]
It seems the dlc channel is stuck in an intermediate state.

```
{"timestamp":"2023-09-29T22:59:17.83819589Z","level":"ERROR","fields":{"message":"Failed to execute trade. Error: Invalid state: Can only close subchannel that are established or settled","trader_id":"020f0f44a72fe30cad2a280cfd1802b087eab258db1abc418478fb7e7ab1b000e7","order_id":"99f61ea4-b1c7-49b7-8aaf-b784b2c05c1d"},"target":"coordinator::node","span":{"name":"post_trade"},"spans":[{"name":"post_trade"}]}
```
