### ISSUE TITLE
Include DLC channel state in `/api/admin/dlc_channels` endpoint

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#1404]
The DLC channel state is useful information after the introduction of the rollover protocol and with the advent of position resizing.

Whilst we work on this we could also:

- Make this information available through the _app_'s UI (together with subchannel state), since it can help with debugging problems between coordinator and app.
- Rename the endpoint to `/api/admin/subchannels`[^1] since the endpoint actually informs about the subchannel state more generally.

[^1]: We could also take this as an opportunity to consistently use kebab-case instead of snake_case for endpoints. I introduced it at first and I think it is non-standard.

**Comment by bonomat** [comment]
I'm confused :D 

There is already a `state` : 

```
{
  "channel_id": "78afbea629ceee96391300b52f34758e641e386e4adae0ad4146d2d1de36b17a",
  "dlc_channel_id": "07fed026210c4d4458d78fc697a10b0f2eddbeddd293f210f0a3d1e91c78594a",
  "counter_party": "023e7ebafc5d353b0916b5e447aaefd2464dd485e09aba5ba3e6f4d72612b808ad",
  "update_idx": 281474976710655,
  "state": "Signed",
  "fee_rate_per_vb": 9,
  "fund_value_satoshis": 200000,
  "is_offer": true,
  "user_email": "test@test.com",
  "user_registration_timestamp": "2023-10-01T09:05:17.379078Z"
}
```

**Comment by luckysori** [comment]
> I'm confused :D 
> 
> 
> 
> There is already a `state` : 
> 
> 
> 
> ```
> 
> {
> 
>   "channel_id": "78afbea629ceee96391300b52f34758e641e386e4adae0ad4146d2d1de36b17a",
> 
>   "dlc_channel_id": "07fed026210c4d4458d78fc697a10b0f2eddbeddd293f210f0a3d1e91c78594a",
> 
>   "counter_party": "023e7ebafc5d353b0916b5e447aaefd2464dd485e09aba5ba3e6f4d72612b808ad",
> 
>   "update_idx": 281474976710655,
> 
>   "state": "Signed",
> 
>   "fee_rate_per_vb": 9,
> 
>   "fund_value_satoshis": 200000,
> 
>   "is_offer": true,
> 
>   "user_email": "test@test.com",
> 
>   "user_registration_timestamp": "2023-10-01T09:05:17.379078Z"
> 
> }
> 
> ```

That's the _subchannel_ state.

**Comment by holzeis** [comment]
We need that in the context of https://github.com/get10101/10101/issues/1401 where the renew protocol used for rollover stopped in an intermediate state. This protocol is not executed on the subchannel but the dlc channel. (Terminology is a bit confusing here though 🙈)
