### ISSUE TITLE
Allow re-balancing through an API

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1407]
We need to be able to re-balance our channels. 

Not sure what the best approach is but we will need this in the future.

**Comment by holzeis** [comment]
I suggest we create an invoice with an outbound and an inbound routing hint. Shouldn't be too complicated.

**Comment by bonomat** [comment]
> I suggest we create and pay an invoice with an outbound and an inbound routing hint. Shouldn't be too complicated.

I've implemented it this way but keep getting "no route found" errors when paying the invoice. Are we sure that this is how it should work?

**Comment by bonomat** [comment]
It looks like this is currently not possible as constructing a route to ourselves is not allowed: 

https://github.com/lightningdevkit/rust-lightning/blob/ec928d55b480254f2ce3457a5c219ed115fdf9ef/lightning/src/routing/router.rs#L1498-L1500

**Comment by bonomat** [comment]
Draft can be found here: https://github.com/get10101/10101/compare/feat/rebalance?expand=1

**Comment by bonomat** [comment]
Unassigning myself from this and seeking help from LDK-team
