### ISSUE TITLE
Round contracts amount to 2 numbers after the comma

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1408]
<img width="347" alt="Screenshot 2023-10-02 at 10 45 44" src="https://github.com/get10101/10101/assets/382048/b7be5d7e-3375-4019-a0b4-9fd3a57679d2">

**Comment by bonomat** [comment]
I've found myself always only wanting to change the quantity in USD, so why not let the user only change the quantity and let the margin be calculated. 
Then we can go with round numbers only.

**Comment by luckysori** [comment]
We should also consider only allowing whole contracts. Maybe this is only specific to BTCUSD, but trading fractions of a contract is not that interesting and dealing with floats is annoying.
