### ISSUE TITLE
Allow app user to export all data

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1410]
This could be used to manually back up the app.

Additionally this can be used to recover funds by collaborating with us (10101 devs). Some users might be willing to share this information if they run into a severe bug.

Let's add a "Export user data" to the settings page which allows a user to export all critical data.

---

In the context of #1240, we could implement this as a backup which is either unencrypted or encrypted with a different seed/password, so that it can be shared and used without leaking the app seed.

**Comment by bonomat** [comment]
Please replace with the famous async idea

**Comment by klochowicz** [comment]
I'd like to keep this issue as a stepping stone towards the backup/restore functionality if possible. 

the same codepath can be used both for exporting user data for the purpose of backup and for sharing with devs (with the sensitive content being not backed up then).
