### ISSUE TITLE
Add receiving on chain to floating action button

### ISSUE THREAD

**Issue by Restioson** [get10101/10101#1411]
As discussed in #1296 we should be able to receive on chain through the floating action button.

https://github.com/get10101/10101/assets/224613/035e8a95-0437-4ba2-9bcf-1804f0309d2a

**Comment by holzeis** [comment]
I like how this is solved in zeus. The order is basically reversed. You firstly enter the amount and then see the qr code, you can then switch between unified, lightning and onchain.

**Comment by Restioson** [comment]
Yep, we could do that too!

What format is Zeus using for unified QR codes? https://bitcoinqr.dev ?

**Comment by bonomat** [comment]
I like that, it's definitely simpler and more flexible because you can just swap the qr code instead of going back in the wizard.

**Comment by Restioson** [comment]
Sounds good!
