### ISSUE TITLE
Import exported backup into 10101 app

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#1417]
Only into a *new* install

**Comment by holzeis** [comment]
Not sure whats meant with import, but IMHO we should only support the scenario where the user can restore the app from a backup, and not import a backup into an existing app.

e.g. The user gets a question (before we start the node). Do you want to 1. create a new wallet or 2. restore from a backup. For 1) its the same flow as today and for 2) the user is asked for their seed phrase, etc.

**Comment by klochowicz** [comment]
> Not sure whats meant with import, but IMHO we should only support the scenario where the user can restore the app from a backup, and not import a backup into an existing app.

I'm sorry for being unclear, in my mind this was obvious because it's not technically feasible to even do the "import into an existing app".  I've updated the ticket.

> 
> e.g. The user gets a question (before we start the node). Do you want to 1. create a new wallet or 2. restore from a backup. For 1) its the same flow as today and for 2) the user is asked for their seed phrase, etc.

the flow will be done as an augmentation of  #1079
