### ISSUE TITLE
Our balance row is too small for bigger numbers

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1420]
<img width="331" alt="Screenshot 2023-10-04 at 13 11 16" src="https://github.com/get10101/10101/assets/382048/a68f99dc-fd5d-451f-b505-112bdfd0a720">

**Comment by bonomat** [comment]
We could remove the drop down and just show all balances at all times.

**Comment by bonomat** [comment]
@holzeis 
> I don't want top open the account dropdown because I don't want to see the gradient color!!!!111
