### ISSUE TITLE
on-sync wallet stuck during refresh

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#1431]
**Describe the bug**

During local dev testing, I run into an issue when the wallet refresh would never finish (it just kept spinning).

The logs mentioned that the wallet sync has finished, which leads me to suspect that we've run into a deadlock whilst acquiring the Mutex *after* the log. 

**To Reproduce**

Not easy to reproduce; I struggled to reproduce it. 

**Expected behavior**

** Logs

Unfortunately, no relevant logs; my scroll window was too short. #1388 would have been very helpful for this.

**Comment by holzeis** [comment]
> Unfortunately, no relevant logs; my scroll window was too short. https://github.com/get10101/10101/pull/1388 would have been very helpful for this.

@klochowicz the app logs are stored using flog so you can simply export them using the "Share logs" button in the settings. 

We print the directory when starting the app very early on.

`flutter: 2023-10-06 08:40:52.819  LogLevel.INFO App data will be stored in: /Users/holzeis/Library/Developer/CoreSimulator/Devices/1182E2D1-DA66-4C3C-96AF-720DA15E9BB3/data/Containers/Data/Application/3020C4D7-90F6-4F0E-BF35-B2FB0B9AB630/Documents`

If you hit the "Share logs" button on the simulator you can find your logs here.

`..../Documents/FLogs/flog.txt`

**Comment by bonomat** [comment]
It could be that we don't receive the notification that the sync was done - that way the spinner in the frontend keeps spinning. 
The logic for this is in here: 

https://github.com/get10101/10101/blob/0c1844399718b432f94a24dab59b089c0b132313/mobile/lib/features/wallet/wallet_change_notifier.dart#L43-L50

> Unfortunately, no relevant logs; my scroll window was too short. https://github.com/get10101/10101/pull/1388 would have been very helpful for this.

You can also change the max lines of your terminal.

**Comment by klochowicz** [comment]
> You can also change the max lines of your terminal.

That part is easy, it's the "go-back-in-time" part to get the same logs part is tricky 😅

**Comment by klochowicz** [comment]
> > Unfortunately, no relevant logs; my scroll window was too short. #1388 would have been very helpful for this.
> 
> @klochowicz the app logs are stored using flog so you can simply export them using the "Share logs" button in the settings.

I was running a native build, and the share logs doesn't work there. I had also trouble using that button with Simulator FWIW.
Not to mention that the timing is off in FLogs in regards to coordinator (different time zone)

**Comment by holzeis** [comment]
> I was running a native build, and the share logs doesn't work there. I had also trouble using that button with Simulator FWIW.

The logs are still stored on flog.db. So you should be able to print them one way or another.

> Not to mention that the timing is off in FLogs in regards to coordinator (different time zone)

I think the logs are still useful especially as this bug has nothing to do with the coordinator.

**Comment by bonomat** [comment]
Could not reproduce this.
