### ISSUE TITLE
Optimistic status icon

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1442]
Currently we show the status icon red until we get the first notification from the coordinator. Since we have an initial delay of some seconds, before trying to connect to the coordinator, the status icon is always shown red after opening the app.

I think we can be a bit more optimistic here and assume the coordinator is online and only set it too red if we do not get an `Online` message after a timeout.

Even more so since we anyways have an additional check seeing if the coordinator is reachable.

**Comment by klochowicz** [comment]
I firmly believe the current behaviour is correct. There's no point pretending that we have a connection when we don't; moreover, the user is more likely to trust the status icon if they see it *changing*.

Case in point: when you're about to start a car, but it's not running yet, all the warning signs are on (including "check engine"); they go off when the ECU sends a notification that everything is OK.

**Comment by holzeis** [comment]
Maybe we should rather investigate why the longer timeout is even needed. Maybe we can shorten it again.

**Comment by Restioson** [comment]
Maybe there could be another colour for unknown? Or just display a superimposed question mark. I think there is still a difference between not having checked if everything is ok vs things not being ok

**Comment by klochowicz** [comment]
FWIW: With #1512 this stops becoming an issue; when the status screen appears, it's already green. :-)

**Comment by holzeis** [comment]
Obsolete as status thermostat has been moved to settings
