### ISSUE TITLE
Group fees with transaction

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1457]
We currently depict every fee individually. I propose to group the fees to the actual transaction.

E.g. the first 6 transactions in the below screenshot would end up in the following 3 transactions, with the fees being depicted in the details.

- +840k Payment
- -713.13k Open position (I would also include the reserve here as a separate field in the details)
- +692.82k Close position

![image](https://github.com/get10101/10101/assets/382048/db218fd9-5eb4-41b8-ab68-fff1f4f23999)

**Comment by Restioson** [comment]
Seems thematically related to #1147 ? We could implement some kind of system where we could associate transactions with other transactions. Probably just simple parent-child would suffice, maybe with a fkey in sql too

**Comment by holzeis** [comment]
> Seems thematically related to #1147 ? 

Yeah, but not dependent on it.

**Comment by Restioson** [comment]
Yep, agreed. Though, we could use the same solution for both, for example, if it happens to make the most sense

**Comment by holzeis** [comment]
Closing this ticket in favor of https://github.com/get10101/10101/issues/843 and https://github.com/get10101/10101/issues/1277

**Comment by Restioson** [comment]
Could you explain which parts of each ticket would resolve this issue? This seems to be more of an issue with how the history is shown and less about how the paying of fees is initiated

**Comment by holzeis** [comment]
> Could you explain which parts of each ticket would resolve this issue? This seems to be more of an issue with how the history is shown and less about how the paying of fees is initiated

Once these tickets are resolved, we do not have the payment transaction anymore. The fees have to be depicted on the wallet type item.

See also
