### ISSUE TITLE
Funding transaction is opened on mempool for regtest

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1486]
Regtest Environment should point out to our esplora instance

**Comment by bikraj2** [comment]
more detail on this ?

**Comment by holzeis** [comment]
If you open the funding transaction you will be redirected to mempool, which will not work for regtest.


![image](https://github.com/get10101/10101/assets/382048/830d887d-cbd0-4004-95fd-af23c3654be7)

**Comment by holzeis** [comment]
Fixed on main
