### ISSUE TITLE
Trading Buy: Need labels for quantity / margin

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#15]
Once values are filled in the user does not know what these values stand for.
(And the confirmation screen uses different values, so it's super confusing and one cannot make sense of it.)

**Comment by bonomat** [comment]
I wanted to use this sexy component for input fields a while ago: 

<img width="600" alt="image" src="https://user-images.githubusercontent.com/224613/212608367-92cae641-0959-48ea-89b5-00f0b08c2145.png">

It's already copied in :)

**Comment by 1010Tom** [comment]
This was feedback on the old prototype and is obsolete now.
