### ISSUE TITLE
Pull-down refresh no longer works

### ISSUE THREAD

**Issue by Restioson** [get10101/10101#1529]
**To Reproduce**

1. Create wallet
2. Drag down using the mouse

**Expected behavior**
Spinner appears 

**Smartphone (please complete the following information):**

Desktop simulator

**Additional context**
May be related to #1509

**Comment by holzeis** [comment]
On the latest test app version this is not reproducible.. can you add more details? Is this only happening for you on the simulator? Can you maybe add a video?

**Comment by luckysori** [comment]
@Restioson: can we close this one? It seems to work for everyone else atm.

**Comment by Restioson** [comment]
I can test this again on main
