### ISSUE TITLE
Failing intercepted HTLC backwards although it succeeded?

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1532]
Weird situation is happening locally for me and I can reproduce it:

1. open channel using the faucet
2. (optional) receive payment or do anything to show the channel works
3. collaborative close channel using the app
4. see this log message in the coordinator: 
`
Failing intercepted HTLC backwards intercept_id=faa7438307d2ee8f8fc51e32056f8ff75d435aa0a3428485fc56680cb501722b`

**Comment by holzeis** [comment]
Did you mine some blocks?

**Comment by bonomat** [comment]
Found the issue: 
we are calling this function when we get a close event: 

https://github.com/get10101/10101/blob/9c8924fdde58533fb337991acd0be7e0734b1ea1/crates/ln-dlc-node/src/ln/common_handlers.rs#L243-L245

Nothing happens because the HTLC has been resolved already. I guess we should remove the intercepted HTLC from the list once it is done.
