### ISSUE TITLE
Closing channel does not give you feedback

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1533]
Right when closing a channel, it doesn't give you any feedback. 

When the channel was successfully closed we should show a dialog with the closing tx details, in case of an error, we should inform the user what was wrong (afaik we do this already).

**Comment by holzeis** [comment]
The current behaviour is that on success you will be redirected to the wallet screen on error you'll see a snackbar message.

What more feedback are you thinking of?

**Comment by bonomat** [comment]
Ideally we show the closing tx with a link to mempool

**Comment by holzeis** [comment]
You mean a transaction in the wallet history?

**Comment by bonomat** [comment]
No, I mean a confirmation dialog.

**Comment by holzeis** [comment]
As far as I can remember, fetching the commitment transaction is not that easy.

See also 

- https://github.com/get10101/10101/issues/1105
- https://github.com/orgs/lightningdevkit/discussions/2407
- https://github.com/orgs/lightningdevkit/discussions/2405

**Comment by bonomat** [comment]
Looks like LDK 117 will give us more details: https://github.com/lightningdevkit/rust-lightning/pull/2511

**Comment by holzeis** [comment]
Actually we already do show the commitment transaction in the wallet history. It's the onchain payment after the channel is closed. It's just not labeled as such.

**Comment by holzeis** [comment]
Thinking about it, I guess it's easier on the app side as we only have a single channel there. So we can simply assume that the spendable output event belongs to that channel.

**Comment by bonomat** [comment]
I know, but we should give the user _some_ feedback after clicking the button. Right now he doesn't get anything.

**Comment by holzeis** [comment]
Let's wait for ldk 117 for that.
