### ISSUE TITLE
Add max amount button to send out on-chain funds

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1538]
A max button that sets the amount to the maximum the user can send out.

**Comment by bonomat** [comment]
Afaik if you put in `0` it will send out max.

**Comment by holzeis** [comment]
🙈

![image](https://github.com/get10101/10101/assets/382048/379f5989-2ac4-458f-8210-b219811cde1a)

**Comment by bonomat** [comment]
The logic is implemented though 😅

https://github.com/get10101/10101/blob/68958755e16f8cb3eec4a08de507ff2e4059b74c/crates/ln-dlc-node/src/ldk_node_wallet.rs#L199-L210

**Comment by bonomat** [comment]
Although, I believe it is flawed, it should be `None` or `0`
