### ISSUE TITLE
Coordinator's channel announcement chain hash does not match genesis hash

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#1561]
Since we upgraded to `rust-lightning:0.0.116` we started seeing this message in the app logs:

```
lightning::ln::peer_handler: Error handling message from 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156; ignoring: Channel announcement chain hash does not match genesis hash 
```

The error message seems to suggest that the production coordinator sent a channel announcement about a _non-mainnet_ channel.

The log was added with the recent upgrade, so perhaps it just uncovered a problem that was already happening before.

**Comment by luckysori** [comment]
Waiting to see if we see this anymore after the next release.

**Comment by holzeis** [comment]
I guess we may be able to fix that issue by implementing a UTXO lookup on the P2PGossipSync https://docs.rs/lightning/latest/lightning/routing/gossip/struct.P2PGossipSync.html#method.new

> UTXO lookup is used to make sure announced channels exist on-chain, channel data is correct, and the announcement is signed with channel owners’ keys.

or changing to RapidGossipSync

**Comment by holzeis** [comment]
> The error message seems to suggest that the production coordinator sent a channel announcement about a non-mainnet channel.

I don't think its the coordinators channel, but just a gossiped channel that is not on chain.

**Comment by holzeis** [comment]
Closing this ticket as this should be resolved with switching to rgs. https://github.com/get10101/10101/pull/1631

Reopen if the log message is shown again.
