### ISSUE TITLE
Couldn't find channel for update

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1567]
Our logs are filled with messages about message of channels that can't be found. It looks like we can safely ignore those messages, but it would be great if we could get to the source of it and verify that those message are indeed harmless and potentially get rid of them one way or the other. 

```
[D] TIME: 2023-11-08T12:53:22.529282Z r: lightning::ln::peer_handler: Error handling message from 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156; ignoring: Couldn't find channel for update 
```

**Comment by luckysori** [comment]
For context: https://github.com/lightningdevkit/rust-lightning/issues/2471.
