### ISSUE TITLE
Add erase wallet button

### ISSUE THREAD

**Issue by SXBT69** [get10101/10101#1594]
**At the moment, the only way to create a fresh wallet or to switch between several wallets is to uninstall/reinstall the app.**

**An erase wallet button with a proper disclaimer in the settings could be handy**

**An alternative would be having several wallets that you can switch in the settings**

**Phoenix got something like this in the settings, for reference**

**Comment by SXBT69** [comment]
This could definitely go in the "danger zone" of the settings

**Comment by holzeis** [comment]
> **At the moment, the only way to create a fresh wallet or to switch between several wallets is to uninstall/reinstall the app.**
> 
> 
> **An erase wallet button with a proper disclaimer in the settings could be handy**

Why would you want to create a fresh wallet? IMHO reinstalling seems to be a good enough solution.

> 
> **An alternative would be having several wallets that you can switch in the settings**
> 

What do you mean with several wallets? Several installations of the 10101 wallet? I don't see why you want that 🤔

**Comment by SXBT69** [comment]
> Why would you want to create a fresh wallet? IMHO reinstalling seems to be a good enough solution.

You might want to have a fresh start and create a new wallet from scratch

> What do you mean with several wallets? Several installations of the 10101 wallet? I don't see why you'd want that 🤔

No I was meaning, several "profiles" that you can switch from and to.
