### ISSUE TITLE
Better starting point & flow for the `Stable Sats` task

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#16]
We had trouble in two user interviews already, where it was unclear what is the exact starting point of the user case.

In my opinion there are two things needed:

1. Be clear that the task is about moving funds from the trading to the stable sats wallet.
2. Wire "Receive" buttons to the "not part of your task button
3. Make sure that there are no "Deposit" buttons in the task. The deposit buttons should only be shown if 
    1. In case we want to change this constraint we have to clear that the scenario is about moving funds from the trading wallet into the stable sats wallet!

**Comment by 1010Tom** [comment]
Stable sats feature has been descoped for the MVP.
