### ISSUE TITLE
Upgrade ldk to 0.0.117

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1604]
https://github.com/lightningdevkit/rust-lightning/releases/tag/v0.0.117

**Comment by holzeis** [comment]
https://github.com/p2pderivatives/rust-lightning/pull/15

**Comment by luckysori** [comment]
> @luckysori Can we close this now that ldk 117 has landed on 10101 or do you want to keep it open until it gets merged in our rust-lightning fork in p2pderivatives?

Probably should keep it open, but we can move it out of the iteration.
