### ISSUE TITLE
Opening open order drawer showed error

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1633]
I wanted to open a new position today and was presented with this error. 

![image](https://github.com/get10101/10101/assets/224613/138c3302-00c2-4ba4-89ea-9a73fcd39369)

After restarting the app it was gone but we might want to look into this because this endpoint shouldn't be called here.

**Comment by holzeis** [comment]
When did you try? Maybe you've unlucky and tried while I was releasing 1.6.2.

**Comment by holzeis** [comment]
![Screenshot 2023-11-24 at 13 26 10](https://github.com/get10101/10101/assets/382048/868c8247-9fd8-404d-b7b5-d5bcda8dbbd2)

If this is UTC+1 then you tried to open a position when the coordinator was down.

**Comment by bonomat** [comment]
This was GMT-3 aka timezone in Chile.
