### ISSUE TITLE
Can't create an opposite order with the exact quantity of my current position

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1660]
Having a short position of 300 contracts should allow me to go at least 300 long, as this is the order that would get created when using the close position button. But using the order drawer for that it shows me that I do not have a sufficient balance to do that.

![Screenshot 2023-11-29 at 16 20 12](https://github.com/get10101/10101/assets/382048/904d8341-5986-4fed-a561-75109c7fb6d8)

**Comment by luckysori** [comment]
> Oh, yea, I guess the calculations here are now completely off.

Should not be _completely_ off. The usable balance was updated correctly as can be seen in the screenshot above: it takes into account your margin if you're going in the opposite direction.

But there's clearly still a bug!
