### ISSUE TITLE
Replace USDP tab on home screen with a swap drawer opened from the bottom

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1676]
The screens do not 100% reflect the intended design, but is close enough to get an idea on how it should look like.

Scope:

 - Add swap button to home screen
 - Upon clicking the swap button open a drawer from the bottom showing the swap option
 - Both Lightning and USD-P should be editable
 - The selection should allow for selecting lighting and usdp, if one changes the other should be changed accordingly
 - If the amount in usdp is changed it should change the lightning amount and vice versa
 - The trading amount is the best ask price from the orderbook
 - The summary should not include an EST time
 - Upon confirming the swap a loading screen should be shown spinning until the swap was successful or failed.
 - success or failed screen should also be dispayed as drawer from the bottom.

![Screenshot 2023-12-04 at 14 01 53](https://github.com/get10101/10101/assets/382048/c64922e2-1e1d-476f-b8c9-0bf5a3f698e8)

**Comment by SXBT69** [comment]
@Restioson check this out : 


![image](https://github.com/get10101/10101/assets/137571657/c32b5539-9b13-4e9d-81ad-891502940952)
![image](https://github.com/get10101/10101/assets/137571657/885b0cf7-de75-48c9-95b2-a5a543a99309)

the correct way to display it is in the "sending" flow

D

https://figma.com/file/5BgcmpxFA7AHN2bs8Cd8wC/10101-Mobile-app-design?type=design&mode=design

**Comment by Restioson** [comment]
The thing that's confusing me is this line:

> Upon clicking the swap button open a drawer from the bottom showing the swap option

Does that mean that we want the entire swap screen in a drawer?

**Comment by SXBT69** [comment]
It was not designed like this on figma, but I think that's not a bad idea since there is a lot of free space on the swap screen...
