### ISSUE TITLE
Add fee estimation to sending a lightning invoice

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1682]
Scope

- Add a probing api to lndlc crate for paying an invoice. Should return a route if possible.

![Screenshot 2023-12-04 at 15 53 57](https://github.com/get10101/10101/assets/382048/ddefe703-2ee9-445d-97ee-cca69a71c04d)

Either in this ticket or a follow up

- Should include an estimate on the lightning transaction fees
- If usdp is selected the fees should additionally include the order matching fees.

**Comment by bonomat** [comment]
> If usdp is selected the fees should additionally include the order matching fees.

if usdp are sent to another 10101 wallet and received as such we should wave said fees and only account for routing fee.
