### ISSUE TITLE
Failed to upload backup: too large

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1719]
just noticed locally: 

> flutter: [D] TIME: 2023-12-11T07:39:51.686165Z r: Response status code 413 Payload Too Large
> flutter: [E] TIME: 2023-12-11T07:39:51.686640Z r: Failed to upload backup. Failed to buffer the request body: length limit exceeded

**Comment by bonomat** [comment]
Happens continuesly times now

**Comment by holzeis** [comment]
I think the limit is currently set to 20mb? Do you know what file did get so large?

**Comment by bonomat** [comment]
Needs to be investigated more. The logs are gone now so I don't know which file was too big.

**Comment by holzeis** [comment]
related to https://github.com/get10101/10101/issues/1637

**Comment by holzeis** [comment]
related to https://github.com/get10101/10101/issues/1737

**Comment by luckysori** [comment]
The `app_can_be_restored_from_a_backup` e2e test fails with this error now.

I think this must have to do with https://github.com/get10101/10101/pull/1817, since we potentially added lots of CET adaptor signatures to the app's database.

**Comment by holzeis** [comment]
> The `app_can_be_restored_from_a_backup` e2e test fails with this error now.
> 
> 
> 
> I think this must have to do with https://github.com/get10101/10101/pull/1817, since we potentially added lots of CET adaptor signatures to the app's database. If that's the problem, how should we fix it, @holzeis?

Hmm, we might be able to tell SQLite to skip a specific table for backup. We don't need to backup the `last_outbound_dlc_messages` table.

**Comment by holzeis** [comment]
> Hmm, we might be able to tell SQLite to skip a specific table for backup. We don't need to backup the last_outbound_dlc_messages table.

It looks like there is no way telling sqlite to backup only some tables, but its possible to backup only a specific database. So we could add a second database for the non-critical large data, which does not get backed up.

**Comment by holzeis** [comment]
@luckysori reopening that issue, as I don't think you meant to close it?

**Comment by luckysori** [comment]
> @luckysori reopening that issue, as I don't think you meant to close it?

I suppose the fix that we introduced might be enough if a backup chunk never exceeds 50MB (ignoring the fact that the proxy limit is set to 20 MB).

But a 50MB chunk is already massive and we definitely want to bring that down.

**Comment by bonomat** [comment]
> @luckysori reopening that issue, as I don't think you meant to close it?

He actually did fix it here: 2dccdd856f95f9eab74ef9a9af5c82fbde4e209f

**Comment by holzeis** [comment]
Oh nice, I've missed that 🙂
