### ISSUE TITLE
Receive screen is not designed according to figma

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1735]
The toggle in the middle currently shows the invoice amounts, however it should show the current balance and the amount should be shown in an extra row. 

See below screenshot how it should look like. 

<img width="323" alt="image" src="https://github.com/get10101/10101/assets/224613/1c207286-4424-46d3-b04a-bcd7bf3c8a29">

**Comment by SXBT69** [comment]
Yes, correct.
Edit should give the ability to enter the amount in sats or usdp
amount row could be clickable to change between both
