### ISSUE TITLE
Lightning / On-chain switch is jumping on the receive screen

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1736]
Although the whole widget stays the same size the inner options change width when selected and unselected.

![image](https://github.com/get10101/10101/assets/382048/f543dabd-6337-4c0c-8134-c8bc2e8369cf)

![image](https://github.com/get10101/10101/assets/382048/7cac174c-1ea0-44e6-bd25-89cbf6985bff)

**Comment by Restioson** [comment]
This is most likely due to the icon only appearing when it is selected
