### ISSUE TITLE
USDp rounding numbers

### ISSUE THREAD

**Issue by SXBT69** [get10101/10101#1765]
When paying an invoice, the USD value **of the invoice** when switching to USDP balance is **rounded up**, thus it can be confusing

[Example here](https://rumble.com/v41kdmx-pleb-using-usdp-to-pay-a-chivo-lightning-invoice.html?mref=1mh890&mc=5ek6u)

I think this could be fixed by displaying the digits after the decimal point when using dollar value invoice amount.
<img width="639" alt="image" src="https://github.com/get10101/10101/assets/137571657/bf2fa7bb-949a-45e7-8270-62ca425a70d5">

**Comment by bonomat** [comment]
> I think this could be fixed by displaying the digits after the decimal point when using dollar value invoice amount.
Not sure if this will fix it. 

I think we should show the in big bold letters the sats amount you are paying and in smaller letters the estimated USD amount.

**Comment by bonomat** [comment]
This will get better once we have fractional dollar amounts which will be introduced with #1729
