### ISSUE TITLE
App crashes at startup: Commitment txids are unique outside of fuzzing, where hashes can collide

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1772]
Happened on our test-environment after funding the app and opening a positions which got stuck in `Open`. Eventually the app crashed and is not able to startup again.

Judging from the apple crash report it looks like to be a panic `channelmonitors::update_monitor` function.

![image](https://github.com/get10101/10101/assets/382048/90ac323c-60ab-4a25-9423-bd3407809c06)

**Comment by holzeis** [comment]
I started the app with debug from my mac and found the following panic

```
flutter: [E] TIME: 2023-12-21T14:44:30.111838Z r: Aborting after panic in task info: panicked at /Users/holzeis/.cargo/git/checkouts/rust-lightning-bee3233422fa4387/121bc32/lightning/src/chain/channelmonitor.rs:2380:17:
Commitment txids are unique outside of fuzzing, where hashes can collide
```

**Comment by luckysori** [comment]
I was able to reproduce this with this diff, although it's not consistent:

```diff
1 file changed, 3 insertions(+)
mobile/native/src/ln_dlc/node.rs | 3 +++

modified   mobile/native/src/ln_dlc/node.rs
@@ -236,6 +236,9 @@ impl Node {
                                 .context("Could not set order to failed")?;
                             }
                         }
+
+                        std::thread::sleep(std::time::Duration::from_secs(5));
+                        panic!();
                     }
                     SubChannelMessage::CloseOffer(offer) => {
                         let channel_id = offer.channel_id;
```

**Comment by holzeis** [comment]
> I was able to reproduce this with this diff, although it's not consistent:
> 
> 
> 
> ```diff
> 
> 1 file changed, 3 insertions(+)
> 
> mobile/native/src/ln_dlc/node.rs | 3 +++
> 
> 
> 
> modified   mobile/native/src/ln_dlc/node.rs
> 
> @@ -236,6 +236,9 @@ impl Node {
> 
>                                  .context("Could not set order to failed")?;
> 
>                              }
> 
>                          }
> 
> +
> 
> +                        std::thread::sleep(std::time::Duration::from_secs(5));
> 
> +                        panic!();
> 
>                      }
> 
>                      SubChannelMessage::CloseOffer(offer) => {
> 
>                          let channel_id = offer.channel_id;
> 
> ```

Ups that looks like test code 🙈. Hopefully that wasn't me 😬

**Comment by luckysori** [comment]
> Ups that looks like test code 🙈. Hopefully that wasn't me 😬

Not sure I get you.

What _I_ did was introduce that diff in order to reproduce the problem described above.

**Comment by holzeis** [comment]
> > Ups that looks like test code 🙈. Hopefully that wasn't me 😬
> 
> 
> 
> Not sure I get you.
> 
> 
> 
> What _I_ did was introduce that diff in order to reproduce the problem described above.

Oh, got ya I thought this was a commit on main 😅

**Comment by luckysori** [comment]
Btw, since we are moving away from Lightning for the time being, we came up with this idea to filter out incoming subchannel-related messages to unblock those who are running into this bug.

**Comment by holzeis** [comment]
> Btw, since we are moving away from Lightning for the time being, we came up with this idea to filter out incoming subchannel-related messages to unblock those who are running into this bug.

@luckysori We already doing that. Can we close that ticket?

**Comment by luckysori** [comment]
Yes!
