### ISSUE TITLE
Pending receive / success handling after "receive payment" flow

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#180]
Follow up of #71  and #178

When receiving we cannot really refresh the wallet besides actually picking up the payment in the backend and then triggering a refresh of balance and transaction history. 

One thing that we could add is some form of `Success` screen, that tells the user that the payment will appear once it was sent and picked up by the Lightning node. We have that in the [Figma prototype](https://www.figma.com/file/Sr3SfZ46sZstKjSwftmTtc/10101-v1-(incl-bitcoin.design)?node-id=5652%3A92292&t=55DjyHsH66ykrAcQ-1). 

I think this is not optimal, because that success diakog might just come out of nowhere if the user navigates somewhere else and only does the payment later. Instead I propose this more guided UX:

Once the user hits `Done` in the "receive paymnet" flow we display the`SubmissionStatusDialog` in `Pending` state; and transition to `Success` state once we detect the payment coming in (which will show the payment in the wallet history and reflect the balance change). The user can just close that dialog and it will be gone (e.g. if the user does not want to receive anymore).
Note: This means we would have to update the state of the dialog by the payment. With the current implementation of the dialog this is not easily possible, so we would have to adapt that.

**Comment by holzeis** [comment]
In zeus, if you stay on the invoice and you receive it you will be shown that this invoice has been paid (middle screenshot), if you go back to the wallet dashboard, you will get no notification, but can see the payment in your transaction history (see third screenshot).

![Screenshot 2023-03-01 at 09 49 48](https://user-images.githubusercontent.com/382048/222089667-11ffdc05-5e9c-4bc1-b757-22ffc7367791.png)

The same UX in Breez. I would go for a similar UX. So, I would simply return to the wallet dashboard on done and list the transaction in the history if received. In case of a pending transaction, I guess I would show it still in the history, but remove it once the invoice expired (if not paid). (fyi: Breez is not showing any pending payment)
