### ISSUE TITLE
Can't close a position/dlc-channel which was not yet confirmed

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1802]
How to reproduce: 

1. Open position (i.e. implicitely open a dlc-channel)
2. Try to close immediately
3. Get following error
```
flutter: [ERROR] TIME: 2024-01-05T07:50:30.791945Z r: Failed to process incoming DLC message: Failed to handle ChannelSettleConfirm message from 02dd6abec97f9a748bf76ad502b004ce05d1b2d1f43a9e76bd7d85e767ffb022c9: Invalid state: Invalid state Contract { state: "signed" } expected Confirmed. from: 02dd6abec97f9a748bf76ad502b004ce05d1b2d1f43a9e76bd7d85e767ffb022c9,kind: ChannelSettleConfirm
```

**Comment by bonomat** [comment]
@luckysori : what do you think? It's probably not a bug, but I think we should still be able to do this.

**Comment by luckysori** [comment]
Yeah, I mentioned this last time we talked: I think the node needs to run the `periodic_check` at least once to mark the contract as confirmed (even if we set `NB_CONFIRMATIONS` to 0).

Keep in mind that this only happens the very first time you open the DLC channel. In any case, to be safe I think the app and coordinator should only let you start doing things with the DLC channel once they know that the contract has been confirmed. We could just check this before any messages are sent. With 0-conf this will be fast (we could even force the periodic check).

And if we want 1-conf etc we should display this information in the UI. I talked to Tibo about the possibility of opening the DLC channel without a DLC output to prepare the channel ahead of time, but I don't think he's into the idea. So we just need to come up with good UX for that first trade.

**Comment by bonomat** [comment]
@luckysori : please document and close if not needed/replace with a new one.

**Comment by luckysori** [comment]
With #1836, we require 1 confirmation on the DLC channel to trade, so it is more likely that the app user will run into this situation.

But this is normal behavior, so the only thing we want to do is to improve the UX by ensuring that the user knows that they will have to wait for a confirmation before they can start trading. As such, this will be covered when we have a clear [on-boarding flow](https://github.com/get10101/10101/issues/1797) and separate the channel creation from the creation of the first position.
