### ISSUE TITLE
Create an ADR for the order + trade lifecycle within the systems

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#181]
This ticket adds to https://github.com/get10101/meta/discussions/131

We should capture the lifecycle and flow of the order and the order execution in an ADR. 

---

After a discussion with @bonomat about the flow "from order to position" we agreed on:

- When an order is matched by the orderbook *both* trading parties (clients) get notified about the match by the orderbook
- Both clients then send an execution request to the coordinator
     - The order is what the parties agreed on, the order is what is used in the execution request.
     - The coordinator comes up with the `ContractInput` based on the order and returns the `ContractInput` to the client as response to the request; this is to be used by the client to trigger `propose_dlc_channel` on either client side
- Once the coordinator has both (matching) execution requests, i.e. both `propose_dlc_channel` recorded, the coordinator accepts both.
    - Timeout on coordinator: If either party does not execute the other party is notified with execution failure and the coordinator removes the pending execution request. 

Note: In the context of the coordinator we don't have to use "Maker" and "Taker", because for the coordinator it should not matter; it's just two trading parties / clients. But since we used these labels in other sequence diagrams I am re-using them here.

```mermaid
sequenceDiagram

participant m as Maker
participant o as Orderbook
participant c as Coordinator
participant t as Taker

o ->> m: matched {order_maker} with {order_taker, taker_pubkey}
o ->> t:  matched {order_taker} with {order_maker, maker_pubkey}
t ->> c: request execution: {mine: order_taker, counterparty: order_maker, pubkey_taker, pubkey_maker}
c ->> t: `ContractInfo` {contract_info_taker}
c ->> c: record pending execution: {party_a: order_taker, party_b: order_maker, pubkey_taker, pubkey_maker}: request_pending
m ->> c: request execution: {mine: order_maker, counterparty: order_taker, pubkey_taker, pubkey_maker}
c ->> m: `ContractInfo`  {contract_info_maker}
c ->> c: match pending execution: {party_a: order_taker, party_b: order_maker, pubkey_taker, pubkey_maker}: request_completed
t ->> c: propose_dlc_channel(contract_info_taker)
c ->> c: update pending execution: {party_a: order_taker, party_b: order_maker, pubkey_taker, pubkey_maker}: execution_pending
m ->> c: propose_dlc_channel(contract_info_maker)
c ->> c: update pending execution: {party_a: order_taker, party_b: order_maker, pubkey_taker, pubkey_maker}: in_execution
c ->> t: accept_sub_channel(pubkey_taker)
c->> m: accept_sub_channel(pubkey_maker)
c->> c: update pending execution: {party_a: order_taker, party_b: order_maker, pubkey_taker, pubkey_maker}: completed
```

Note: The order in which maker/taker request / messages arrive on the coordinator should not matter, the maker can go first or the taker can go first.

Note: The diagram is simplified and only depicts the success scenario for now.

**Comment by luckysori** [comment]
Maybe I'm just stating the obvious, but I want to remind ourselves that the protocol does not guarantee that the coordinator will be able to establish a DLC channel with both maker and taker. As such, the coordinator is taking on risk every time they accept the first of the 2 DLC channels per trade.

**Comment by da-kami** [comment]
> Maybe I'm just stating the obvious, but I want to remind ourselves that the protocol does not guarantee that the coordinator will be able to establish a DLC channel with both maker and taker. As such, the coordinator is taking on risk every time they accept the first of the 2 DLC channels per trade.

Yes. I don't think there is a way around this in a non-custodial setup where we have a coordinator. 
Given that both parties already put *some* commitment in by triggering `propose_dlc_channel` that's a risk we are willing to take? 

CC @bonomat

**Comment by bonomat** [comment]
> Yes. I don't think there is a way around this in a non-custodial setup where we have a coordinator. I don't see a way to enforce execution.

Me neither. As long as we can't connect the two DLCs with each other, one has always to go before the order.

> To be clear: I don't think there is an attack scenario here, because a party that would want to "hurt" the coordinator would have to trade with itself and then back out of one side all the time. This requires stakes; i.e. there is no way to attack without actually locking up funds.

**Comment by holzeis** [comment]
In the context of #220 I thought about the edge cases on the sequence diagram above and tried to extend it. The main assumption here is that we will only ever have one open position with the trader, and in case a position is already existing we will have to close the existing dlc_channel, before we can open a new. In case the executed order is "reversed" (meaning that it is the exact opposite of the open position) we only have to close the dlc_channel and are done.

I have added more context here https://github.com/get10101/10101/issues/220#issuecomment-1458349496

```mermaid
sequenceDiagram

participant m as Maker
participant o as Orderbook
participant c as Coordinator
participant t as Taker


o ->> m: matched {order_maker} with {order_taker, taker_pubkey}
o ->> t:  matched {order_taker} with {order_maker, maker_pubkey}
t ->> c: request execution: {mine: order_taker, counterparty: order_maker, pubkey_taker, pubkey_maker}

alt "reversed" position exists AND position.quantity == order.quantity
    Note over c,t: If an order is exectued with the exact same quantity as the existing "reversed" position, <br/> the dlc channel can be closed.
    c ->> t: offer_subchannel_close
    t ->> c: accept_subchannel_close_offer
else
    opt position exists
        Note over c,t: If a position exists but it's not a reverse of the order, respectively a different quantity we need to <br/> close the extend or reduce the dlc channel. For that we will have to initially close the dlc channel and <br/>then reopen again.
        c->> t: offer_subchannel_close
        t ->> c: accept_subchannel_close_offer
    end
    c ->> t: `ContractInfo` {contract_info_taker}
    c ->> c: record pending execution: {party_a: order_taker, party_b: order_maker, pubkey_taker, pubkey_maker}: request_pending
    m ->> c: request execution: {mine: order_maker, counterparty: order_taker, pubkey_taker, pubkey_maker}
    c ->> m: `ContractInfo`  {contract_info_maker}
    c ->> c: match pending execution: {party_a: order_taker, party_b: order_maker, pubkey_taker, pubkey_maker}: request_completed
    t ->> c: propose_dlc_channel(contract_info_taker)
    c ->> c: update pending execution: {party_a: order_taker, party_b: order_maker, pubkey_taker, pubkey_maker}: execution_pending
    m ->> c: propose_dlc_channel(contract_info_maker)
    c ->> c: update pending execution: {party_a: order_taker, party_b: order_maker, pubkey_taker, pubkey_maker}: in_execution
    c ->> t: accept_sub_channel(pubkey_taker)
    c->> m: accept_sub_channel(pubkey_maker)
    c->> c: update pending execution: {party_a: order_taker, party_b: order_maker, pubkey_taker, pubkey_maker}: completed
end
```

**Comment by da-kami** [comment]
> Also, note that I've drawn the flow with the coordinator to propose the dlc channel close, as I don't see any benefit of instructing the trader to do so, but happy to change if you see it differently.

I think this is clear already, but I'm still pointing it out for completion: "Closing a position" is filling an order (i.e. executing a trade) between two trading parties and the coordinator. 
For the MVP the maker that we open and close the position with will be the same, but in the future the order to "close" a position will likely be filled with a different maker.
The trade that is being executed for the taker still has a counterpart (the "maker"), and the coordinator has to ensure that both parties requested to act before it can be executed. I think for the MVP we can assume that the maker will be the same.

At the moment there is an assumption, that the coordinator has *some* time to accept an action after the client that requested trade execution first triggers that action. 
At the point of requesting to execute a trade, the coordinator may not be in the position to execute it yet because the trade counterpart has not requested execution yet.

Your proposal of letting the coordinator trigger the actual execution by calling `offer_subchannel_close` might be a better approach overall, because only the coordinator knows when the execution is ready.

I think both approaches are possible, but I think we should not have different ones for `create_channel` and `close_channel`. I think this should be the same flow - but I'm happy to evaluate if it's better to let the coordinator trigger it.

**Comment by bonomat** [comment]
The problem with the `coordinator` proposing and the `taker` accepting is that it is riskier for the `coordinator`. 
- the `taker` could wait for a long time or just let it time out
- the _counterpary_ of the trade could already move on with the trade leaving the `coordinator` with a onesided position. 

That's why the `coordinator` should always have the last word.

Imho the flow (without the details) looks like this: 

```mermaid

sequenceDiagram

participant m as Maker
participant c as Coordinator
participant o as Orderbook
participant t as Taker

m ->> o: create limit order


t ->> o: market order
o -->> o: match maker and taker

par Trader to Coordinator
o-->>t: Order details
t ->>c: Propose DLC channel open
c -->>t: Accept 
and Maker to Coordinator
o-->>m: Order details
m ->>c: Propose DLC channel open
c -->>m: Accept 
end


Note over m,t: ...time flies when making money....

m ->> o: create limit order


t ->> o: market order

o -->> o: match maker and taker

par Trader to Coordinator
o-->>t: Order details
t ->>c: Propose DLC channel close
c -->>t: Accept 
and Maker to Coordinator
o-->>m: Order details
m ->>c: Propose DLC channel close
c -->>m: Accept 
end

```

**Comment by holzeis** [comment]
I guess the second `market order` submitted by the taker is a "reversed" order meaning that its closing the first `market order`?

It would be great if we could separate the different scenarios on this diagram, as it could also happen, that the trader wants to open an additional e.g. long position, which I guess will "simply extend" (or update) the one position we already have? or she might as well try to partially close a position, in which case we would "simply reduce" the existing position. I know its not scope for the MVP, but knowing how it would look like beyond MVP will help implementing the MVP scope.

**Comment by da-kami** [comment]
> It would be great if we could separate the different scenarios on this diagram, as it could also happen, that the trader wants to open an additional e.g. long position, which I guess will "simply extend" (or update) the one position we already have? or she might as well try to partially close a position, in which case we would "simply reduce" the existing position. I know its not scope for the MVP, but knowing how it would look like beyond MVP will help implementing the MVP scope.

I would answer all your questions raised with: Yes, correct. 
Not sure if we need a separate flow for different scenarios (create, extend, reduce); the behavior should be the same - in my mind the flow is always the same: The coordinator comes up with new `ContractInfo`, communicates it to the client and then they set up a new contract replacing the old one; i.e. they set up a new DLC channel.
For me "reducing" or "extending" is always a replace of the old channel; or do we expect to actually *change* the existing DLC channel @bonomat ?

**Comment by bonomat** [comment]
>  Not sure if we need a separate flow for different scenarios (create, extend, reduce); the behavior should be the same - in my mind the flow is always the same: The coordinator comes up with new ContractInfo, communicates it to the client and then they set up a new contract replacing the old one; i.e. they set up a new DLC channel.

I'm with Daniel here, the flow is always the same: 
1. The trader posts a market order
2. The orderbook comes back with a match
3. The trader's app knows what todo: (i) open new DLC channel, (ii) close DLC channel, (iii) extend DLC channel, (iv) reduce DLC channel


>  For me "reducing" or "extending" is always a replace of the old channel; or do we expect to actually change the existing DLC channel @bonomat ?

From a technical perspective it is always closing the existing channel and creating a new one: we need to re-create all transactions.

**Comment by holzeis** [comment]
> > For me "reducing" or "extending" is always a replace of the old channel; or do we expect to actually change the existing DLC channel @bonomat ?
> 
> From a technical perspective it is always closing the existing channel and creating a new one: we need to re-create all transactions.

I've talked to @luckysori about that and since it's all off-chain. It should be possible to simply update a dlc channel, instead of closing and opening it again. But I guess this is just semantics.
