### ISSUE TITLE
Can't open another position after losing

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1815]
After opening the smallest possible position (100) and losing some dollars >=$1 one cannot trade again.
The problem is that the min amount to trade is $100, we have put up $100 into the channel but lost after the first trade $1, meaning we only have $99 left and hence cannot trade again (unless taking higher leverage).

How to reproduce: 
1. open a channel/trade with $100
2. close and lose some money
3. try to open another position
4. frontend tells you max quantity is $99 (because of your remaining margin) but min trade size is $100

**Comment by bonomat** [comment]
This will be resolved with https://github.com/get10101/10101/issues/1797

**Comment by holzeis** [comment]
@bonomat by setting the min quantity to 1, I think this issue is resolved. Can we close this ticket?

**Comment by bonomat** [comment]
Yes, let's close this.
