### ISSUE TITLE
Rollover failed

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1841]
I just got the push notification that rollover window is open but it failed after some time.

[2024-01-18_170616.log](https://github.com/get10101/10101/files/13978960/2024-01-18_170616.log)

**Comment by holzeis** [comment]
@bonomat can you check if you have a correct expiry though?

**Comment by bonomat** [comment]
It was ok (now I closed the position). 

The error seems to be this: 

`
[ERROR] TIME: 2024-01-18T07:56:19.082556Z r: Failed to process incoming DLC message: Cannot rollover non-existing position from: 03507b924dae6595cfb78492489978127c5f1e3877848564de2015cd6d41375802,kind: ChannelRenewOffer
`

**Comment by bonomat** [comment]
This was potentially fixed with https://github.com/get10101/10101/pull/1838/files as the error message `Cannot rollover non-existing position` has been removed.
