### ISSUE TITLE
Funding amount input is not enough to cover collateral, fund fee cet or refund fee and extra fee

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1912]
After upgrading to 1.8.3 I tried to open a dlc channel with a quantity of 260 and a leverage of 2. When trying to accept the offer I fail to do so.

In my scenario I had the following values:

required collateral:  `360,664`
required fund_fee: `15,086` sats 
required cet_or_refund_fee: `3,230` sats
required extra_fee: `10,260`

===
total required input funds: `389,240` sats

However the total funds reserved for the funding transaction have only been `367,470` which is not enough to create the funding transaction. Consequently accepting the offer fails.

-----

I suspect that the following section does not take all required fees into account.

https://github.com/p2pderivatives/rust-dlc/blob/49ace9b4bc5eea6360d06773c53348af9efb002c/dlc-manager/src/utils.rs#L62-L128

**Comment by holzeis** [comment]
It appears we only consider the `common_fee` + `collateral` when looking for utxos, but when creating the funding transactions with fees we are looking at looking at `collateral` + `fund_fee` + `cet_or_refund_fee` + `extra_fee`.  I am pretty sure that this is the reason for this bug.

I guess I run into this error because I have multiple smaller utxos and it was possible to find a set of utxos which are much closer to the `common_fee`+ `collateral` (which is not enough eventually).

I think we did not run into this issue during testing, because we always had gigantic utxos which automatically also covered the additional fees required to create the funding transaction. It should be possible to demonstrate that in a simple test.

**Comment by luckysori** [comment]
Nice investigation, @holzeis. I was able to confirm that with a bunch of 10k sats UTXOs I can reproduce the original issue if I open a big enough channel. I'll work on a fix.
