### ISSUE TITLE
No infos on funding fees anywhere

### ISSUE THREAD

**Issue by carboncls** [get10101/10101#1913]
Hi, I was wanting to try out the app, but I cannot find any info on a fee schedule. The app let's you buy with leverage but doesn't say how much you pay for borrowing money.

**Comment by bonomat** [comment]
Thanks for creating a ticket @carboncls . You are right, at the moment there are no funding rates. We are working on this and will roll it out in a later release.

**Comment by bonomat** [comment]
Tracked here: https://github.com/get10101/10101/issues/1926

**Comment by carboncls** [comment]
Well, I didn't mean to make you add a funding fee =) I just thought it was important information, whether there is none, or if there is one, how much it is.
