### ISSUE TITLE
Rejecting a dlc channel does not update the apps state

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1919]
At the moment the moment rejecting a dlc channel offer on the app side, does not update the channel state of the app. There seems to be a api missing in the rust-dlc library to do that.

Additionally, there seems to be a handling missing on how to deal with rejecting a dlc offer that is not yet on a signed channel. IMHO it should be fine to simply delete the `OfferedChannel` on both sides. (waiting for feedback from tibo on that matter).

It also looks like that the `Reject` message never got received / processed on the coordinator side. This might be an additional bug.

related to #1912

**Comment by luckysori** [comment]
> At the moment the moment rejecting a dlc channel offer on the app side, does not update the channel state of the app. There seems to be a api missing in the rust-dlc library to do that.

Ah, I see that there is no API missing. It's just that we manually construct the message instead of calling `reject_renew_offer` or `reject_settle_offer`.

> Additionally, there seems to be a handling missing on how to deal with rejecting a dlc offer that is not yet on a signed channel. IMHO it should be fine to simply delete the OfferedChannel on both sides. (waiting for feedback from tibo on that matter).

Yeah, this just needs to be added to `rust-dlc`.

> It also looks like that the Reject message never got received / processed on the coordinator side. This might be an additional bug.

I noticed this too. The message is received, but the coordinator doesn't understand it:

```
lightning::ln::peer_handler: Received unknown even message of type 43024, disconnecting peer!
```

This leads to a reconnect which moves us into https://github.com/get10101/10101/issues/1918 territory.

**Comment by holzeis** [comment]
> I noticed this too. The message is received, but the coordinator doesn't understand it:
> 
> ```
> lightning::ln::peer_handler: Received unknown even message of type 43024, disconnecting peer!
> ```

Just a missing mapping in the message handler

https://github.com/p2pderivatives/rust-dlc/commit/1549522ca3a204a760ad2c7edcff55abf3350796

**Comment by holzeis** [comment]
Working on this ticket a bit, I noticed that we also missing proper state handling on the app layer updating the failed position and order correspondingly. Not handling that correctly already lead to issues - see also #1921

**Comment by luckysori** [comment]
> Just a missing mapping in the message handler
> 
> [p2pderivatives/rust-dlc@1549522](https://github.com/p2pderivatives/rust-dlc/commit/1549522ca3a204a760ad2c7edcff55abf3350796)

Nice find! Ah, a classic problem with `rust-dlc` not testing the message handler!

> We need to adapt `rust-dlc` to be able to process a `Reject` message on a dlc channel offer. I propose we simply delete the dlc channel if still not `Signed`. wdyt?

That sounds fine to me, but I would check with Tibo.

**Comment by holzeis** [comment]
>> We need to adapt rust-dlc to be able to process a Reject message on a dlc channel offer. I propose we simply delete the dlc channel if still not Signed. wdyt?
> That sounds fine to me, but I would check with Tibo.

I decided against deleting the dlc channel and rather introduce a `CancelledChannel` state. IMO it's better to mark the dlc channel as cancelled opposed to completely delete it. E.g. for debugging purposes etc.
