### ISSUE TITLE
Creating a payment request on-chain with an amount leads to a malformed address

### ISSUE THREAD

**Issue by Restioson** [get10101/10101#1929]
Steps to reproduce:
- Navigate to balances screen
- Select on-chain
- Click 'receive'
- Click 'edit'
- Enter an amount
- Click 'continue'
- Click the copy icon next to 'Address'

In this case, what is copied is something like `bcrt1qh2dgxfxy9wmwsmspl49saf0tas54jaq8gns7ln?amount=0.00000123`. As far as I am aware this is not a valid address. We create this by removing the BIP21 `bitcoin:` prefix, but we don't remove the query parameters such as the amount. Thus this is neither a valid address nor a valid BIP21 URI

The copy icon under the QR code is still okay as it does not truncate the `bitcoin:` prefix

**Comment by Restioson** [comment]
As an aside, what is the expected behaviour here? We could just leave it out but it may be confusing that there are two separate copy buttons which do different things.

If we just want the address to be just the real address part, we could easily alter the SharePaymentRequest struct/class to include the bare address too

**Comment by bonomat** [comment]
> In this case, what is copied is something like bcrt1qh2dgxfxy9wmwsmspl49saf0tas54jaq8gns7ln?amount=0.00000123. As far as I am aware this is not a valid address. We create this by removing the BIP21 bitcoin: prefix, but we don't remove the query parameters such as the amount. Thus this is neither a valid address nor a valid BIP21 URI

lol, this was me 🙈
