### ISSUE TITLE
Web app randomly stops responding

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1938]

**Comment by holzeis** [comment]
still happening

**Comment by holzeis** [comment]
The latest version has been deployed to demo environment. Let's monitor if the app is stopping to respond.

**Comment by holzeis** [comment]
Seems to be fixed with https://github.com/get10101/10101/pull/2118 🥳

**Comment by bonomat** [comment]
Webapp has been running for ~11 days and is not reachable anymore :(

**Comment by bonomat** [comment]
We should try what was mentioned in https://github.com/get10101/10101/pull/2118
