### ISSUE TITLE
`Latest` release

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1949]
What do you think of having a `Latest` release on GitHub which is constantly updated whenever we merge something into `main`? We could use this to attach
- build binaries like `coordinator`/`maker`,`webapp`
- android apks

_Originally posted by @bonomat in https://github.com/get10101/10101/issues/1943#issuecomment-1924546493_

**Comment by holzeis** [comment]
You mean whenever we release right? In the context of apk releases, we still have to make sure that the coordinator is upgraded in coordination.

If not what benefits do you see in releasing every merge to main?

**Comment by bonomat** [comment]
> You mean whenever we release right? 

No, I mean whenever we merge, like a nightly release, just not nightly, but whenever we merge. 

> If not what benefits do you see in releasing every merge to main?

The benefits are: 
- a static link for all _latest_ release binaries
- a place to find _latest_ apks

It might be confusing though if this is called **latest** because people might understand that this is the latest stable release.

**Comment by bonomat** [comment]
> In the context of apk releases, we still have to make sure that the coordinator is upgraded in coordination.

The default values will go against our regtest setup.
