### ISSUE TITLE
Failed executing the DLC protocol

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1971]
How to reproduce

- Funded wallet with 500k sats.
- Open position with the max quantity possible $429 (x2). Margin: 495,381 sats

![image](https://github.com/get10101/10101/assets/382048/c6882ec8-a43c-4373-9839-6d30ab5e86b0)

**Comment by holzeis** [comment]
Logs do not reveal a lot unfortunately.

```
[ERROR] TIME: 2024-02-06T19:57:51.610389Z r: Failed to accept dlc channel offer. Dlc error 
```

should be improved with https://github.com/p2pderivatives/rust-dlc/pull/204

**Comment by luckysori** [comment]
Will be solved with https://github.com/get10101/10101/issues/2022.
