### ISSUE TITLE
No bnb solution found after 0 rounds

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1972]
```
[ERROR] TIME: 2024-02-06T19:55:23.057700Z r: Failed to accept dlc channel offer. Invalid state: Could not find utxos for amount: Failed to select coins

Caused by:
    No bnb solution found after 0 rounds (max rounds is 100000). 
```

**Comment by holzeis** [comment]
the user finally got the order through. I presume its related to the fees not being properly considered as the margin was pretty close to the max balance.

**Comment by bonomat** [comment]
If he had tried before his UTXOs might have simply been locked.

**Comment by holzeis** [comment]
> If he tried before and failed, his UTXOs might have simply been locked.

yes, I think you are right. Closing this ticket in favor of https://github.com/get10101/10101/issues/1971
