### ISSUE TITLE
Error running `docker-compose up`

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#199]
```
ARNING: Image for service coordinator-db was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Pulling adminer (adminer:)...
latest: Pulling from library/adminer
32fb02163b6b: Pull complete
211049d859dd: Pull complete
fad214499817: Pull complete
a1013a6619f4: Pull complete
0f914a1428c6: Pull complete
fbfe08e4fb04: Pull complete
bad45ce694ef: Pull complete
Digest: sha256:63139b85e7d786a88afd12e800af9934f72052ac02223830119ab72b828972bb
Status: Downloaded newer image for adminer:latest
Creating 10101_adminer_1 ...
Creating 10101_coordinator-db_1 ...
Creating bitcoin                ... error
Creating 10101_adminer_1        ... done
Creating 10101_coordinator-db_1 ... done
50f7f5c924ef2bcf6c9704fd94db65e9b62d42b377d9517a7c". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for bitcoin  Cannot create container for service bitcoin: Conflict. The container name "/bitcoin" is already in use by container "38a315f888aff750f7f5c924ef2bcf6c9704fd94db65e9b62d42b377d9517a7c". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
```

If everyone agrees, I would like to rename the `bitcoin` container to `10101_bitcoin` to ensure that we don't step on toes of other setup that might be already present (like the problems above).

**Comment by holzeis** [comment]
I am wondering if the issue would be resolved if we simply remove the 'container_name'.

**Comment by bonomat** [comment]
> I am wondering if the issue would be resolved if we simply remove the 'container_name'.

I prefer keeping _a_ container name because than it is easier to remember cli commands to get the logs (i.e. docker logs -f lnd)

**Comment by bonomat** [comment]
I have no hard feelings about names as long as they remain constant

**Comment by klochowicz** [comment]
I've realised that this was due to the case I had a nigiri node running previously, and didn't prune the containers. I've described this in the README, this should be enough as I assume that we don't need `nigiri` and `10101` running at the same time for now?

If we would like to support such use case, we'd need to change both the container names and exposed ports to avoid conflicts.
