### ISSUE TITLE
Cannot save new contact details

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#2008]
![image](https://github.com/get10101/10101/assets/9418575/691adac2-73e4-4e67-8954-be1a7bbc857f)

**Comment by holzeis** [comment]
🤔 I just tried on the test environment and it worked for me.

Judging from the 404 error it may have failed to deploy the test coordinator when you tried?

**Comment by luckysori** [comment]
> 🤔 I just tried on the test environment and it worked for me.
> 
> Judging from the 404 error it may have failed to deploy the test coordinator when you tried?

This was in production. I guess the coordinator hasn't been updated yet.

**Comment by bonomat** [comment]
> This was in production. I guess the coordinator hasn't been updated yet.

Yes, latest version in production i 1.8.6 which does not have this feature yet. I assume you've updated your app already to 1.8.7 since you are in the pre-release group. 

I think this is not an issue.
