### ISSUE TITLE
Coordinator: Shadow dlc channel into database

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2012]
Analog to what we've done with a lightning channel, it would be nice to have some additional meta data stored in the 10101 database.

- trader pubkey
- trader balance
- coordinator balance
- created at timestamp
- updated at timestamp
- funding txid
- closing txid
- buffer txid
- refund txid
- punish txid

**Comment by luckysori** [comment]
Less of a priority after adding the closing transaction to the DLC channels in `rust-dlc`.
