### ISSUE TITLE
Stop periodically syncing sub channels

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2013]
This is an unnecessary overhead and should be removed from the interval tasks.

Note, make sure to add the `dlc_channel_manager.periodic_check` back to the `manage_dlc_manager` task. 

```
if let Err(e) = self.dlc_channel_manager.periodic_check() {
            error!(
                "Error performing periodic check of the channel manager: {}",
                e
            );
        }
```

**Comment by bonomat** [comment]
If we remove this, we might not be able to detect closed channels
