### ISSUE TITLE
Add reject flow to collab close offer

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2019]
We shouldn't automatically accept any collab close offer, equally I don't think it reasonable to automatically force close those dlc channels either. 

I propose we implement a flow to reject a collab close offer.

**Comment by bonomat** [comment]
Proposal: implement a simple if check which does not automatically accept a collab close offer. In a later phase we will then implement the reject flow.

**Comment by bonomat** [comment]
> Proposal: implement a simple if check which does not automatically accept a collab close offer. In a later phase we will then implement the reject flow.

see https://github.com/get10101/10101/issues/2156
