### ISSUE TITLE
Network fees are spinning forever

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2024]
![IMG_F63E2CCFEBD7-1](https://github.com/get10101/10101/assets/382048/c24ec7a5-0a2c-4f7f-b04c-0348f54dfba6)

**Comment by bonomat** [comment]
Was this mainnet/testnet setup or local dev setup?

**Comment by holzeis** [comment]
I think it was on mainnet, but its not happening anymore.. I am closing this ticket for now until it happens again.
