### ISSUE TITLE
App: Flaky test `e2e_restore_from_backup`: Cannot acquire db lock

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#2033]
Here is the failure in CI: https://github.com/get10101/10101/actions/runs/7899457897/job/21559444712?pr=2032#step:10:145.

Perhaps related to our recent switch to separate jobs per e2e test (probably not).

**Comment by bonomat** [comment]
That's a new error : 

```
 2024-02-14T10:15:34.781418Z ERROR native::orderbook: Failed to handle event: Trade request sent to coordinator for order 83bf0e51-aaa7-4e13-a554-9472e75c12bb failed: Could not load order from db: cannot acquire database connection: timed out waiting for connection
```

**Comment by bonomat** [comment]
I've created #2050, maybe it shows us anything interesting.

**Comment by bonomat** [comment]
> It makes me think it does have to do with the setup, @bonomat.

Thinking about it more: I don't think it has todo with the new setup. This is the client db, i.e. the sqlite db

https://github.com/get10101/10101/blob/84a47917a8508cd3ef35755ce0be21fd03b7a53d/mobile/native/src/db/mod.rs#L145-L149

Meaning, my patch in #2050 won't show us anything.

**Comment by bonomat** [comment]
This was fixed.
