### ISSUE TITLE
Get rid of non-standard seed derivation

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2037]

**Comment by luckysori** [comment]
Related to https://github.com/get10101/10101/issues/1241 😍

**Comment by luckysori** [comment]
I suppose this is motivated by not needing to have a Lightning seed anymore. That is true, although we still need to have a seed for certain traits that we have to implement for `rust-dlc` (namely `ContractSigner` and `ContractSignerProvider`, in `rust-dlc#master).

I would still advocate for having a way for the user to be able to recover their on-chain funds without our help, by having a standard seed for that like this ticket seems to suggest. But we will still have to account for the `rust-dlc` somehow.
