### ISSUE TITLE
Verify fee rate when force-closing a channel

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#2071]

**Comment by luckysori** [comment]
We don't quite remember what this is about, @bonomat. Help.

**Comment by bonomat** [comment]
I think we did this already. 
The question here was to verify what fee rate we use when force-closing a channel and if it is the one we set when opening the contract.

**Comment by holzeis** [comment]
> I think we did this already. 
> 
> The question here was to verify what fee rate we use when force-closing a channel and if it is the one we set when opening the contract. 

And is it? 😅
