### ISSUE TITLE
Add release notes to the app

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#2119]
We could add a new section to our settings page to list all the changes that come with every new release.

To be honest, I'm no longer all that keen on this idea because I think this stuff belongs in the App Store's version history (once we are there) or in TestFlight's `Previous builds` section. I suppose Android has a similar concept.

---

This came up during our last retro.

**Comment by holzeis** [comment]
I am not a fan of this either.. did we really say add the release notes to the app? The user would see the testflight message, when starting the new version. There we already provide the latest updates. For Android we can provide Release Notes in Google Play and on our Release github page.

**Comment by luckysori** [comment]
> I am not a fan of this either.. did we really say add the release notes to the app? The user would see the testflight message, when starting the new version. There we already provide the latest updates. For Android we can provide Release Notes in Google Play and on our Release github page.

I think I suggested it and someone else liked the sound of it. I will just close it now, but I wanted to fulfill the retro action item.
