### ISSUE TITLE
Replace candlestick chart

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2123]
Note, I didn't manage to set the background of the candlestick chart back to white, but we might want to consider replacing that dependency altogether, since it doesn't seem to be maintained anymore.

_Originally posted by @holzeis in https://github.com/get10101/10101/issues/2122#issuecomment-1970884220_

**Comment by holzeis** [comment]
Try migrating to `fl_chartfl_chart` https://app.flchart.dev/#/line

**Comment by bonomat** [comment]
> Try migrating to `fl_chart` [app.flchart.dev/#/line](https://app.flchart.dev/#/line)

Unfortunately fl_chart does not support scrollable axis, meaning, you won't be able to scroll left or right :/

**Comment by bonomat** [comment]
Maybe we should look into TradingView again. My last conclusion was that it does not work well on mobile because of the layout/font size. It looks like though one can configure quite a bit on the widget: 

https://www.tradingview.com/charting-library-docs/latest/core_concepts/Widget-Constructor/

**Comment by Restioson** [comment]
If we are going to switch to TradingView, would we just use their data source or do we need to stick specifically with Bitmex's?

**Comment by bonomat** [comment]
> If we are going to switch to TradingView, would we just use their data source or do we need to stick specifically with Bitmex's?

For time being we should use BitMex because we don't have enough depth in our orderbook yet.

>Additionally, the flutter_webview package (which would be required to display the TradingView chart) does not support desktop, so we would not be able to use the same solution for both desktop and iOS. This is fine as we are not targetting desktop, but could be irritating.

Yes, that sucks a bit. You can look into DLC-Connect where I'm using a library which supports desktop. But for the App I think it's fine to use the native flutter webview - it's not meant to run on Desktop
