### ISSUE TITLE
On chain balance and history is gone

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2129]
Environment: test

After upgrading the test app to the latest TestFlight version my on-chain balance and history seems to be gone. See screenshot below.

The only thing that might be relevant for this bug found in the logs is the following.

```
Failed to run DLC manager periodic chain monitor task: Invalid state: Current height is lower than last height
```

![IMG_53B731AC3B49-1](https://github.com/get10101/10101/assets/382048/f0580162-30b9-458f-bb66-f4ceec9c667a)

**Comment by holzeis** [comment]
With https://github.com/get10101/10101/pull/2094 the sled db was deleted. In order to get the on-chain balance and history back we need to make a full sync with gap. Gradually increase the gap until the on-chain balance and history is back. e.g. 5/10/20/50

**Comment by bonomat** [comment]
> With #2094 the sled db was deleted. In order to get the on-chain balance and history back we need to make a full sync with gap. Gradually increase the gap until the on-chain balance and history is back. e.g. 5/10/20/50

We should communicate this with our users
