### ISSUE TITLE
Failed to process incoming DLC message: No order to mark as Filled

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2136]
At the moment, if we can't find an order in `Filling` we stop everything. In case of https://github.com/get10101/meta/issues/355 that got the protocol stuck again, because the position was not deleted and the last message was also not sent back to the user.

Now the state is broke and has to be cleaned up.

I propose we do not stop the process in case we can't find an order in `Filling` but rather print a warning as this is not a super critical thing.

**Comment by bonomat** [comment]
This has already been fixed.

**Comment by holzeis** [comment]
Reopening this ticket as this is still happening and causing issues. related to https://github.com/get10101/10101/issues/2361
