### ISSUE TITLE
Add a max trade button

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2139]
We have a lot of users that try to trade with the max balance they have in their wallet (balance).

Two phases: 

1. [x] use max on-chain balance to open a channel
2. [ ] use max off-chain balance to trade

**Comment by bonomat** [comment]
Show this max button at least when the channel is open.

**Comment by bonomat** [comment]
Mhm, this is actually not easily possible. 
The only way to define how much you want to trade is by entering a `. However, while the `quantity` is fixed, the actual margin is dynamic and depends on the rate. 
A user doesn't want to trade max quantity but max `margin`, i.e. say to the orderbook, I want to buy/sell for all the sats I own.

This idea has been proposed before here: https://github.com/get10101/10101/issues/1712

**Comment by holzeis** [comment]
> This idea has been proposed before here: #1712

I like it, I guess the user wouldn't need to see the actual quantity if we tell them we will buy the max possible. I would do it similar to how its done on the send on-chain funds screen. In the background we can run a margin order.

**Comment by bonomat** [comment]
I'm throwing this back into the pile because I burned my fingers with https://github.com/get10101/10101/pull/2282 and need to lick my wounds before giving it another go.
