### ISSUE TITLE
Show price and direction of open order when bragging

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2182]
When closing a position the dialog lets you brag about your pnl. But it shows the direction and the entry price of the closing order instead of the opening order

**Comment by bonomat** [comment]
It also shows the direction of the closing order, not the direction of the position which is a bit weird.

**Comment by bonomat** [comment]
<img width="502" alt="image" src="https://github.com/get10101/10101/assets/224613/18e0ced2-e86c-424d-9b66-e6c1b8379653">

**Comment by bonomat** [comment]
Closed in favor of https://github.com/get10101/10101/issues/2199#issuecomment-1990960683
