### ISSUE TITLE
Share after position opening shows pnl of 0

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2199]
Even though the position wasn't exactly 0 after opening the "Share as image" the numbers on the brag image are always 0.

![image](https://github.com/get10101/10101/assets/382048/96f7f9e4-ff37-4437-9b30-66c913785eae)

**Comment by bonomat** [comment]
How to reproduce: 

1. open position 
2. click on share button

**Comment by bonomat** [comment]
The bug here is that we take the price of the order and compare it against the position, hence, PnL is always 0

**Comment by bonomat** [comment]
Related to https://github.com/get10101/10101/issues/2182

**Comment by bonomat** [comment]
Proposal: remove the share button from the dialog.
