### ISSUE TITLE
Setup oracle for production

### ISSUE THREAD

**Issue by 1010Tom** [get10101/10101#221]

**Comment by klochowicz** [comment]
@holzeis is that containerised? if yes than we could easily include that in our dev container setup?

**Comment by holzeis** [comment]
> @holzeis is that containerised? if yes than we could easily include that in our dev container setup? 

Yes, that's what we are currently using.

https://github.com/p2pderivatives/p2pderivatives-oracle

It also requires a Postgres database, but we already have that in our setup so we should be good to go.

@bonomat we should also run our own oracle for regtest and prod.

**Comment by bonomat** [comment]
Do you have the docker run command? Then we can just throw it onto the VMs

**Comment by bonomat** [comment]
Deemed to be a post mvp Ticket

**Comment by bonomat** [comment]
Closing this in favor of : https://github.com/get10101/cloud-conf/issues/211
