### ISSUE TITLE
App bar changes color when scrolling down

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2217]
![IMG_4715](https://github.com/get10101/10101/assets/382048/8768b8fd-ab57-4d42-a74a-64a660154a6b)

**Comment by Restioson** [comment]
At first I didn't understand what you meant, but now I see: it should be white, but scrolling down makes it purple.
![image](https://github.com/get10101/10101/assets/6688948/017418c3-43f7-44e9-b736-b05479539713)
![image](https://github.com/get10101/10101/assets/6688948/29d2307e-84e9-4256-88ce-78a2fb590f15)
