### ISSUE TITLE
update order in db when necessary

### ISSUE THREAD

**Issue by 1010Tom** [get10101/10101#223]
https://github.com/get10101/10101/pull/208 set the foundation for storing the order in the DB. What is missing is to update the order whenever something happens, e.g. when it gets created or filled.

**Comment by da-kami** [comment]
My understanding: This ticket is about implementing the *business logic* that triggers the creation  / update of the order in the database, i.e. use the database interface that was created. I will see to wire that together :)

**Comment by da-kami** [comment]
I basically completed the (happy path) order lifecycle as part of this ticket and would go on with the position next; which requires the position handling in the DAL.

**Comment by bonomat** [comment]
done
