### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2233]

**Comment by itsmesuraj20** [comment]
Hey I m new to this,
Can you assign me for this task

**Comment by holzeis** [comment]
> Hey I m new to this,
> 
> Can you assign me for this task

Hey @itsmesuraj20 ! Sure, thanks for contributing. Let us know if you need help. You can find us here https://matrix.to/#/%23tentenone%3Amatrix.org

**Comment by bonomat** [comment]
Hi @itsmesuraj20 , just checking in if you need any guidance?

**Comment by itsmesuraj20** [comment]
Yes I m into the contribution ,
i m not able to contribute it right now as I m buckle up with my final year semester exam 
Which is going to over in fews 

Then I will surely start my contribution in this 
Hope you get this 


And tell me if there is any slack channel or discord channel for the assistance 
Please as I m newbie in open source contribution thing

Regards , 
Suraj Singh

**Comment by bonomat** [comment]
Hi @itsmesuraj20 , you can join us on Matrix here: [matrix.to/#/%23tentenone%3Amatrix.org](https://matrix.to/#/%23tentenone%3Amatrix.org). Feel free to ping us there if you need help to get started and all the best with your exams.

**Comment by itsmesuraj20** [comment]
Thanks for sharing

**Comment by itsmesuraj20** [comment]
@bonomat should I have the deep understanding of flutter to get started with it 
as I have worked on react, next js

**Comment by itsmesuraj20** [comment]
Some one please help to setup this project locally 
I having trouble to install all the required thing in windows 11 
Please help me !
