### ISSUE TITLE
Trading fees breakdown

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#224]
As a user I want to know what fees I am paying when submitting an order.

The scope of this ticket includes:

- Being able to query the fees from the app backend
- Include the fees into the buy/sell bottom sheet (that might require displaying the fees there)
- Display the fee breakdown in the confirmation screen

*Not* within the scope of this ticket:

- Fees that are not related to trading
- Perpetual fees

**Comment by bonomat** [comment]
Fees which are relevant: 

- orderbook fee (maker/taker fee)
- transaction fee (inside the virtual channel) - user gets those back

**Comment by bonomat** [comment]
related to  #225

**Comment by holzeis** [comment]
Find below my proposal on how to break down the trading fees.

- I opted to add the fees directly to the trading screen, as I remember having some feedback from users, that they wanted to see the fees right away.
- It is a bit tricky to depict the "collateral tx fees" (representing a transaction fee in case we have to go onchain) as this is already part of the margin. I opted to add the total costs as well to the trade screen to show that these costs are already covered in the margin. The **info** should give more explanation about the nature of this fee. I would do that in the same way as we are currently depicting our market order info button.


![Image](https://user-images.githubusercontent.com/382048/226598071-561891b7-5718-4eb6-9180-a49f0a4a22fd.png)

**Comment by holzeis** [comment]
@da-kami @bonomat @luckysori @klochowicz any thoughts on this?

**Comment by bonomat** [comment]
Sorry for missing this. 

I don't see it yet but it would be good if we could indicate better that `Collateral Tx Fee` is not being paid but just a collateral. I would not group it into `Fees` because of this. 

... Maybe `PWCTX` (Potential Worst-Case Transaction Fee) 😬.

The `matching fee` sounded weird to me first because I have never heard it in this context. What do you think of `trading fee`? I know this makes it more abstract than _matching_ but it reflects that this is the fee which needs to be paid for _trading_.

**Comment by holzeis** [comment]
> I don't see it yet but it would be good if we could indicate better that `Collateral Tx Fee` is not being paid but just a collateral.

The idea was to add the explanation to the info button in the same way as we are currently depicting our market order info button.

> I would not group it into `Fees` because of this.

fair enough, I'll remove the grouping.

> ... Maybe `PWCTX` (Potential Worst-Case Transaction Fee) 😬.

Sounds a bit complicated 😅, maybe we shouldn't call it a fee at all? 🤔 

> The `matching fee` sounded weird to me first because I have never heard it in this context. What do you think of `trading fee`? I know this makes it more abstract than _matching_ but it reflects that this is the fee which needs to be paid for _trading_.

If this is the more common terminology, I am happy with it. Another option could be `orderbook fee`.

**Comment by bonomat** [comment]
> fair enough, I'll remove the grouping.

thanks :) 

> Sounds a bit complicated 😅, maybe we shouldn't call it a fee at all? 🤔

I was not 100% serious...or was I ? 😅 I think it's fair to call `fee`. I would not overthink this for now and just call it what it is: `Potential Worst-Case Transaction Fee`

> If this is the more common terminology, I am happy with it. Another option could be orderbook fee.

Imho it is. `ordebook fee` also works for me.

**Comment by holzeis** [comment]
Users suggestion on how to display the `Collatoral Tx Fee` or `Potential Worst-Case Transaction Fee` after the money is locked up. I guess we will still need a way of communicating this fee upfront.

![ET6NOk1N](https://github.com/get10101/10101/assets/382048/ac1ef072-52ab-479c-8990-bbe6b9d3d8ce)

**Comment by da-kami** [comment]
> Users suggestion on how to display the `Collatoral Tx Fee` or `Potential Worst-Case Transaction Fee` after the money is locked up. I guess we will still need a way of communicating this fee upfront.
> 
> ![ET6NOk1N](https://user-images.githubusercontent.com/382048/248694580-ac1ef072-52ab-479c-8990-bbe6b9d3d8ce.jpg)

I like the suggestion of the user - on top of that we could abstract a simplified overview - potentially without text, and then details when the user opens the dropdown for balance details.

Something like this maybe:

![wallet-screen_fee-reserve](https://github.com/get10101/10101/assets/5557790/e75c8268-10ee-48e5-9ded-83401abeed00)
