### ISSUE TITLE
Balance is not loaded at startup

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2246]
This seems to be a regression. At startup the balance isn't immediately ready, but needs a few seconds before being loaded. This is not reproducible on the prod app version.

Environment: test

https://github.com/get10101/10101/assets/382048/ae80dc01-4c9f-4da9-ba0d-d05c931c3833

**Comment by luckysori** [comment]
I think this has to do with removing the dedicated wallet refresh (without sync) on startup. We can just add it again.
