### ISSUE TITLE
Open channel fee breakdown / display 

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#225]
As a user I want to know the fees when I fund the app initially.

Scope of this ticket includes:

- Query the app backend for the fees when opening a channel
- Integrate the fee(s) in the user interface in the `Receive` flow (if there are fees they should be displayed)

*Not* part of this ticket:

- Fees in the transaction history are covered in #67 
- *Recurring* fees that we charge for keeping a channel open are treated as separate feature.

**Comment by holzeis** [comment]
Do we want to keep these fees? Eventually, we might want to add them again, but initially I would simply do it for "free".

**Comment by bonomat** [comment]
> Do we want to keep these fees? Eventually, we might want to add them again, but initially I would simply do it for "free".

Why would you do it for free? We occur on-chain transaction fees when opening a channel with them.

**Comment by holzeis** [comment]
Closing in favor of https://github.com/get10101/10101/issues/577
