### ISSUE TITLE
Persist limit orders

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#227]
The maker is currently not persisting anything, which means, on a restart, it won't remember anything. 

This ticket is about storing 
- orders and their states

Once we have positions, we should also store them

**Comment by holzeis** [comment]
@bonomat this ticket looks relevant for milestone 1.0.22, but lacks some description. May I ask you to add details or close the ticket?

**Comment by luckysori** [comment]
> Once we have positions, we should also store them

We can do this as part of https://github.com/get10101/10101/issues/973, or as a follow-up.
