### ISSUE TITLE
Show poll title instead of a generic message

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2276]
At the moment we show a generic "time for a quick survey" box, instead we could show the actual question which may engage the user more to answer.

**Comment by holzeis** [comment]
@SXBT69 please update if my description of the ticket did not match your understanding.

**Comment by bonomat** [comment]
> At the moment we show a generic "time for a quick survey" box, instead we could show the actual question which may engage the user more to answer.

We will need to re-design the whole component because otherwise the title will be shown twice.

**Comment by bonomat** [comment]
when doing this, we should update the coordiantor API to only return a single poll.

**Comment by bonomat** [comment]
when doing this we could re-redesign this component and use a dialog instead. This dialog then can be shown on different screens.
