### ISSUE TITLE
CI failure with `docker logs maker`

### ISSUE THREAD

**Issue by Restioson** [get10101/10101#2289]
![image](https://github.com/get10101/10101/assets/6688948/0d2bbabd-746f-4105-8d04-9e59a5a72b0f)

See this failure: https://github.com/get10101/10101/actions/runs/8324505745/job/22919454343?pr=2272

cc @bonomat

**Comment by bonomat** [comment]
Has been fixed in 799a4cd2858f6387022a57359b5abf1cc3cc66b8
