### ISSUE TITLE
CI: Ensure no changes when running `flutter pub get` on CI

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#230]
We had several instances where we had changes to files (e.g. `pubspec.lock`) in the mobile project after something merged into `main`.
CI should ensure that all files are up to date when running `flutter pub get`; i.e. no changes on git.

**Comment by luckysori** [comment]
Did we do this? @da-kami @klochowicz @holzeis

**Comment by klochowicz** [comment]
@luckysori I don't think so. I suspect that this issue got mention by mistake; there's nothing on the CI that checks this.
