### ISSUE TITLE
User gets a bad request error instead of the error message

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2310]
Environment: test

If a user with an older version tries to trade with the coordinator the request is rejected with a bad request.

Instead of the http error the error message should be shown.

More specifically the user should see that a new version is available if the request gets rejected due to the version check.

![image](https://github.com/get10101/10101/assets/382048/d3731fd4-4f2e-4a64-b019-d5997280e8b5)

**Comment by holzeis** [comment]
I am labelling this as a bug since this used to work.

**Comment by bonomat** [comment]
I don't think we ever showed a better error here. 

We don't know more here unfortuantely because axum is rejecting the http request because the URL/body has changed.

I'm removing the bug here. What we can do is show a different error instead.

**Comment by holzeis** [comment]
> I don't think we ever showed a better error here. 
> 
> 
> 
> We don't know more here unfortuantely because axum is rejecting the http request because the URL/body has changed.
> 
> 
> 
> I'm removing the bug here. What we can do is show a different error instead by catching the reqwest error.
> 
> 

I do agree if the api changes. But this is not the case from 2.0.5 to 2.0.6. The user should see an error message that 2.0.6 is available.

**Comment by bonomat** [comment]
Do you have the logs by any chance?

**Comment by holzeis** [comment]
The relevant log on the coordinator

```
2024-03-25 14:21:05 ERROR post_order: coordinator::orderbook::routes: error=BadRequest("Please upgrade to the latest version: 2.0.6")
```

The relevant logs on the app

```
flutter: [ERROR] TIME: 2024-03-25T14:21:05.583718Z r: Failed to post new order: HTTP status client error (400 Bad Request) for url (http://127.0.0.1:8000/api/orderbook/orders) order_id: 8aa7b627-79c3-4571-90b1-a4e8dcfefe62
flutter: [ERROR] TIME: 2024-03-25T14:21:05.584267Z r: Executed price not known in state Initial
flutter: [INFO] TIME: 2024-03-25T14:21:05.584896Z r: Updated order state new_state: Failed,order_id: 8aa7b627-79c3-4571-90b1-a4e8dcfefe62
flutter: [ERROR] TIME: 2024-03-25T14:21:05.632909Z Failed to submit order: FfiException(RESULT_ERROR, Failed to post order to orderbook: HTTP status client error (400 Bad Request) for url (http://127.0.0.1:8000/api/orderbook/orders), null)
```
