### ISSUE TITLE
Cannot trade due to `Max quantity is 0`

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#2353]
With a fresh regtest setup, having funded coordinator and app, I am unable to trade. Perhaps the error is transient, but the error message I get is not very helpful.

![image](https://github.com/get10101/10101/assets/9418575/e0f9f6ac-9cc3-49f1-b5a6-0428e8d71e25)

**Comment by luckysori** [comment]
I guess you might know more about this, @holzeis. I am going to bed now, hopefully you can reproduce it too.

**Comment by holzeis** [comment]
@luckysori I am not able to reproduce this. Is this happening permanently for you or only occasionally?

**Comment by luckysori** [comment]
> @luckysori I am not able to reproduce this. Is this happening permanently for you or only occasionally?

This happens all the time for me. Removing the check in the frontend solves the problem for me.

**Comment by holzeis** [comment]
> > @luckysori I am not able to reproduce this. Is this happening permanently for you or only occasionally?
> 
> This happens all the time for me. Removing the check in the frontend solves the problem for me.

that's weird.. we will have to look at your setup to check what is going wrong..

**Comment by bonomat** [comment]
I was able to reproduce this after rebasing onto latest master: 

1. `just wipe`
2. `just docker`
3. `just coordinator`
4. `just fund`
5. `just run`
6. try opening a position.

**Comment by holzeis** [comment]
> I was able to reproduce this after rebasing onto latest master: 
> 
> 
> 
> 1. `just wipe`
> 
> 2. `just docker`
> 
> 3. `just coordinator`
> 
> 4. `just fund`
> 
> 5. `just run`
> 
> 6. try opening a position. 
> 
> 

That would be the expected behaviour if you did not fund the wallet.
