### ISSUE TITLE
Missed async match leads to expired position to be not removed

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2361]
When a position expires the user gets a web socket notification containing the async order that will be created in the order history. As the protocol moves on the async order will eventually be set to filled when the protocol finishes and the position gets removed.

It appears the user managed to open the app and connect to the p2p endpoint, which triggered the closing of the expired position. However, before the app was able to receive the async match notification, the app was closed again. Upon opening the app again, the dlc protocol continued and succeeded. But the position remained.

```
Failed to process incoming DLC message: No order to mark as Filled
```

|	|	|	|
|:-:|:-:|:-:|
|![IMG_0455](https://github.com/get10101/10101/assets/382048/810da5ce-405f-4a2b-aa86-6c402ed7c73c)|![IMG_0454](https://github.com/get10101/10101/assets/382048/d1dac4db-d80d-4bd9-ab74-e1c3106b647a)|![IMG_0453](https://github.com/get10101/10101/assets/382048/7d1f8f76-475a-4513-9944-658ce74c9af6)|

**Comment by luckysori** [comment]
I think this should be fixed by having positions that are based on `rust-dlc` `Contract`s. If the `Contract` is not "active", the position should not appear open.

**Comment by bonomat** [comment]
related to #2476
