### ISSUE TITLE
Show better error message when opening a position while channel is in closing

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2367]
At the moment the user gets this message, which is not very helpful.

![image](https://github.com/get10101/10101/assets/382048/4e0cea0c-6f8a-420f-b882-1f19997f9570)

**Comment by luckysori** [comment]
I think the error message is okay, but maybe we could let the user open a new position/channel. After all, the other channel is already gone.

**Comment by bonomat** [comment]
@luckysori thinks: we should allow users to trade while a channel is in closing.

**Comment by bonomat** [comment]
Replaced by https://github.com/get10101/10101/issues/2383
