### ISSUE TITLE
Opening a new position sometimes takes unacceptably long with very weird behavior. 

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#2377]
Look at the video, something is not right. 

https://github.com/get10101/10101/assets/224613/bf0f9cb6-2ce1-4871-b1d7-0632a239c369

[2024-04-09_122223.log](https://github.com/get10101/10101/files/14912705/2024-04-09_122223.log)

**Comment by bonomat** [comment]
I'll add critical because I believe a normal user would have closed the app already.

**Comment by holzeis** [comment]
Looks like you are losing the connection in between. Otherwise you wouldn't see the catch up dialog.

**Comment by holzeis** [comment]
related to https://github.com/get10101/10101/issues/2089

**Comment by bonomat** [comment]
> Looks like you are losing the connection in between. Otherwise you wouldn't see the catch up dialog.

But there is no reason for me to lose connection.

**Comment by holzeis** [comment]
> > Looks like you are losing the connection in between. Otherwise you wouldn't see the catch up dialog.
> 
> But there is no reason for me to lose connection.

Can you maybe add the relevant logs when you opened the position?

**Comment by bonomat** [comment]
Related to https://github.com/get10101/10101/issues/2415

**Comment by bonomat** [comment]
Looks like I'm in a broken state now :(: 

on my side I see this: 


> [WARN] TIME: 2024-04-16T11:00:59.179567Z r: dlc_manager::manager: Dlc channel timed out in State SettledAccepted { counter_next_per_update_point: PublicKey(6ff23dbe7ab0aeb721b6d22062e325b66e4a69516c7abbd6fbd6c23f3b9df01077b7bfdf4d4f5cb0497019453149cdfe202373cc62826f241fab423ced31d96f), own_next_per_update_point: PublicKey(e716c65c283c1c0ba6c2ccb176e6e00cb278ae1dbe70df25a62432627d9fcdfdd3c54d4451e1407be0b18238bd6d56b97061a5281448790914b280b48498e8b2), own_settle_adaptor_signature: EcdsaAdaptorSignature(02d72a6ebcf0b2e6a311e0b7286595d5b1e93a4ad8b068a4e59bb19be5a6d15eb503a88bea00c3b70612981488021d69f47ee965c9d04fea7554556f2ab74834033ac5783da03473c03e18005aaad3e9996d9fa48cc26cb0e628f7ba0829156535ad5d1558a4f851b945128dcc7966b9aa99396f76528d3e7178c38f9ab8b1aa816308c859936af606a66110fdf659e6508e2c6e1ccc0e098d340f40038f73fc378e), settle_tx: Transaction { version: 2, lock_time: PackedLockTime(0), input: [TxIn { previous_output: OutPoint { txid: dc21b526971e07b77637ab38aa811a24be12aaab5bae6c1d11eae813aecbb01d, vout: 2 }, script_sig: Script(), sequence: Sequence(4294967295), witness: Witness { content: [], witness_elements: 0, last: 0, second_to_last: 0 } }], output: [TxOut { value: 1586053, script_pubkey: Script(OP_0 OP_PUSHBYTES_32 9a3a48d1d9d001cacf40e5e26f3abfd77b28259ed99f893376cc07433e854bc1) }, TxOut { value: 1336598, script_pubkey: Script(OP_0 OP_PUSHBYTES_32 86d426dd1c9ab0e1ef6379659fdb6f0962920c8fab8eda5b252d52992da1d8a0) }] }, timeout: 1713256707, own_payout: 1334078, counter_payout: 1583533 }. Skipping force-closure of dlc channel 



[2024-04-16_210102.log](https://github.com/get10101/10101/files/14995831/2024-04-16_210102.log)

**Comment by bonomat** [comment]
> Looks like I'm in a broken state now :(:
> 
> on my side I see this:
> 
> > [WARN] TIME: 2024-04-16T11:00:59.179567Z r: dlc_manager::manager: Dlc channel timed out in State SettledAccepted { counter_next_per_update_point: PublicKey(6ff23dbe7ab0aeb721b6d22062e325b66e4a69516c7abbd6fbd6c23f3b9df01077b7bfdf4d4f5cb0497019453149cdfe202373cc62826f241fab423ced31d96f), own_next_per_update_point: PublicKey(e716c65c283c1c0ba6c2ccb176e6e00cb278ae1dbe70df25a62432627d9fcdfdd3c54d4451e1407be0b18238bd6d56b97061a5281448790914b280b48498e8b2), own_settle_adaptor_signature: EcdsaAdaptorSignature(02d72a6ebcf0b2e6a311e0b7286595d5b1e93a4ad8b068a4e59bb19be5a6d15eb503a88bea00c3b70612981488021d69f47ee965c9d04fea7554556f2ab74834033ac5783da03473c03e18005aaad3e9996d9fa48cc26cb0e628f7ba0829156535ad5d1558a4f851b945128dcc7966b9aa99396f76528d3e7178c38f9ab8b1aa816308c859936af606a66110fdf659e6508e2c6e1ccc0e098d340f40038f73fc378e), settle_tx: Transaction { version: 2, lock_time: PackedLockTime(0), input: [TxIn { previous_output: OutPoint { txid: dc21b526971e07b77637ab38aa811a24be12aaab5bae6c1d11eae813aecbb01d, vout: 2 }, script_sig: Script(), sequence: Sequence(4294967295), witness: Witness { content: [], witness_elements: 0, last: 0, second_to_last: 0 } }], output: [TxOut { value: 1586053, script_pubkey: Script(OP_0 OP_PUSHBYTES_32 9a3a48d1d9d001cacf40e5e26f3abfd77b28259ed99f893376cc07433e854bc1) }, TxOut { value: 1336598, script_pubkey: Script(OP_0 OP_PUSHBYTES_32 86d426dd1c9ab0e1ef6379659fdb6f0962920c8fab8eda5b252d52992da1d8a0) }] }, timeout: 1713256707, own_payout: 1334078, counter_payout: 1583533 }. Skipping force-closure of dlc channel
> 
> [2024-04-16_210102.log](https://github.com/get10101/10101/files/14995831/2024-04-16_210102.log)

I've rolled back my channel state and was able to close the position. Thanks @luckysori for the hand holding.

**Comment by bonomat** [comment]
For debugging: 

check the `DLC_Messages` table for how long does it take from start to end.

**Comment by bonomat** [comment]
Updated logs from closing the position just now

[2024-04-24_112613.log](https://github.com/get10101/10101/files/15084742/2024-04-24_112613.log)
