### ISSUE TITLE
Referent does not get Referral bonus after 3 active referrals

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2407]
1. Refer another wallet so this will get the Referent bonus
2. From the referent wallet refer additional 3 wallets and trade.

### Expected behaviour

Referent wallet should get the Referral bonus of 20%

### Actual behaviour

Referent remains with the Referent bonus of 10%

![image](https://github.com/get10101/10101/assets/382048/d40a25e8-9a08-4d68-b847-5553237ab3d5)

**Comment by bonomat** [comment]
I'm happy to change this but it was by design (removed bug): 

https://github.com/get10101/10101/blob/8c46fb0fbe00bcc6eb58071f13d5bd11b41dab6d/coordinator/src/referrals.rs#L90-L103

**Comment by holzeis** [comment]
> I'm happy to change this but it was by design (removed bug-label): 
> 
> https://github.com/get10101/10101/blob/8c46fb0fbe00bcc6eb58071f13d5bd11b41dab6d/coordinator/src/referrals.rs#L90-L103
> 

So it was a design bug then 😉
