### ISSUE TITLE
Rollover on regtest app took more than 30 seconds

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2415]
This is additionally bad, because we show the rollover as failed after 30 seconds.

We should at least not show a failed state but simply show the close button if the state does not change after 30 seconds.

**Comment by bonomat** [comment]
Very likely related to #2377

**Comment by holzeis** [comment]
We should probably change the rollover dialog to not show an error if the dialog times out.

**Comment by holzeis** [comment]
Most likely fixed with https://github.com/get10101/rust-dlc/pull/17
