### ISSUE TITLE
Initiate the dlc channel setup from the coordinator

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#243]
I've updated the diagram according to our discussion this morning. Note, due to the additional `Confirm` message that was originally not reflected in the diagram, the trade would have had the last word in the dlc channel creation. As a consequence the Coordinator needs to initiate the trade. This will also allow us to simplify things, as the coordinator is now really in control of coordinating the trade.

However, we need to provide the matched order details to the trader, simply open a dlc channel with out order context is not sufficient. This is not reflected in the diagram yet.

```mermaid
sequenceDiagram

participant m as Maker
participant c as Coordinator
participant o as Orderbook
participant t as Taker

m ->> o: create limit order

t ->> o: market order
o -->> o: match maker and taker

o ->> c: execute match

par Coordinator to Taker
    c ->> t: Propose DLC channel open
    t -->> c: Accept
and Coordinator to Maker
    c ->> m: Propose DLC channel open
    m -->> c: Accept 
end

par Coordinator to Taker
    c ->> t: Confirm
and Coordinator to Maker
    c ->> m: Confirm
end


Note over m,t: ...time flies when making money....

m ->> o: create limit order

t ->> o: "reversed" market order
o -->> o: match maker and taker

o ->> c: execute match

par Trader to Coordinator

c ->> t: Propose DLC channel close
t -->> c: Accept 
and Maker to Coordinator

c ->> m: Propose DLC channel close
m -->> c: Accept 
end

par Coordinator to Taker
    c ->> t: Confirm
and Coordinator to Maker
    c ->> m: Confirm
end
```

Side note, in the diagram, below we are automatically closing the position with the maker. This is fine for the MVP purpose, but post MVP we could find another match taking the original limit order from the maker so that we don't have to close the dlc channel with the maker.

_Originally posted by @holzeis in https://github.com/get10101/10101/issues/181#issuecomment-1461622475_

**Comment by 1010Tom** [comment]
resolved in #249
