### ISSUE TITLE
Seedphrase : UI problem

### ISSUE THREAD

**Issue by SXBT69** [get10101/10101#2443]
Reported by a user:
<img width="200" alt="image" src="https://github.com/get10101/10101/assets/137571657/86c70e2f-2a71-43b8-86b3-7e2e8d5f15b5">
Xiaomi Poco X4 GT
2460 x 1080

**Comment by pythcoiner** [comment]
got the same on pixel 7a

**Comment by Restioson** [comment]
In this case we are referring to the numbers being split across the lines, right? I think this is related to #1933 in that case.

**Comment by Restioson** [comment]
Nevermind, this is not related. The text simply isnt taking up enough space
