### ISSUE TITLE
Cannot acces orderbook

### ISSUE THREAD

**Issue by pythcoiner** [get10101/10101#2446]
loop spinning here:

![image](https://github.com/get10101/10101/assets/124568858/1d5c278d-d6f0-4d17-bbf9-962cd82b4f4b)

![image](https://github.com/get10101/10101/assets/124568858/34b1e08d-4b8b-498e-8b43-de22def1653c)

[app-arm64-v8a-full-release.apk](https://github.com/get10101/10101/releases/download/2.2.0/app-arm64-v8a-full-release.apk) on GrapheneOS

**Comment by bonomat** [comment]
Thanks for reporting @pythcoiner . 
Do you use some form of firewall or VPN? It looks like you are constantly dropping connections. 
In your logs I can see things like: 

> [DEBUG] TIME: 2024-04-17T13:15:06.877017Z r: Connection lost; reconnecting peer: tcp://022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156@46.17.98.29:9045,reconnect_interval: 1s
[WARN] TIME: 2024-04-17T13:15:06.878610Z r: Orderbook WS stream closed with error error: IO error: Software caused connection abort (os error 103)

> [ERROR] TIME: 2024-04-17T13:15:06.871999Z r: Failed to update fee rate estimates: error sending request for url (https://mempool.space/api/v1/fees/recommended): error trying to connect: Software caused connection abort (os error 103): error trying to connect: Software caused connection abort (os error 103): Software caused connection abort (os error 103): Software caused connection abort (os error 103) 

> [WARN] TIME: 2024-04-17T13:20:58.096456Z r: Connection failed: Failed to connect to peer: tcp://022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156@46.17.98.29:9045: deadline has elapsed; reconnecting peer:

**Comment by pythcoiner** [comment]
using orbot system wide

**Comment by pythcoiner** [comment]
just checked the logs now (app running since i hit the bug), no `Connection lost` from hour, i think the `Connection lost` i trigger when i tryed to change orbot `identity`

**Comment by pythcoiner** [comment]
but something looks weir to me (without take a look at the codebase is the large amount of `Could not remove non-existing order`

**Comment by bonomat** [comment]
> Could not remove non-existing order

I've created a separate ticket for this. In your case this error comes likely from not being able to receive the orders but you do receive the request to delete outdated orders - which is weird.

**Comment by bonomat** [comment]
I think we can close this ticket now. 
The source of this problem is Orbot which seemingly doesn't allow our requests to get through. 
In the future I'd love to support Tor out of the box, but for now this is not in scope.
