### ISSUE TITLE
LSP Fees

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#245]
The coordinator should charge a fee for the provided liquidity

* The fee is supposed to be charged as fraction of the quantity.
* This fee is charged independent of the trade setup; i.e. it's a separate payment and not reflected in the `Trade` model. 
* Initially, there is no enforcement to pay the matching fee, but clients are trusted to pay.

<details>
<summary>Outdated</summary>
**Scope of this ticket:**

- The client (i.e. the app / a potentially automated market making software) have to know the fee parameters up front. This includes the fee rate and how the fee is supposed to be payed.
    - Endpoint on the `Orderbook` so that the client can query what the "fee rate" of the orderbook is (initially we could also hardcode that, but it might be better to build that in configurable from the start)
    - Endpoint on the `Orderbook` to be able to generate an invoice that can be paid by the client.
- Query the rate, calculate the fee and display  the fee in the app when creating an order
- When a trade is being "set up" a client (the app and potential automated market makers) have to ensure to pay the orderbook matching fee. This is triggered as separate payment to the orderbook.
- On the client we have to associate the fee payment (a separate Lightning payment to the orderbook) with the trade / order after it was paid, so we can display this fee associated to the order / trade in the wallet history.
- Ensure that the coordinator opens a channel with the orderbook initially, so that payments from client to orderbook can be routed.

**Can be done outside of the MVP scope:**

- The orderbook should keep track of fees being paid for matches and potentially ban users if they don't pay

</details>

**Comment by bonomat** [comment]
I made a small adjustment: 

the fee is paid on the `quantity`, i.e.
for a taker fee of `0.3%` and a maker fee of `0.15%`, if a trader goes `$100` long with leverage of `2` at the price of `$20,000/BTC` the fee will be: 

- for a taker: `$0.3` worth of BTC at the price of `20,000` => 1,500 SATS
- for a maker: `$0.15` worth of BTC at the price of `20,000` => 750 SATS

**Comment by holzeis** [comment]
❓

Will the orderten get paid over  the coordinator? 

Will the orderbook eventually have a lightning channel with the coordinator or will the coordinator manage the orderbooks wallet?

🤔 if the coordinator would tale care of the fee payments we could include the payment into our protocol, meaning that we will not confirm the trade unless the fees have been paid. However, if we let the coordinator manage the fees we might not get the fiscal separation that we wanted of these two components.

**Comment by bonomat** [comment]
> 🤔 if the coordinator would take care of the fee payments we could include the payment into our protocol, meaning that we will not confirm the trade unless the fees have been paid. However, if we let the coordinator manage the fees we might not get the fiscal separation that we wanted of these two components.

This is true but we want to avoid this. 

> ❓ I am wondering if separating the coordinator and orderbook is really a good idea. Respectively if the trader initiated flow will fit to that fee flow.

Let's keep the separation for now and revisit in 3 months. 

> ❓ I guess it also goes into the question what the orderbook charges for. Would we also charge the trader if the match turns out not to be working? E.g. one side is not accepting. If not we would need more coupling between the coordinator and the orderbook, which leads to the original question. 😅

Then let's just not fail during the execution ;)

**Comment by luckysori** [comment]
What do we think about this now? @bonomat @da-kami @holzeis

**Comment by bonomat** [comment]
> What do we think about this now? @bonomat @da-kami @holzeis

I've updated the description slightly. I think it has a high priority to start charging fees.

**Comment by bonomat** [comment]
Sounds like a duplicate to #577
