### ISSUE TITLE
Custom fee not used for build spend tx

### ISSUE THREAD

**Issue by pythcoiner** [get10101/10101#2451]
There is a mismatch between custom fees selected and fees used for build the Tx

![image](https://github.com/get10101/10101/assets/124568858/196a9132-0175-4d5f-8f1b-b7da9ff65de7)

![image](https://github.com/get10101/10101/assets/124568858/13ba1f22-8e39-4624-aa8c-e86dc10958d7)

Pixel 7a w/ 2.2.0 app

**Comment by pythcoiner** [comment]
it looks too me the 1 sat is a display but as i got the same if if select high/medium fee

**Comment by luckysori** [comment]
Thanks for your report again, @pythcoiner.

This is indeed a bug. We were tracking this here: https://github.com/get10101/10101/issues/2196.

> it looks too me the 1 sat is a display bug as i got the same if i select high/medium fee

I agree with you that this is just a display bug. Nevertheless, I am working on a fix.

**Comment by luckysori** [comment]
@pythcoiner:

We've just merged https://github.com/get10101/10101/pull/2491, which fixes this bug. The bug fix should come with the next version after 2.2.3.
