### ISSUE TITLE
Do not allow user to spend more fees than the amount send when spending onchain

### ISSUE THREAD

**Issue by pythcoiner** [get10101/10101#2452]
As the default amount to send is 1000 sats (what is the rationnale behind this?) if user want sweep wallet but forgot to click on `max` (because he upset many fail prior to this one :grin:) the app let him spend way more fees than the 1000 sats...

**Comment by luckysori** [comment]
You are absolutely right, @pythcoiner. The app should prevent you from producing a transaction with a fee that is bigger or comparable to the send amount.

> As the default amount to send is 1000 sats (what is the rationnale behind this?)

This is an arbitrary default. I think we should remove the default and force the user to either specify an amount or click `max`.
