### ISSUE TITLE
Inverse payout curve

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#250]
With https://github.com/get10101/10101/pull/228 we've introduce the close position feature leveraging the `rust-dlc` implementation of the linear payout curve. However, for our btcusd trading pair this payout curve is not correct and should be replaced with an inverse payout curve.

**Comment by bonomat** [comment]
Update, we can use the `PolynomialPayoutCurvePiece` and just put our own value in. The algorithm will then ensure that the steps are linear but that's ok.

This is what I got:


## Our current payout curve

![Image](https://github.com/get10101/10101/assets/224613/563e8f7b-9f43-46db-bfad-f6b220babd80)


## How it should look like with a step function of 1



![Image](https://github.com/get10101/10101/assets/224613/10e66a0d-b811-466a-a999-efb3c134148d)

## How it looks like filled into the `PolynomialPayoutCurvePiece`



![Image](https://github.com/get10101/10101/assets/224613/5d16cee0-2b77-4d9f-b9b8-63d8bfbcde6b)

The number of steps is currently ~350 which was feasible to execute on the simulator.
