### ISSUE TITLE
`Pending` dialog opens when navigating to settings

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#2506]
When navigating to settings randomly the `Pending` dialog popped up: 

![image](https://github.com/get10101/10101/assets/224613/4134729c-11e5-45d7-be41-83dad9c3d6cd)

**Comment by bonomat** [comment]
cc @holzeis : same behavior as in the demo yesterday

**Comment by holzeis** [comment]
Can you share the logs? I wasn't able to reproduce this yesterday.

**Comment by holzeis** [comment]
Did it happen on the test app or in the dev setup?

**Comment by bonomat** [comment]
> Did it happen on the test app or in the dev setup?

it was locally in an simulator. I'm afraid I deleted the app right away because I was testing something else :/

**Comment by holzeis** [comment]
> > Did it happen on the test app or in the dev setup?
> 
> it was locally in an simulator. I'm afraid I deleted the app right away because I was testing something else :/

I tried to reproduce this yesterday and figured it might have been some quirk due to a hot reload / restart. Did you do something like that?

**Comment by bonomat** [comment]
> I tried to reproduce this yesterday and figured it might have been some quirk due to a hot reload / restart. Did you do something like that?

A definite yes 😅

**Comment by bonomat** [comment]
Reproduced on our regtest VM:

1. open a new channel and position
2. try to close it: get an error that the channel has not been confirmed yet
3. navigate to settings and see dialog

![image](https://github.com/get10101/10101/assets/224613/3da5f134-e194-4ced-b7f9-2a47111d8022)
