### ISSUE TITLE
Limit orders

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#2510]
Related to #2171

**Comment by bonomat** [comment]
To be fleshed out. 

Some thoughts: the user needs to be online to execute the limit order.

**Comment by bonomat** [comment]
Notes on limit orders: 

A limit order executes at the specific price set by the trader or a better price if available in the orderbook, meaning, there are two scenarios: 

1. If the limit order is not immediately executed, then the trader pays the maker's order matching fee, once a match is found
2. If there is already a better price in the orderbook, then the limit order executes at the best price and the trader pays the taker's order matching fee

In some exchanges, it is common to have a `post only` limit order: 
Post-only limit orders are orders where traders specify a limit price but only want their order to be added to the orderbook and not executed immediately. If the order would execute immediately, it's typically rejected.

**Comment by holzeis** [comment]
depends on #2270
