### ISSUE TITLE
Trading view is reloaded when switching between tabs

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2525]
https://github.com/get10101/10101/assets/382048/8f0f9fad-19a7-4484-ac24-294ab7ca1585

**Comment by bonomat** [comment]
@Restioson do you want to look into this?

**Comment by Restioson** [comment]
I can; I'm not so sure I'd classify this as a bug though as it's just default flutter behavior I am pretty sure. Maybe a UX bug if switching screens is a very common task

**Comment by luckysori** [comment]
> I can; I'm not so sure I'd classify this as a bug though as it's just default flutter behavior I am pretty sure. Maybe a UX bug if switching screens rapidly is a very common task 

It's very noticeable unfortunately. I think we should prioritise this.
