### ISSUE TITLE
The back button brings you back to the channel configurator even if the order has been successfullly executed.

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2569]
The back button doesn't really make sense when the order got executed.

https://github.com/get10101/10101/assets/382048/eb8d3cd9-ea98-49e4-a03b-3ac821f15e04

**Comment by holzeis** [comment]
@bonomat @luckysori @SXBT69 How about automatically navigating to the trade screen when the order got executed successfully?

**Comment by bonomat** [comment]
> @bonomat @luckysori @SXBT69 How about automatically navigating to the trade screen when the order got executed successfully?

I wanted to navigate to the trade screen when clicking on the button in the confirmation dialog, but I failed doing so.
