### ISSUE TITLE
Run Clippy CI job for each crate separately

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#257]
Otherwise we don't know if our crates build in isolation.

This can be annoying locally, as you can encounter unexpected build errors caused by missing dependency features.

This is how we solved the problem in ItchySats: https://github.com/get10101/itchysats/pull/1333.

**Comment by luckysori** [comment]
To be fair this is not crucial as long as we run something like `cargo hack check --all` locally every now and then.

**Comment by klochowicz** [comment]
can't we use `just clippy` for this?

**Comment by luckysori** [comment]
> can't we use `just clippy` for this?

Do you mean the current command or the `justfile` in general?

We could write the script that builds each crate separately in the `justfile` and use it on CI, sure.
