### ISSUE TITLE
Position margin disagrees with close margin after clicking `Close Position` button

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#2577]
![image](https://github.com/get10101/10101/assets/9418575/04c8a350-06a4-4e9c-8a1c-1487737c2624)

## Repro

- Open $100 long position with e.g. 5,000 sats margin.
- Press `Close Position` button.
- The margin row will show a margin that does not match 5,000 sats. Instead, it will be equivalent to the margin for _opening_ a new $100 short position, which is different because the bid and ask prices are normally different.

Interestingly, this is fixed if you toy around with resizing the position first. Although we then display `Margin 0 sats`:

![image](https://github.com/get10101/10101/assets/9418575/0525f9f2-cbbe-4aef-8e5a-c594d5951da3)

It would make sense to not display the margin row when closing positions.

**Comment by Restioson** [comment]
@holzeis: if you'd like I can take it over?

I would implement it by not showing the margin as @luckysori suggested, as it seems the simplest option (unless we have a reason to show the margin)

**Comment by holzeis** [comment]
Go for it 👍
