### ISSUE TITLE
CD to Android Firebase App Distribution

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#29]
When creating a release a new version of our app should be pushed to [Android's Firebase App Distribution](https://firebase.google.com/docs/app-distribution).

**Comment by holzeis** [comment]
why not [Google Play Console](https://developer.android.com/distribute/console)?

**Comment by bonomat** [comment]
Afaik firebase is for testing and google play store for production. I would have gone first for testing and then for production CD later on.

**Comment by holzeis** [comment]
I mean google play **console** not the store.

**Comment by holzeis** [comment]
hmmm.. I thought the google play console was the android analogy to test flight.

**Comment by bonomat** [comment]
Isn't Google Play Console just the management interface behind Google Play, same as AppStore Connect is for Apple's AppStore?

**Comment by holzeis** [comment]
After a quick chat with chat gpt, it seems you can you google play console also for publishing test apps.

> Alpha and Beta testing: You can set up an alpha or beta testing program for your app on Google Play Console. This allows you to invite a select group of testers to try out your app before it is released to the general public.

**Comment by bonomat** [comment]
Android is not in focus for now
