### ISSUE TITLE
Create a testflight release

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#293]
Release the version to be used for the user interviews to TestFlight.

Side note: We will need to invite our users as testers to TestFlight so they can download and test the app.

**Comment by holzeis** [comment]
@bonomat @da-kami @klochowicz @luckysori I checked with my interviewee and he is on ios so I am fine with just releasing to TestFlight, but it might not apply for your interviewees. If the they are on Android, we will need to build an additional release for Android.

**Comment by bonomat** [comment]
@klochowicz and me spent some time on trying to get a the shared apple id working but can't. For the time being @bonomat is the only one who can publish to testflight.

**Comment by bonomat** [comment]
> Side note: We will need to invite our users as testers to TestFlight so they can download and test the app.

yes, they will need to share their apple id/email with us
