### ISSUE TITLE
Can't create invoice on phone

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#298]
If I deploy latest `main` on the phone  via `testflight` I can't get past creating an invoice. 
When clicking the button nothing happens. 

The settings seem to be correct:

![image](https://user-images.githubusercontent.com/224613/226517198-4a596f2f-9539-4e30-976d-ec298d2bb07f.png)

**Comment by holzeis** [comment]
I noticed that it sometimes takes quite some time to get a response from our vm. When I tested it, it took about 5 seconds before I got the fake scid.

**Comment by bonomat** [comment]
> I noticed that it sometimes takes quite some time to get a response from our vm. When I tested it, it took about 5 seconds before I got the fake scid.

I can confirm that it is not a timing issue. I'm keeping the app open and nothing happens

**Comment by holzeis** [comment]
@bonomat Did the permissions really fix the issue? It was just an assumption as I couldn't test it. Please reopen if this ticket is not fixed yet.
