### ISSUE TITLE
Use payout calculation when calculating close position trade amount in TX history

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#311]
At the moment we use the margin calculation, which is incorrect because it doesn't include the PNL.

See: https://github.com/get10101/10101/pull/307#discussion_r1144213133.

**Comment by holzeis** [comment]
@luckysori is this a duplicate of #301 ?

**Comment by luckysori** [comment]
It's similar but this one was just meant for displaying in the transaction history. I'll make that clearer.

**Comment by da-kami** [comment]
We should be able to use the `payout` function that will be introduced in https://github.com/get10101/10101/pull/305
