### ISSUE TITLE
Fix pull-down refresh for the wallet 

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#313]
We have the possibility to trigger a refresh in Dart, so we can actually add this feature easily.

**Comment by holzeis** [comment]
This is already working in case the screen gets scrollable (that is happening when we have enough transactions in the wallets history).

However, if the screen is not scrollable we can't refresh. (pull down gesture)

**Comment by bonomat** [comment]
Unassigned @da-kami because he is on leave currently
