### ISSUE TITLE
FlutterRustBridgeBase should be singleton

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#315]
I've noticed the following line in our logs: 

```
Error: Exception: Subclasses of `FlutterRustBridgeBase` should be singletons - there should not be two instances (runtimeType=NativePlatform) 
```

Looks like a bug to me.

**Comment by klochowicz** [comment]
It's a bug in the flutter rust bridge, but seems easy to fix: https://github.com/fzyzcjy/flutter_rust_bridge/issues/1025

**Comment by klochowicz** [comment]
@bonomat did you get this error on macOS or iOS?

**Comment by bonomat** [comment]
> @bonomat did you get this error on macOS or iOS?

it was on iOS
