### ISSUE TITLE
App received all orders from orderbook even though it already had some orders

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#323]
I ran into this on iOS:

```
2023-03-23 14:12:49.016 | LogLevel.WARNING | Received all orders from orderbook, but we already have some orders. This should not happen 
```

**Comment by klochowicz** [comment]
This would have come if the websocket stream got broken & reestablished. After we get this message we swap all orders we had previously with new list of initial orders - and then proceed to accumulate deltas.

I'm happy to downgrade this to debug and make it less scary :)

**Comment by luckysori** [comment]
> This would have come if the websocket stream got broken & reestablished. After we get this message we swap all orders we had previously with new list of initial orders - and then proceed to accumulate deltas.
> 
> I'm happy to downgrade this to debug and make it less scary :)

Right, that makes sense. Downgrading and rewording this would be great, yeah.
