### ISSUE TITLE
We have a DLC but were unable to set the order to filled

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#336]
When opening a dlc from the phone, the filling order can not be found in the database. No other error messages were seen in the logs until the point where the order is fetched by state.

Note, this is only happening on the App released on TestFlight build 46 and is not reproducible on the simulator.

```
| 2023-03-27 13:59:57.455 | LogLevel.DEBUG | New message from orderbook 
| 2023-03-27 13:59:57.456 | LogLevel.INFO | Received match from orderbook 
| 2023-03-27 13:59:59.156 | LogLevel.INFO | Sent trade request to coordinator successfully 
| 2023-03-27 14:00:13.512 | LogLevel.DEBUG | Processing DLC channel message 
| 2023-03-27 14:00:13.534 | LogLevel.INFO | Accepting DLC channel offer 
| 2023-03-27 14:00:34.095 | LogLevel.DEBUG | Processing DLC channel message 
| 2023-03-27 14:00:34.256 | LogLevel.DEBUG | Sending DLC channel message 
| 2023-03-27 14:00:34.257 | LogLevel.ERROR | Critical Error! We have a DLC but were unable to set the order to filled: There is no order in state filled in the database 
```

**Comment by holzeis** [comment]
Note, build 47 does not run into this error. We should start to somehow map a commit to a build number. 😅 It's hard to track what changes are in a build version.

**Comment by holzeis** [comment]
Happened again on build 48

**Comment by klochowicz** [comment]
maybe we could push git tags for testflight builds? that would allow us to bisect bugs much easier. 
we can always remove these "ephemeral" tags when we get a bit more official release happening on TestFlight.

**Comment by bonomat** [comment]
> maybe we could push git tags for testflight builds? that would allow us to bisect bugs much easier. we can always remove these "ephemeral" tags when we get a bit more official release happening on TestFlight.

I don't think this concept exists on TestFlight. All you can do is define a version number.
