### ISSUE TITLE
The numbers don't add up: wallet history, position, balance

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#345]
There are multiple problems, I summarize them in this ticket for now because I am not sure if there is a relationship / dependency between some of the problems.  We can decide to split this into multiple tickets.

- While a position is open there are some additional "locked up funds" that are currently hidden. 
    - My understanding is, that these funds are for the worst-case scenario
    - These funds are not usable, i.e. they are not part of the usable balance. 
    - The wallet history does not show these fees at the moment.
    - I am not sure how we should display them; if the position is collaboratively closed these funds just go back to the user.
    - This is one aspect of being *self custodial* so we could highlight that these locked up "emergency" funds exist to see how users react.

- The PnL displayed on the position does not reflect the actual PnL of the position. 
    - Example: An `x2` long position with `1000` contracts that was just opened shows a `PnL` of `-438` sats. That's quite a big loss.
    - I don't think we can just blame this on the payour curve, because we actually just calculate the PnL now, and this calculation should be correct.
    - When we close the position the `PnL` is actually - as expected, given that the price did not really move - at abour `+/- 1` sat.
    - Somehow we must be using different values to calculate the `PnL`; this could be related to some additional "reserved" funds that are locked up

- After opening and closing one or multiple positions the balance does not add up
    - Somehow a few sats might get lost - is this just due to precision rounding errors?
    - The "fee" for opening the position is not reflected (I guess that is expected at the moment because the fee displayed is not actually charged yet. 
    - We have to evaluate where we are taking the numbers from - I think the balance is indisputable because it's coming from the node. How come that the items in the history don't reflect it?
    - Example:

![image](https://user-images.githubusercontent.com/5557790/228690067-4a994f90-3f9f-4135-9965-609ccec505ea.png)

`100,000 - 997 + 998 - 998 + 998 = 100,001`

Note: The initial funding transaction of `100,000` is missing in the list, because we don't persist the payment history yet.

**Comment by holzeis** [comment]
This ticket has been resolved with https://github.com/get10101/10101/pull/378
