### ISSUE TITLE
CI often hangs on `run-tests-ln-dlc-node` job

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#355]
We started seeing this on and off since [this run](https://github.com/get10101/10101/actions/runs/4444630040). We cannot associate it with a particular code change because it doesn't always happen.

It could be related to GitHub's infrastructure but I wouldn't know why.

I am not able to reproduce this problem locally.

**Comment by luckysori** [comment]
Interestingly, the previous PR triggered exactly the same tests (2 hours before this issue started affecting us) and they passed: https://github.com/get10101/10101/actions/runs/4570833858.

**Comment by luckysori** [comment]
Turns out it was just a transient problem with CI.

**Comment by luckysori** [comment]
We're actually still seeing this, but not necessarily with the same test: https://github.com/get10101/10101/actions/runs/4612585983/jobs/8153652603. I'm not sure what to do about this issue if it only happens sometimes.

**Comment by luckysori** [comment]
Re-opening as it keeps happening.

**Comment by luckysori** [comment]
[This CI run](https://github.com/get10101/10101/actions/runs/4619199701/jobs/8167629311) was automatically cancelled after 30 minutes given the changes in #371. We can see that the last test to reach completion was actually running until the very end, so there is a chance that we can debug this problem.

**Comment by klochowicz** [comment]
I wonder whether this would reproducible with https://github.com/nektos/act ?

**Comment by klochowicz** [comment]
I'll try to migrate our old setup for partitioned tests from ItchySats to see whether it will make a difference - it should be just copy-paste; it would certainly distribute test load, might as well give it a go.

**Comment by bonomat** [comment]
This keeps happening here as well: https://github.com/get10101/10101/pull/414#issuecomment-1508958660

**Comment by luckysori** [comment]
Definitely not fixed with f00ec25 unfortunately.

**Comment by luckysori** [comment]
I may have a new lead!

I randomly checked this run that failed because it was hanging and it's interesting because it hanged on _the very first test_ it tried to run. This means that we should be able to definitively determine where the test is hanging on CI (as far as the logs can provide context).

Here's the last interesting log message AFAICT: https://github.com/get10101/10101/actions/runs/5005062691/jobs/8968486859#step:8:249.

Here's the line where I think it hangs in the test (although it could possibly be the next time we call `process_incoming_messages`): 

https://github.com/get10101/10101/blob/f95de01215d915a67763b42737aa1e4d45d2dfe0/crates/ln-dlc-node/src/tests/dlc/collaborative_settlement.rs#L79

I've never been able to reproduce the test hang locally, but @da-kami thinks he has been able to and @holzeis has a suspicion that we might have seen this behaviour on our deployed coordinators too.

It's important to note that I am not sure if this problem is specific to this test or if it can happen for other tests. My guess is that it can happen for other tests too.

Assigning @klochowicz as he wants to look into it.

**Comment by luckysori** [comment]
We no longer see it after moving these test to a different job.

Whilst I'm not satisfied that moving the tests is a good fix, I'm convinced that the root cause was fixed with https://github.com/get10101/10101/pull/756.
