### ISSUE TITLE
Add e-mail signup page when starting the app

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#376]
Only for beta phase (so we can give feedback/support/understand the user).

Don't require confirming the email, a simple form validation (ie does this look like an email?) should be sufficient.

Also, I would strongly consider using NIP-5 as an alternative - it's about possibility to reach out to the users, not to know anything about them.

**Comment by holzeis** [comment]
How about the following flow.

1. The referral creates a referral link in the app.
2. The referral shares that link. (E.g. on twitter) promoting that you can be part of something great from the start and save trading fees.
3. The referred user opens the link on her phone - navigates to an enter your email wall.
4. The referred user enters her email address and receives the  TestFlight link via email.


Advantages:
- we don't have to add the email wall artificially to the app. Making it clear that such kind of requests are not part of the app.
- we only hand out an TestFlight download to a user who entered a real email address.
- we could create a ranked waiting list once we've reached our max available seats.
- this could be nicely combined with our questionnaire form. E.g. after providing the email address the user could be asked if she is willing to optionally take part of a survey.

**Comment by holzeis** [comment]
related to https://github.com/get10101/meta/issues/148
