### ISSUE TITLE
Remove orderbook fees for now

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#379]
remove hardcoded `30sats fees` and mention that while in beta we do not charge any orderbook fee.

Related:#224

**Comment by holzeis** [comment]
> remove hardcoded 30sats fees and mention that while in beta we do not charge any orderbook fee.

Small change to the text above. It's not that we don't charge because of beta, but as benefit of the referral program.

**Comment by klochowicz** [comment]
> 

I don't think that has anything to do with referral program? I know someone said something about referrals, but IMHO it doesn't add up.

**Comment by bonomat** [comment]
I would also go with the referral program: it sounds better if we say: you got referred by X, X gets Z sats and you have 0 trading fees.
