### ISSUE TITLE
Add sucess screen overlays after the user successfully finished certain actions

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#38]
Pattern: Once the user successfully did an action don't just modify the screen to show that something happened, but add an explicit success dialog that tells the user that:

* The action the user did was successful
* What is going to happen on the screen

Success Screens are needed for:

- Wallet: Fund/Receive 
- Wallet: Send/Withdraw
- Trading: Open Position
- Trading Close Position

Examples:

* Wallet Funding/Receive: should be some kind of waiting overlay that automatically closes once the incoming payment is detected or the user closes it
* Opening a position: success, your order has been submitted, your position will be opened once the order was filled (...)
* Closing position: success, you created and order to close your position, the position will be closed once the order was filled

**Comment by holzeis** [comment]
- [ ] Wallet: Fund/Receive
- [ ] Wallet: Send/Withdraw
- [ ] Trading: Open Position
- [ ] Trading: Close Position

**Comment by bonomat** [comment]
All done
