### ISSUE TITLE
Improve app splash screen

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#381]
- e.g. add a text: we are loading, please wait...
-  add Beta tag
- ~add a welcome wizard and load in the background~

**Comment by holzeis** [comment]
cc @bonomat

**Comment by bonomat** [comment]
> Btw, on my iPhone SE it now looks like this:
> 
> ![image](https://user-images.githubusercontent.com/9418575/231686326-5667f182-97c9-44b5-a31a-e0863cc959d8.png)
> 
> It didn't use to be zoomed in like that.

it's a feature 😬

**Comment by klochowicz** [comment]
that's not what I meant when I asked whether "we're gonna make it big" 😂

**Comment by holzeis** [comment]
is this really needed for MVP?

**Comment by klochowicz** [comment]
> is this really needed for MVP?

it's one of the tickets where arguing whether to keep it in scope is probably than fixing it. ;D

having it say
' please wait, loading....' and a 'BETA' tag somewhere is pretty low level.
