### ISSUE TITLE
Crunch the numbers

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#382]
- what is the smallest channel we can work with (in-bound and out-bound liquidity)
- Do we need a cap for referral payments because we cannot extend an existing channel?
- if we give the user 2k sats, can the user open a position or do anything?

**Comment by holzeis** [comment]
> Do we need a cap for referral payments because we cannot extend an existing channel?

I don't think we need an additional cap, as the channel already limits that. The transactions would simply go to failed, which I guess is ok. If the referral would start trading again and open up some inbound liquidity again we could continue sending her rewards.

**Comment by da-kami** [comment]
Conclusions from our talk just now:

1. Channel cap: 200k sats
    1. This is the channel cap for all initial 50 beta users on Testflight
    2. This is about 60$ (at current price), the user can use ~20$ for trading given the 1/3 to 2/3 split
2. Referral is 2k sats, meaning the user can top up with 1/3 of the channel, which means adding up to ~64,666 sats

![image](https://user-images.githubusercontent.com/5557790/231206591-94ef32f1-9194-4d63-88a8-1d4a9062a967.png)



Since the channel capacity is for all users in the beta program we should communicate that when users try to receive funds.

**Comment by da-kami** [comment]
Everything we need should be defined:

Channel capacity (fixed during beta): 200k
Maximum trading amount by user: 1/3 of channel size
Minimum trading amount by user: 1000 sats

Closing this ticket, if something is missing please re-open and state!

**Comment by da-kami** [comment]
Reopening because:

- What is the *minimum amount* that has to remain in the Lightning channel?

If we have 2k off-chain balance, we cannot use all of the 2k for trading, but some amount has to be set aside - what is that amount?

**Comment by da-kami** [comment]
Note: Currently the `sats/vbyte` is set to `2`, resulting in `833` fee-reserve.
I tested with the regtest setup with

`2833` initial balance, and traded `1000` sats and it worked:

 
<img width="406" alt="image" src="https://user-images.githubusercontent.com/5557790/231264562-1c29d8aa-80cd-49db-be16-3e1e4315e8eb.png">

<img width="406" alt="image" src="https://user-images.githubusercontent.com/5557790/231264720-03ec53e2-0953-45e0-ae22-48d54ca66504.png">

(I made 2 sats profit :)

**Comment by da-kami** [comment]
should be completed - all points will be worked in as part of working on #131 !
