### ISSUE TITLE
Show the expiry in the position and when creating an order

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#385]
e.g. 00:00 every day

**Comment by holzeis** [comment]
> e.g. 00:00 every day

As we want the user to come online at this time, I wouldn't go for a fixed time, but rather 24 hours after the order has been filled.

**Comment by bonomat** [comment]
> As we want the user to come online at this time, I wouldn't go for a fixed time, but rather 24 hours after the order has been filled.

I prefer a fixed time, we can then in the future use this moment in time to calculate funding rates and do the rollover.

**Comment by klochowicz** [comment]
the simplest way would be to align it with bitmex times - 8:00, 16:00, 0:00 UTC time; this is what users are used to.
