### ISSUE TITLE
Add the `fee-reserve` to the wallet history while position is open

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#392]
At the moment while a position we don't see see the reserved fees in the wallet history resulting in the entries not adding up to the balance (the fee-reserve of the position is missing).

This can look odd (below based on 2 sats/vbyte `833` are missing):

![image](https://user-images.githubusercontent.com/5557790/231268016-8193ed94-7eea-4ee6-be01-17af856251a0.png)

Note: We are changing the sats/vbyte to `4` instead of `2`, so the fee will be fixed at `1666`.

Since the fee-reserve is currently fixed we can easily add it as either a separate history entry; or we can add it as part of the opening wallet history entry. We should make it clear (some info button) that this fee is only temporary for the duration of the position being open and returned when closing the position.

**Comment by holzeis** [comment]
Closing this ticket as it has been resolved.

**Comment by bonomat** [comment]
> Closing this ticket as it has been resolved.

Has this been really resolved?

**Comment by da-kami** [comment]
No, it has not been resolved! Screenshot from latest `main` at `35a41b47766c5d17eba49892a7f01c98bfa88aa5`:

<img width="500" alt="image" src="https://github.com/get10101/10101/assets/5557790/c0cc8214-fd1d-4c42-856a-be88c719813a">


6000 - 153 - 1000 - 6 = 4841 

The displayed balance of `3175` does not take the reserve into account.

Note: I noticed that we also touched on this topic in https://github.com/get10101/10101/issues/224
I am not sure why we discussed this topic in https://github.com/get10101/10101/issues/224, I think the reserve is not a *fee*.
Repopening this ticket because I think it is relevant and can be actioned independent of https://github.com/get10101/10101/issues/224

**Comment by Restioson** [comment]
> Since the fee-reserve is currently fixed we can easily add it as either a separate history entry; or we can add it as part of the opening wallet history entry. We should make it clear (some info button) that this fee is only temporary for the duration of the position being open and returned when closing the position.

Do we think this should be a separate history item or rather as some fraction of the total sats as was discussed elsewhere (maybe not for this feature, though)? I wish I could remember where that mock was posted!

**Comment by holzeis** [comment]
we may not even subtract it from the balance at all, as its only theoretically locked. I talked with @bonomat about it the other day and I would even argue that we shouldn't change the wallet balance at all when we are opening a position (only for updating the amount according to the current pnl).

If the user would like to send some money out and this would include a money in an open position, I would simply ask if she wants to reduce / close her position to complete that transaction. On yes, we queue up a trade before paying the invoice.

**Comment by Restioson** [comment]
>  The user would like to send some money out and this would include a money in an open position, I would simply ask if she wants to reduce / close her position to complete that transaction.

I do think in this case that it should be portrayed in the balance as a non-liquid asset. I would expect, as a user, that the balance displayed is liquid and available and wouldn't require selling assets to use.

**Comment by holzeis** [comment]
Closing in favour of https://github.com/get10101/10101/issues/1496
