### ISSUE TITLE
Home screen flickers every few seconds

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#404]
https://user-images.githubusercontent.com/9418575/231685385-b0a96564-5fda-4d09-95c3-16b0b04e28d9.MOV

---

On iPhone SE.

**Comment by luckysori** [comment]
This is on my iPhone SE.

**Comment by holzeis** [comment]
This is still happening. I think the issue is coming from the way we are using the preferences indicating if a backup of the seed phrase has been created. Since we are not hiding the button anymore, we could simple remove corresponding code.
