### ISSUE TITLE
Include the `trades` inside `orders`

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#41]
On a high level your `orders` actually *define* your `trades` - One order can result in multiple trades.
This means we don't necessarily need a `trades` tab in the trading screen, but can just structure the orders to contain the trades.
This simplifies the user interface, because there is only `orders` and `positions` in the trading screen.

Scope: 

1. Remove the `Trades` tab
2. Change the `Order` entries in `Orders` tab to be more like a list view
3. When the user clicks on an `Order` the user gets a details view of the order: Design a details view of the order that shows the trades including the status of the order (filled = the order was completely executed by one or multiple trades, ...)

**Comment by bonomat** [comment]
Done, the idea is that one can swipe/click on the order tile and one will see the executed trades for this order: 

full order
<img width="519" alt="image" src="https://user-images.githubusercontent.com/224613/215390990-3ba8c6e5-f8dd-426d-9c6f-2c0d43dfb6c7.png">

trades (can be multiple)
<img width="504" alt="image" src="https://user-images.githubusercontent.com/224613/215391049-c0bc3138-cc94-4e3e-836e-5dc07fe5d670.png">
