### ISSUE TITLE
ADR for oracle choice

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#48]
We've decided to depend on `rust-dlc` (as opposed to e.g. a modified version of `maia`) and this means that we no longer have a library that supports Olivia by default. `rust-dlc` should support any oracle that conforms to `dlcspecs` and it provides an implementation of an oracle client that works with any instance of a [`p2pderivatives` oracle](https://github.com/p2pderivatives/p2pderivatives-oracle).

This leaves us 3 choices:

1. ~Stick to Olivia and modify `rust-dlc` to support its bespoke attestation scheme and API.~ (Olivia won't be maintained long term).
2. Use a public `dlcspecs`-compliant oracle, such as some of the ones listed here: https://oracle.suredbits.com/.
3. Run our own instance of the `p2pderivates` oracle to bootstrap our setup.

Let's document our choice in an ADR.

**Comment by holzeis** [comment]
@luckysori and I just looked over suredbits options and found that their services are currently unavailable. We are not sure if this is just a temporary thing or permanent. Trying to reach them on their slack channel, also failed as the link on their website has been expired.

We also figured out that their mainnet oracles are now paid services, which might be a blocker for our use case.

**Comment by bonomat** [comment]
Thanks for sharing. Let's run our own for the time being and see if we can outsource it later-on. Maybe cryptogarage or atomicfinance are keen on chiming in.

**Comment by holzeis** [comment]
> Thanks for sharing. Let's run our own for the time being and see if we can outsource it later-on. Maybe cryptogarage or atomicfinance are keen on chiming in.

see also https://github.com/get10101/10101/issues/92

**Comment by holzeis** [comment]
The p2p derivatives oracle is not intended for commercial use. It leverages the public api of [cryptocompare](https://www.cryptocompare.com/). Tibo suggested, if we want to use the p2p derivatives oracle, to integrate with another source for btcusd rates like bitmex or deribit. That would need to get implemented in [p2pderivates-oracle](https://github.com/p2pderivatives/p2pderivatives-oracle), but that should be rather straight-forward.
