### ISSUE TITLE
Order failed in the coordinator

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#480]
Could not open a new position

```
| 2023-04-21 09:43:42.522 | LogLevel.INFO | Updated order state new_state: Filling,order_id: 0522710a-8842-492b-a665-cdaa35af9a85 
| 2023-04-21 09:43:42.523 | LogLevel.DEBUG | Publishing event OrderUpdateNotification(Order { id: 0522710a-8842-492b-a665-cdaa35af9a85, leverage: 5.0, quantity: 1.495325, contract_symbol: BtcUsd, direction: Long, order_type: Market, state: Filling { execution_price: 29906.5 }, creation_timestamp: 2023-04-21 13:43:41.0 +00:00:00 })  
| 2023-04-21 09:43:43.539 | LogLevel.ERROR | Failed to execute trade for order Some(0522710a-8842-492b-a665-cdaa35af9a85): TradeResponse: Could not post trade to coordinator: {"error":"Could not handle trade request: Storage error Nonsense bytes didn't map to the type they were interpreted as"}  
| 2023-04-21 09:43:43.541 | LogLevel.INFO | Updated order state new_state: Failed,order_id: 0522710a-8842-492b-a665-cdaa35af9a85 
```

Investigating the coordinator side, more details coming

**Comment by luckysori** [comment]
Is this on `mainnet`?

The `mainnet` coordinator reports the same error when I try to list the DLC channels:

```
lucas@get10101-production ~ $ curl localhost:8000/api/admin/dlc_channels | jq .

{
  "error": "Failed to list DLC channels: Storage error Nonsense bytes didn't map to the type they were interpreted as"
}
```

**Comment by klochowicz** [comment]
Had the same issue on regrest. Can reproduce locally with the db I copied before wiping coordinator.

**Comment by luckysori** [comment]
There was at least [one breaking change in the serialisation of `SubChannel`s](https://github.com/p2pderivatives/rust-dlc/commit/adc7cef5650cbba56f869a275b7b0a273c414ef1#diff-98c1a2b50758c12662586ffc088a6113bf2e4635402d799164c78fdea0129628R175-R176) in the past few days and it's the likely cause of this error.

I think we:

- Created a DLC channel before the patch.
- Upgraded `rust-dlc` to a version that included the patch.
- Deployed a new version of the coordinator.
- Tried to load the DLC channel from the `sled` DB and encountered the error on deserialising the data.

---

Conversation with Tibo for context [here](https://matrix.to/#/!YOUZSBmuJuaGzmxzaA:matrix.org/$NvCwTq6pRQC3JIKoRA8qT1F5zh-AvoV2SMVxlcugrts?via=matrix.org).

**Comment by klochowicz** [comment]
We have found a way to circumvent breaking rust-dlc changes with https://github.com/get10101/10101/pull/514
kudos to @da-kami and @luckysori
