### ISSUE TITLE
Configure Android APK build and release action

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#496]
We should have a just command to build the APK.
We started with this here https://github.com/get10101/10101/pull/343 but due to re-prioritization it was never finished.

We should configure the APK release as part of the release action in GitHub.
In https://github.com/get10101/10101/pull/497 we deactivate the APK build because the artifact is not showing up in the release at the moment.

**Comment by holzeis** [comment]
I wouldn't release an apk but rather an android app bundle so we can use the analogue of apples TestFlight.
