### ISSUE TITLE
`Unrealised P/L` calculation seems weird

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#499]
With a position open, I see the BTC price moving up and down on the candlestick chart.
It doesn't seem to move at the same time as the unrealised P/L, which I find is a bit weird. 

example:
- I went long with x2 leverage
- it started with `-2` loss
- when the price went up, I got `-4` loss! 
- then the price went down, and it's still `-4` sats.

I suspect that this is due to the current best orders in the orderbook, but if we have the giant candlestick in front of the positions, it's hard not to pay attention to that.

When I closed, I got the predicted amount back, so at least it's consistent :)

**Comment by bonomat** [comment]
Unfortunately, the price in the candle stick chart is not related to the price you get in our orders.

**Comment by luckysori** [comment]
Do we want to action this or should we just close this? @klochowicz @bonomat

**Comment by bonomat** [comment]
One thing we could consider is changing the candle stick chart to 1m candles, because that's the rate our orders update. But I would not bother at the moment.
