### ISSUE TITLE
Model how receive funds via lightning without inbound liquidity

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#5]
We need to model a flow where the user receives funds but does not have inbound liquidity yet.

There are two possible ways: 
1. we ask the user upfront how much inbound liquidity he wants and charge him for that, e.g. when opening the channel, we say inbound liquidity costs 1%
2. we tell the user that an incoming payment above his inbound liquidity will always incure a fixed fee, e.g. 1%

Here is a little diagram showing the technical side of this: 

```mermaid
sequenceDiagram

participant D1 as "Daniel-10101"
participant T as "10101" 
participant B as "Breez"
participant D2 as "Daniel Breez"

D1 ->> D1: create invoice: 1k sats
D1 ->> D2: send invoice
D2 ->> D2: pay invoice

D2 ->> B: pay
B ->> T: pay
alt channel present and enough inbound liquidity
T ->> D1 : pay
else no channel present
T ->> D1: open channel: 1k sats
Note over T: 10101 opens channel with funding on 10101 side. \nThen pay invoice and funding ends on Daniel-10101 side
T ->> D1: pay: 
end
```

**Comment by 1010Tom** [comment]
This was feedback on the old prototype and is obsolete now.
