### ISSUE TITLE
Failed to build oracle client

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#504]
Build Number: 951
Build Version: 1.0.11

The app fails to initialize during the first startup as it fails to build the oracle client. It seems the oracle is not reachable, but testing locally everything seems to be working just fine.

```
| 2023-04-25 07:16:06.441 | LogLevel.INFO | Initialized logger  
| 2023-04-25 07:16:06.441 | LogLevel.INFO | App data will be stored in: Directory: '/var/mobile/Containers/Data/Application/B2DA67D3-6471-4B61-9A3F-D5F24A5EEEE8/Library/Application Support' 
| 2023-04-25 07:16:06.451 | LogLevel.DEBUG | Database migration run - db initialized  
| 2023-04-25 07:16:06.452 | LogLevel.DEBUG | Publishing event Init("Starting full ldk node")  
| 2023-04-25 07:16:06.453 | LogLevel.INFO | No seed found. Generating new seed  
| 2023-04-25 07:16:06.463 | LogLevel.INFO | Creating the wallet network: Regtest 
| 2023-04-25 07:16:06.784 | LogLevel.INFO | Did not find channel manager data on disk. Initializing new channel manager  
| 2023-04-25 07:16:07.418 | LogLevel.ERROR | Failed to initialise: Error: Failed to build oracle client

Caused by:
    0: IO error
    1: error sending request for url (https://oracle.holzeis.me/oracle/publickey): error trying to connect: tcp connect error: No route to host (os error 65)
    2: error trying to connect: tcp connect error: No route to host (os error 65)
    3: tcp connect error: No route to host (os error 65)
    4: No route to host (os error 65) 
| 2023-04-25 07:16:17.095 | LogLevel.INFO | Successfully stored the email address .... 
| 2023-04-25 07:16:17.099 | LogLevel.ERROR | Aborting after panic in task info: panicked at 'storage::get(): called get() before set()', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/state-0.5.3/src/storage.rs:162:14
```

On a second start everything seems to be working normal. I guess it has something to do with the app asking on the first start for permissions to connect to the network. Although the permission is granted the app seems still not to have access right away, resulting into the app crashing at startup. At the second start, the permissions have been applied and the app start normal.

![Image](https://user-images.githubusercontent.com/382048/234182444-6a65ddd7-7789-4f56-9998-1ed7ba7a289d.jpg)

**Comment by bonomat** [comment]
The request you see (10101 would like to find and connect to devices on your local network) is not related to requests to the internet. I wonder why our app is asking this: it's for finding devices in your "local network", e.g. sonos speaker, or so.

**Comment by klochowicz** [comment]
@holzeis this is a stab in the dark, but do you get the "local network" permission prompt on debug build by any chance? or a regular release? 

Flutter needs more permissions for 'debug' to be able to do remote debugging, so just wanted confirm that this is not the issue we're seeing here.

**Comment by holzeis** [comment]
> @holzeis this is a stab in the dark, but do you get the "local network" permission prompt on debug build by any chance? or a regular release? 
> 
> Flutter needs more permissions for 'debug' to be able to do remote debugging, so just wanted confirm that this is not the issue we're seeing here.

I get it on the released app on TestFlight.

**Comment by klochowicz** [comment]
hmm.... I wonder if we could simply try this a few times until some elapsed time, e.g. 10s.

I'll see if there's a simple way to deal with it and will seek to test it locally.
