### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#508]
Prometheus came handy in the past to track certain metrics, imho we should add it to our coordinator as well and start tracking: 

(including but not limited to)
- [x] connected peers
- [ ] connected users from our app
- [x] in-bound channel liquidity
- [x] out-bound channel liquidity
- [x] open position (amounts, our_margin, their_margin)
- [ ] if a position gets closed
- [ ] if a position gets opened
- [ ] if a channel gets opened
- [ ] if a channel gets closed
- [x] balance (on/off-chain)
- [ ] amounts traded
- [ ] trades per user
- [ ] deposited money

Note: this is a mix between operational and business metrics. Feel free to seperate them.

**Comment by bonomat** [comment]
Let's stick with the libraries we know for now please. Time is not our friend at the moment and it's better to use tools we know already.

**Comment by klochowicz** [comment]
but this.... saves time? 🤔

**Comment by luckysori** [comment]
We are already using `autometrics` a bit, but we suppose we still want to add some of these bespoke metrics.

**Comment by bonomat** [comment]
Created a follow-up ticket https://github.com/get10101/10101/issues/896 but left out 

- if a position gets closed
- if a position gets opened
- if a channel gets opened
- if a channel gets closed
- amounts traded
- trades per user
- deposited money

which I believe are hard to track using prometheus metrics
