### ISSUE TITLE
Success popup is shown twice

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#518]
I couldn't reproduce it yet, but every once in a while the success popup after submitting an order is shown twice. Overlapping, meaning that I have to hit close twice to get back to the order / positions overview.

**Comment by klochowicz** [comment]
Is it critical? I would remove that from the MVP list as it doesn't struck me as anything we should focus on right now (compared to all other bugs).

**Comment by bonomat** [comment]
Does not seem to have happened again.

**Comment by holzeis** [comment]
still happening.. seen it on the latest version.

**Comment by holzeis** [comment]
And it happened again on the latest version 😕

**Comment by bonomat** [comment]
> And it happened again on the latest version 😕

It's happening on your phone right?

**Comment by holzeis** [comment]
> > And it happened again on the latest version 😕
> 
> 
> 
> It's happening on your phone right?

Yes

**Comment by bonomat** [comment]
Is this still happening or can I close it again and you reopen it? 😬

**Comment by holzeis** [comment]
Well I think it's still happening, but I am happy to close it and open it once I see it again 🙃

**Comment by klochowicz** [comment]
How about a middle ground.... we can agree that it's a shortcoming, but we don't fix it as it has 0 impact on stability and usefulness of the app? 🤓

**Comment by Restioson** [comment]
Possibly related: I fixed a different behaviour where the payment success/fail popup _would not_ always be shown in a prior commit: (https://github.com/get10101/10101/commit/6852939404abc53b54709e3fd390e4c4dde0c4b4). Possible that we need to add a similar check here (whether or not it's already been displayed).

**Comment by holzeis** [comment]
I think the issue is related to how we are using `addPostFrameCallback`. I guess whats happening is that we are rendering the trade screen due to a change notification and thus re-registering the `addPostFrameCallback`. This is happening randomly because it depends on when we receive the update (maybe its the price update notification).

I suggest we fix that issue by not relying on the `addPostFrameCallback` altogether and rather publish an `MatchEvent` upon which we are showing the Dialog.

**Comment by holzeis** [comment]
> I managed to have it 3 times today 😅

that's another bug then.. 🤪
