### ISSUE TITLE
Trading ability shouldn't be hampered by `Position` state

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#530]
### Problem

In the app we have an object `Position` which has the ability to prevent the user from trading. This seems okay as we one of the limitations we want to impose at the moment is that the user can only have one position at a time.

The problem lies in the fact that the `Position` state is updated based on the state of the underlying DLC. Unfortunately that update can be missed (perhaps the app is shut down before it arrives), so we can end up with an app without an open DLC, but with an "open" Position which prevents the user from trading.

### Proposal

I think we could get rid of the whole concept of a position state, solely relying on the DLC state instead. We still need a lot of metadata associated with the position, so that would remain.

**Comment by holzeis** [comment]
Related to https://github.com/get10101/10101/issues/568

**Comment by Restioson** [comment]
This reminds me a bit of the itchysats debate on database state vs on-chain state :sweat_smile:
