### ISSUE TITLE
Do not start the app if we failed during init (e.g. didn't start the backend)

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#549]
Right now, if anything crashes during startup, we catch the exception and proceed with opening the UI.

This way we are able to view / export the logs, but it makes it:
1) harder to notice a regression (e.g. #547 - only visible when using / not just starting the UI)
2) possible for the app to run without the backend, causing all sorts of issues for the users in the wild, e.g. #546 

Ideally, we should either:
- crash hard - and force sending the backtrace to us via TestFlight
- just show the settings screen, allowing viewing/exporting logs, but disallow any engagement with wallet/welcome screen / trading screen.
- automatically send the logs to us and gracefully close.

Thoughts? I think the first one is easiest during closed beta, with moving to the second option as the app matures.

**Comment by holzeis** [comment]
> crash hard - and force sending the backtrace to us via TestFlight

The stacktrace is always available to us if the app crashes. see also https://matrix.to/#/!NvqghtiBvZfpwYglIo:matrix.org/$Zq9Za83LF3qAOLGfMGc2o6-ISXKKLm0WoTEt4Ty9XEE?via=matrix.org&via=breadpirates.chat

> Thoughts? I think the first one is easiest during closed beta, with moving to the second option as the app matures.
I do agree, just let the app crash. I don't think the logs will give us any more valuable information than the stacktrace already does.

**Comment by da-kami** [comment]
> just show the settings screen, allowing viewing/exporting logs, but disallow any engagement with wallet/welcome screen / trading screen.

I think this is *only* useful if the user also knows that something went wrong, i.e. we have to communicate that there was a severe error that prevented the app from starting up!
(I might be pointing out the obvious, I am not sure this was implied in what you wrote up.)

**Comment by klochowicz** [comment]
> > just show the settings screen, allowing viewing/exporting logs, but disallow any engagement with wallet/welcome screen / trading screen.
> 
> I think this is _only_ useful if the user also knows that something went wrong, i.e. we have to communicate that there was a severe error that prevented the app from starting up! (I might be pointing out the obvious, I am not sure this was implied in what you wrote up.)

true. this PR is exactly in this sprit - 'exit' from the app will at least tell the user something is wrong, instead of pretending to go on a bit more when the wheels will fall off from unrelated error:
- the true purpose is to prevent unjustified errors / crash reports that would happen if the backend is not running.

**Comment by klochowicz** [comment]
Resolved by #595
