### ISSUE TITLE
ADR for initial funding of Lightning wallet

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#55]
These options are also outlined in #34:

#### 1. Route payment all the way to the coordinator first
1.  User tries to create invoice.
2.  App generates an invoice *via the coordinator* with a payment preimage that only the app knows.
3.  ~App shares payment hash with coordinator.~[^1]
4.  Payer pays the invoice, which eventually reaches the coordinator as a HTLC.
5.  Coordinator matches the received HTLC to the one registered by the app.
6.  Coordinator opens channel with user, including HTLC with amount minus flat routing fee and liquidity-based routing fee.
7.  App claims payment.

#### 2. Open channel between coordinator and user first
1.  User tries to create invoice.
2.  Coordinator opens channel with user with desired invoice amount as inbound liquidity for user (plus whatever inbound liquidity they would want).
3.  Invoice then generated, including route hint for final hop between coordinator and user.

### Tasks

We want to:

- [x] Test that option 1 is feasible, as it is the preferred option.
- [ ] Write an ADR to explain findings, decision and any other insights.

[^1]: The coordinator shouldn't need to know about the invoice. It should be sufficient to learn about the incoming payment, match it with a peer with a connection, but without a channel, and proceed to create the channel with the forwarded payment minus the liquidity fees.

**Comment by holzeis** [comment]
> App generates an invoice to the coordinator with a payment preimage that only the app knows.

I've generated an [invoice](https://lightningdecoder.com/lnbc1p3a8wz9pp5d6k0360rvzhffpxtxwa2dfjdu6n8p9rtuq35pruazdqxrd7xgaxsdqqcqpjsp5werl6pzplax409pqfeuwyy39d5c5zjy0nl8lq5mvvvds57nm5elq9q7sqqqqqqqqqqqqqqqqqqqsqqqqqysgqmqz9gxqyjw5qrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glcll688vkwkzkdjyqqqqlgqqqqqeqqjqdpypnv3dvzjnpdgamjqt92hthdt8qw6cstj0x24c4t0ml8wp2qazpke0slyh0g7fqrsmhh2fwjr052t25twazuym7tvhm2hwjv87yzsprp32x3) in the phoenix wallet and it appears they don't need to generate an invoice for the coordinator, but create an invoice directly to my phones lightning node.

This is my node id `025d6e73beb87aa0a01c1291a4f5e5431d92454e5d03744f73c6473b2ceb0acd91` which can be found in the payee pub key.

So I guess there is also an option 3.

**Comment by luckysori** [comment]
> > App generates an invoice to the coordinator with a payment preimage that only the app knows.
> 
> I've generated an [invoice](https://lightningdecoder.com/lnbc1p3a8wz9pp5d6k0360rvzhffpxtxwa2dfjdu6n8p9rtuq35pruazdqxrd7xgaxsdqqcqpjsp5werl6pzplax409pqfeuwyy39d5c5zjy0nl8lq5mvvvds57nm5elq9q7sqqqqqqqqqqqqqqqqqqqsqqqqqysgqmqz9gxqyjw5qrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glcll688vkwkzkdjyqqqqlgqqqqqeqqjqdpypnv3dvzjnpdgamjqt92hthdt8qw6cstj0x24c4t0ml8wp2qazpke0slyh0g7fqrsmhh2fwjr052t25twazuym7tvhm2hwjv87yzsprp32x3) in the phoenix wallet and it appears they don't need to generate an invoice for the coordinator, but create an invoice directly to my phones lightning node.
> 
> This is my node id `025d6e73beb87aa0a01c1291a4f5e5431d92454e5d03744f73c6473b2ceb0acd91` which can be found in the payee pub key.
> 
> So I guess there is also an option 3 with the "App generates an invoice to the actually phone nodeid"

The invoice lists a short channel ID with the value `ff473b2ceb0acd91`. Which channel is it referring to?

**Comment by 1010Tom** [comment]
@holzeis : did you have funds or a channel in your Breez wallet?

**Comment by 1010Tom** [comment]
I believe you either have or had a channel open in Breez. [This](https://lightningdecoder.com/lightning:lnbc100u1p3as3urpp5k9fwfjlwmuvduazq5s0q02s2xqpukdlmkzva3dhpd9fjsw8k29sqdqqcqzpgxqrrssrzjqvgptfurj3528snx6e3dtwepafxw5fpzdymw9pj20jj09sunnqmwqqqqqyqqqqqqqqqqqqlgqqqqqqgqjqnp4qfg0de2y0y9y2clr48szd760zygn0nuumwwsdj2spv2alrcryduk5sp502279sark8wwqpqgn39qa0zruer2m5x8svj0t90cf204xt9ewrts9qyyssq9f5n4qz24zvaa8a6jfhhhkw79sjaykuf0ldrv7zasgar5ge5vvg9wfy4cmk0yakf3z2p7cpv4847puynvf7gr6fc6vf4yzg43xutunqqmdsv9p) is an invoice from a _clean_ app without anything. 
As you can see, the routing hint includes a short channel_id `0000010000000000` which looks like a tmp channel ID to me. 

Imho this is scenario 1 as described above.

**Comment by luckysori** [comment]
> I believe you either have or had a channel open in Breez. [This](https://lightningdecoder.com/lightning:lnbc100u1p3as3urpp5k9fwfjlwmuvduazq5s0q02s2xqpukdlmkzva3dhpd9fjsw8k29sqdqqcqzpgxqrrssrzjqvgptfurj3528snx6e3dtwepafxw5fpzdymw9pj20jj09sunnqmwqqqqqyqqqqqqqqqqqqlgqqqqqqgqjqnp4qfg0de2y0y9y2clr48szd760zygn0nuumwwsdj2spv2alrcryduk5sp502279sark8wwqpqgn39qa0zruer2m5x8svj0t90cf204xt9ewrts9qyyssq9f5n4qz24zvaa8a6jfhhhkw79sjaykuf0ldrv7zasgar5ge5vvg9wfy4cmk0yakf3z2p7cpv4847puynvf7gr6fc6vf4yzg43xutunqqmdsv9p) is an invoice from a _clean_ app without anything. As you can see, the routing hint includes a short channel_id `0000010000000000` which looks like a tmp channel ID to me.
> 
> Imho this is scenario 1 as described above.

@holzeis and I did discuss it yesterday offline and we reached a slightly different conclusion. But I think that's because we misunderstood the description of scenario 1. The invoice is generated for the _app_'s pubkey and routed through the coordinator as indicated by the "routing info" or "route hint". So the scenarios do match.

One interesting thing we did notice is that scenario shouldn't require communication between coordinator and app once the peers are connected. The coordinator should be able to identify that the incoming HTLC pays to a connected peer without a channel and proceed accordingly. Specifically, this means that we shouldn't need step 3.

**Comment by bonomat** [comment]
> One interesting thing we did notice is that scenario 1 shouldn't require communication between coordinator and app once the peers are connected. The coordinator should be able to identify that the incoming HTLC pays to a connected peer without a channel and proceed accordingly. Specifically, this means that we shouldn't need step 3.

Ah right, only by the peer ID the coordinator will know where to send it to. Good call 👍

**Comment by holzeis** [comment]
> @holzeis : did you have funds or a channel in your Breez wallet?

@bonomat I've created an invoice with [phoenix](https://lightningdecoder.com/lnbc1p3a8wz9pp5d6k0360rvzhffpxtxwa2dfjdu6n8p9rtuq35pruazdqxrd7xgaxsdqqcqpjsp5werl6pzplax409pqfeuwyy39d5c5zjy0nl8lq5mvvvds57nm5elq9q7sqqqqqqqqqqqqqqqqqqqsqqqqqysgqmqz9gxqyjw5qrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glcll688vkwkzkdjyqqqqlgqqqqqeqqjqdpypnv3dvzjnpdgamjqt92hthdt8qw6cstj0x24c4t0ml8wp2qazpke0slyh0g7fqrsmhh2fwjr052t25twazuym7tvhm2hwjv87yzsprp32x3) and [breez](https://lightningdecoder.com/LNBC200U1P3AZGK9PP5FTFKEZA6JF7ZHGW7LZJXT4FEHZ7ZNF30R4JPQ0YHW50MM2M2GT6QDQQCQZPGXQRRSSRZJQVGPTFURJ3528SNX6E3DTWEPAFXW5FPZDYMW9PJ20JJ09SUNNQMWQQQQQYQQQQQQQQQQQQLGQQQQQQGQJQNP4QTGSL5LM9YUQDQZZT6FV7WARFV0JCJEJ3V9WTYM02WLGK4Q5YC7CSSP5QZ3PWZ5RULCWGS3X4WUGGKUUU98SVS0E9HVMXN75WA702UCLY4AQ9QYYSSQD6DZP0KVL60FSFJD3PERF7GLPF2LZ43NAQYY4M8AVJJ8YE8KM5R3TYHK84LJ3XL5U72LFCGS9JAML6A0VVWN266MNJM46GQVF4J5QNQPULJTFF). Both examples look very similar. For phoenix I had definitely no channel, In case of Breez I do have a channel, but not with Breez, but with my own lightning node. I guess in this scenario the routing info was ignored, because my node did know a direct path to my phones node.

Anyhow, I am still not sure what the short channel id in the routing info is referencing to, but it's definitely not a channel I have opened with either phoenix or breez.

**Comment by bonomat** [comment]
Given the note from @luckysori it's now clear to me that the channel id is not even needed. Breez or Phoenix will know using your peer ID if there is a channel big enough to forward or if they have to intercept and open a channel to you.

**Comment by luckysori** [comment]
Looking at `rust-lightning` more closely, I found this event which appears to be designed for our use case:

```rust
/// Used to indicate that we've intercepted an HTLC forward. This event will only be generated if
/// you've encoded an intercept scid in the receiver's invoice route hints using
/// [`ChannelManager::get_intercept_scid`] and have set [`UserConfig::accept_intercept_htlcs`].
///
/// [`ChannelManager::forward_intercepted_htlc`] or
/// [`ChannelManager::fail_intercepted_htlc`] MUST be called in response to this event. See
/// their docs for more information.
///
/// [`ChannelManager::get_intercept_scid`]: crate::ln::channelmanager::ChannelManager::get_intercept_scid
/// [`UserConfig::accept_intercept_htlcs`]: crate::util::config::UserConfig::accept_intercept_htlcs
/// [`ChannelManager::forward_intercepted_htlc`]: crate::ln::channelmanager::ChannelManager::forward_intercepted_htlc
/// [`ChannelManager::fail_intercepted_htlc`]: crate::ln::channelmanager::ChannelManager::fail_intercepted_htlc
HTLCIntercepted {
    /// An id to help LDK identify which HTLC is being forwarded or failed.
    intercept_id: InterceptId,
    /// The fake scid that was programmed as the next hop's scid, generated using
    /// [`ChannelManager::get_intercept_scid`].
    ///
    /// [`ChannelManager::get_intercept_scid`]: crate::ln::channelmanager::ChannelManager::get_intercept_scid
    requested_next_hop_scid: u64,
    /// The payment hash used for this HTLC.
    payment_hash: PaymentHash,
    /// How many msats were received on the inbound edge of this HTLC.
    inbound_amount_msat: u64,
    /// How many msats the payer intended to route to the next node. Depending on the reason you are
    /// intercepting this payment, you might take a fee by forwarding less than this amount.
    ///
    /// Note that LDK will NOT check that expected fees were factored into this value. You MUST
    /// check that whatever fee you want has been included here or subtract it as required. Further,
    /// LDK will not stop you from forwarding more than you received.
    expected_outbound_amount_msat: u64,
},
```

This is event is different to the one I thought we'd need to use: `PaymentClaimable`.

**Comment by bonomat** [comment]
Cool, good find. I didn't see this event neither.

**Comment by holzeis** [comment]
so is the `fake scid` the short channel id referred to in the routing info?

**Comment by bonomat** [comment]
> so is the `fake scid` the short channel id referred to in the routing info?

I would say yes.

**Comment by bonomat** [comment]
Update on the actual flow: 

Alice uses 10101 and wants to receive a payment from Bob via the coordinator but does not yet have a channel open with the coordinator. 

1. Alice tells the coordinator that she is expecting a payment. The coordinator generates a `fake_channel_id`
2. Alice generates an invoice which includes a routing hint using this fake channel id
3. Alice gives the invoice to Bob
4. Bob pays the invoice
5. The coordinator intercepts this payments and checks for known `fake_channel_id`s
6. The coordinator opens a channel
7. Once the channel is open, the coordinator forwards the payment

```mermaid
sequenceDiagram

title Payment Flow

participant Alice
participant Coordinator
participant Bob

Alice->>Coordinator: tells she is expecting a payment
Coordinator->>Coordinator: generates fake_channel_id
Coordinator->>Alice: fake_channel_id
Alice->>Alice: generates invoice with routing hint using fake_channel_id
Alice->>Bob: send invoice
Bob->>Bob: pays invoice
Bob->>Coordinator: send payment
Coordinator->>Coordinator: intercepts payment
Coordinator->>Coordinator: checks for known fake_channel_id
Coordinator->>Alice: opens channel
Coordinator->>Alice: forward payment
```
