### ISSUE TITLE
Fee rate much too low: force closure

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#555]
We have another channel force closure

```
{"timestamp":"2023-04-28T19:25:25.452196137Z","level":"INFO","fields":{"message":"\nChannel closed","channel":"cc61caf56546cc48cd1039b06609b14d55aebc3e5f38f79890ccee3d95cd8c44","reason":"CounterpartyForceClosed { peer_msg: \"Peer's feerate much too low. Actual: 253. Our expected lower limit: 5060 (- 250)\" }"},"target":"ln_dlc_node::ln::event_handler"}
```

and this one: 

```
2023-04-25 17:44:51 TRACE lightning::ln::peer_handler: Handling SendErrorMessage HandleError event in peer_handler for node 03fe8461ebc025880b58021c540e0b7782bb2bcdc99da9822f5c6d2184a59b8f69 with message Peer's feerate much too low. Actual: 2081. Our expected lower limit: 3036 (- 250)    
```

This is critical because our money is locked up for 2 weeks

**Comment by bonomat** [comment]
Note: this was a channel between us and an app. So we should be in control of both sides.

**Comment by holzeis** [comment]
That was my channel! Here are the logs from my phone.

```
023-04-28 21:25:16.604 | LogLevel.DEBUG | lightning::ln::peer_handler: Error handling message from 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156; ignoring: Couldn't find channel for update  
| 2023-04-28 21:25:18.711 | LogLevel.ERROR | lightning::ln::channelmanager: Closing channel cc61caf56546cc48cd1039b06609b14d55aebc3e5f38f79890ccee3d95cd8c44 due to close-required error: Peer's feerate much too low. Actual: 253. Our expected lower limit: 5060 (- 250)  
| 2023-04-28 21:25:18.712 | LogLevel.DEBUG | lightning::ln::channelmanager: Finishing force-closure of channel with 0 HTLCs to fail  
| 2023-04-28 21:25:18.713 | LogLevel.INFO | lightning::chain::channelmonitor: Applying update to monitor cc61caf56546cc48cd1039b06609b14d55aebc3e5f38f79890ccee3d95cd8c44, bringing update_id from 24 to 25 with 1 changes.  
| 2023-04-28 21:25:18.714 | LogLevel.INFO | lightning::chain::channelmonitor: Broadcasting local commitment tx with txid 8f60e05ce1af9f4917517e706fd9ed7a5605f4dc498a4740d7b0a8ae91d0fee7  
| 2023-04-28 21:25:18.748 | LogLevel.ERROR | Error broadcasting transaction: Electrum(Protocol(String("sendrawtransaction RPC error: {\"code\":-25,\"message\":\"bad-txns-inputs-missingorspent\"}")))  
| 2023-04-28 21:25:18.760 | LogLevel.ERROR | lightning::ln::channelmanager: Peer's feerate much too low. Actual: 253. Our expected lower limit: 5060 (- 250)  
| 2023-04-28 21:25:18.761 | LogLevel.ERROR | lightning::ln::channelmanager: Failed to find corresponding channel  
| 2023-04-28 21:25:18.765 | LogLevel.INFO | Received event event: ChannelClosed { channel_id: [204, 97, 202, 245, 101, 70, 204, 72, 205, 16, 57, 176, 102, 9, 177, 77, 85, 174, 188, 62, 95, 56, 247, 152, 144, 204, 238, 61, 149, 205, 140, 68], user_channel_id: 0, reason: ProcessingError { err: "Peer's feerate much too low. Actual: 253. Our expected lower limit: 5060 (- 250)" } } 
| 2023-04-28 21:25:18.766 | LogLevel.INFO | 
Channel closed channel: cc61caf56546cc48cd1039b06609b14d55aebc3e5f38f79890ccee3d95cd8c44,reason: ProcessingError { err: "Peer's feerate much too low. Actual: 253. Our expected lower limit: 5060 (- 250)" } 
| 2023-04-28 21:25:18.767 | LogLevel.DEBUG | Successfully handled event event: "ChannelClosed { channel_id: [204, 97, 202, 245, 101, 70, 204, 72, 205, 16, 57, 176, 102, 9, 177, 77, 85, 174, 188, 62, 95, 56, 247, 152, 144, 204, 238, 61, 149, 205, 140, 68], user_channel_id: 0, reason: ProcessingError { err: \"Peer's feerate much too low. Actual: 253. Our expected lower limit: 5060 (- 250)\" } }" 
| 2023-04-28 21:25:19.672 | LogLevel.INFO | Getting all payments payment_hashes: [PaymentHash([178, 164, 150, 155, 115, 43, 38, 215, 64, 154, 248, 23, 147, 28, 210, 113, 255, 38, 146, 210, 167, 226, 229, 113, 100, 163, 95, 82, 44, 229, 13, 162]), PaymentHash([48, 221, 0, 198, 242, 227, 251, 178, 130, 129, 164, 209, 88, 204, 58, 140, 177, 35, 148, 181, 49, 244, 192, 171, 81, 213, 199, 239, 165, 175, 185, 172]), PaymentHash([9, 17, 145, 144, 165, 114, 98, 88, 168, 150, 186, 89, 251, 186, 115, 17, 8, 232, 159, 236, 224, 138, 88, 230, 121, 110, 103, 83, 58, 155, 103, 55])] 
```

**Comment by holzeis** [comment]
I think this has something to do with the electrum client. A few seconds before the error the electrum client was recreated.

```
| 2023-04-28 21:25:05.981 | LogLevel.WARNING | electrum_client::raw_client: got error for req_id 10137: JSON(Error("EOF while parsing a value", line: 1, column: 0))  
| 2023-04-28 21:25:05.982 | LogLevel.WARNING | electrum_client::raw_client: removing all waiting req of this batch  
| 2023-04-28 21:25:05.983 | LogLevel.WARNING | electrum_client::client: call 'batch_script_get_history' failed with EOF while parsing a value at line 1 column 0, retry: 1/1  
| 2023-04-28 21:25:08.006 | LogLevel.INFO | electrum_client::client: Succesfully created new client
```

After tracing the error in the code, I think the following happened.

On every tick we check if the fee rate needs to be updated for our channel.
The new fee rate is estimated using our electrum client
```
let new_feerate = self.fee_estimator.bounded_sat_per_1000_weight(ConfirmationTarget::Normal);
```

**Comment by holzeis** [comment]
@bonomat 
> This is critical because our money is locked up for 2 weeks

I just checked we only have to wait for 144 blocks or ~24 hours. The config relevant here is `our_to_self_delay` which is set to the default value of `144`. 2016 blocks or ~2 weeks is only the max value we would be willing to accept and is configured with `their_to_self_delay`

I think 24 hours is a reasonable duration.

**Comment by bonomat** [comment]
I think it is/was critical because it happened with a public channel (i.e. one against someone else): 

```
2023-04-25 17:44:51 TRACE lightning::ln::peer_handler: Handling SendErrorMessage HandleError event in peer_handler for node 03fe8461ebc025880b58021c540e0b7782bb2bcdc99da9822f5c6d2184a59b8f69 with message Peer's feerate much too low. Actual: 2081. Our expected lower limit: 3036 (- 250)    
```

**Comment by bonomat** [comment]
> I just checked we only have to wait for 144 blocks or ~24 hours. The config relevant here is `our_to_self_delay` which is set to the default value of `144`. 2016 blocks or ~2 weeks is only the max value we would be willing to accept and is configured with `their_to_self_delay`

So we need to adjust `their_to_self_delay`?

**Comment by holzeis** [comment]
> I think it is/was critical because it happened with a public channel (i.e. one against someone else): 
> 
> 
> 
> ```
> 
> 2023-04-25 17:44:51 TRACE lightning::ln::peer_handler: Handling SendErrorMessage HandleError event in peer_handler for node 03fe8461ebc025880b58021c540e0b7782bb2bcdc99da9822f5c6d2184a59b8f69 with message Peer's feerate much too low. Actual: 2081. Our expected lower limit: 3036 (- 250)    
> 
> ```

Are you sure it was a public channel? I think the logs you provided pointed to a channel with my app.

**Comment by holzeis** [comment]
> > I just checked we only have to wait for 144 blocks or ~24 hours. The config relevant here is `our_to_self_delay` which is set to the default value of `144`. 2016 blocks or ~2 weeks is only the max value we would be willing to accept and is configured with `their_to_self_delay`
> 
> 
> 
> So we need to adjust `their_to_self_delay`?

Yes if we don't want to accept channels with delay with 2016.

**Comment by holzeis** [comment]
@bonomat I guess this ticket will also be resolved if we are using AnchorOutput channels?

**Comment by bonomat** [comment]
> @bonomat I guess this ticket will also be resolved if we are using AnchorOutput channels?

I'm not 100% unfortunately.

**Comment by holzeis** [comment]
We had two additional incidents in production with the channel being force closed due to `Peer's feerate much too high.` I guess on the other side they were much too low?

1. ae486887851b710492d85bf76a1612fcba9154aa060c6f99b7672125347decea: This was the channel with with [my node](https://amboss.space/node/02d8659db54d8c25495d61479d7dcdbda8f949e19b6e03894658cbd3b0a4bc7cd6) 
2. 5c72f12e6be882e5b2b12acebf08e1dfd2074b460fbbc0c943e3203d8b73378b: This was unfortunately the channel with [FaucetCollector.com](https://amboss.space/node/02abd50ef667e05d26a1132eaac0521512605444e95bf12c474a114c7407994eb7)

Not sure whats the state of our funds is though. It looks like the transaction got broadcasted, but I couldn't find the transaction in our wallet.

**Comment by bonomat** [comment]
I don't think this had something todo with electrs when looking at `5c72f12e6be882e5b2b12acebf08e1dfd2074b460fbbc0c943e3203d8b73378b`. 

```
Peer's feerate much too high. Actual: 126278. Our expected upper limit: 50600
```

If electrs fails we would have gotten a lower value here. I assume the `50600` is coming from the fact that we have hardcoded upper limits.

**Comment by bonomat** [comment]
I think we should do this: https://github.com/get10101/10101/issues/617

**Comment by holzeis** [comment]
I think think the problem is our upper limit of 20 sats/vbytes -> 20 * 253 = `5_060`. I don't know where the extra `0` is coming from though.

**Comment by luckysori** [comment]
> I think think the problem is our upper limit of 20 sats/vbytes -> 20 * 253 = `5_060`. I don't know where the extra `0` is coming from though.

The extra 0 comes from multiplying by 10: https://github.com/lightningdevkit/rust-lightning/blob/15d48d8243e05fbd198215c6a3a762d2bdc9f38b/lightning/src/ln/channel.rs#L1094.

**Comment by bonomat** [comment]
We had 4 closures because of this error already :/ 

https://itchysats.grafana.net/goto/DCoggv84g?orgId=1

I haven't tried but I believe we should be able to reproduce this locally by faking the fee estimate during runtime: i.e. edit this file: 

https://github.com/holzeis/10101/blob/a2af291e7916acb8695d008dc2271f5f63f174d5/faucet/btc-fee-estimates.json

**Comment by klochowicz** [comment]
> I think think the problem is our upper limit of 20 sats/vbytes -> 20 * 253 = `5_060`. I don't know where the extra `0` is coming from though.

we don't have this limit since rolling out esplora...

**Comment by luckysori** [comment]
> Did version 1.0.18 already include the removal of the tx fee upper limit? resp. do we still have a limit there?

We use a [fee rate cache](https://github.com/get10101/10101/blob/30a8a03bdfc7e8347413d031864e697fecc67c0e/crates/ln-dlc-node/src/ldk_node_wallet.rs#L327) in 1.0.18.

**Comment by bonomat** [comment]
Maybe we are doing something wrong ? 
It looks like our fee rate was too high this time ? 

Shall we reach out to LDK team and see what they think about this?

**Comment by holzeis** [comment]
The numbers are quite close, could it be that it might be an issue of our fee estimation source? (we are using blockstream while (my) lnd node is using (my) bitcoind service).

Alternatively we might be able to increase the limit of 250 sats?

**Comment by holzeis** [comment]
In the context of different target block settings, I found that lnd is using this configuration suggesting that the target blocks used for fee negotiation is 10, but I am not sure if thats the only config impacting that.

```
; The target number of blocks in which a cooperative close initiated by a remote
; peer should be confirmed. This target is used to estimate the starting fee
; rate that will be used during fee negotiation with the peer. This target is
; also used for cooperative closes initiated locally if the --conf_target for
; the channel closure is not set.
; coop-close-target-confs=10
```

The important part `used during fee negotiation with the peer.`

**Comment by holzeis** [comment]
I am closing this ticket for now as it might be fixed with https://github.com/get10101/10101/pull/780

Please re-open if this bug is happening again.

**Comment by holzeis** [comment]
Opening this ticket as it happened again on the latest version. 

```
2023-06-26T01:11:06Z	{"timestamp":"2023-06-26T01:11:06.888452118Z","level":"DEBUG","fields":{"message":"Successfully handled event","event":"\"ChannelClosed { channel_id: [176, 136, 143, 194, 140, 148, 42, 30, 42, 140, 197, 82, 133, 253, 25, 24, 174, 9, 50, 55, 226, 37, 5, 89, 3, 145, 174, 176, 220, 38, 11, 252], user_channel_id: 43694292409452990062306170634063270236, reason: ProcessingError { err: \\\"Peer's feerate much too low. Actual: 4517. Our expected lower limit: 4772 (- 250)\\\" } }\""},"target":"ln_dlc_node::ln::event_handler"}
2023-06-26T01:11:06Z	{"timestamp":"2023-06-26T01:11:06.887949756Z","level":"INFO","fields":{"message":"\nChannel closed","channel":"b0888fc28c942a1e2a8cc55285fd1918ae093237e22505590391aeb0dc260bfc","reason":"ProcessingError { err: \"Peer's feerate much too low. Actual: 4517. Our expected lower limit: 4772 (- 250)\" }"},"target":"ln_dlc_node::ln::event_handler"}
2023-06-26T01:11:06Z	{"timestamp":"2023-06-26T01:11:06.885559343Z","level":"INFO","fields":{"message":"Received event","event":"ChannelClosed { channel_id: [176, 136, 143, 194, 140, 148, 42, 30, 42, 140, 197, 82, 133, 253, 25, 24, 174, 9, 50, 55, 226, 37, 5, 89, 3, 145, 174, 176, 220, 38, 11, 252], user_channel_id: 43694292409452990062306170634063270236, reason: ProcessingError { err: \"Peer's feerate much too low. Actual: 4517. Our expected lower limit: 4772 (- 250)\" } }"},"target":"ln_dlc_node::ln::event_handler"}
2023-06-26T01:11:06Z	{"timestamp":"2023-06-26T01:11:06.879908916Z","level":"ERROR","fields":{"message":"Peer's feerate much too low. Actual: 4517. Our expected lower limit: 4772 (- 250)","log.target":"lightning::ln::channelmanager","log.module_path":"lightning::ln::channelmanager","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/a663e1f/lightning/src/ln/channelmanager.rs","log.line":6419},"target":"lightning::ln::channelmanager"}
2023-06-26T01:11:06Z	{"timestamp":"2023-06-26T01:11:06.713216316Z","level":"ERROR","fields":{"message":"Closing channel b0888fc28c942a1e2a8cc55285fd1918ae093237e22505590391aeb0dc260bfc due to close-required error: Peer's feerate much too low. Actual: 4517. Our expected lower limit: 4772 (- 250)","log.target":"lightning::ln::channelmanager","log.module_path":"lightning::ln::channelmanager","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/a663e1f/lightning/src/ln/channelmanager.rs","log.line":5188},"target":"lightning::ln::channelmanager"}
```

**Comment by bonomat** [comment]
> Opening this ticket as it happened again on the latest version.
> 
> ```
> 2023-06-26T01:11:06Z	{"timestamp":"2023-06-26T01:11:06.888452118Z","level":"DEBUG","fields":{"message":"Successfully handled event","event":"\"ChannelClosed { channel_id: [176, 136, 143, 194, 140, 148, 42, 30, 42, 140, 197, 82, 133, 253, 25, 24, 174, 9, 50, 55, 226, 37, 5, 89, 3, 145, 174, 176, 220, 38, 11, 252], user_channel_id: 43694292409452990062306170634063270236, reason: ProcessingError { err: \\\"Peer's feerate much too low. Actual: 4517. Our expected lower limit: 4772 (- 250)\\\" } }\""},"target":"ln_dlc_node::ln::event_handler"}
> 2023-06-26T01:11:06Z	{"timestamp":"2023-06-26T01:11:06.887949756Z","level":"INFO","fields":{"message":"\nChannel closed","channel":"b0888fc28c942a1e2a8cc55285fd1918ae093237e22505590391aeb0dc260bfc","reason":"ProcessingError { err: \"Peer's feerate much too low. Actual: 4517. Our expected lower limit: 4772 (- 250)\" }"},"target":"ln_dlc_node::ln::event_handler"}
> 2023-06-26T01:11:06Z	{"timestamp":"2023-06-26T01:11:06.885559343Z","level":"INFO","fields":{"message":"Received event","event":"ChannelClosed { channel_id: [176, 136, 143, 194, 140, 148, 42, 30, 42, 140, 197, 82, 133, 253, 25, 24, 174, 9, 50, 55, 226, 37, 5, 89, 3, 145, 174, 176, 220, 38, 11, 252], user_channel_id: 43694292409452990062306170634063270236, reason: ProcessingError { err: \"Peer's feerate much too low. Actual: 4517. Our expected lower limit: 4772 (- 250)\" } }"},"target":"ln_dlc_node::ln::event_handler"}
> 2023-06-26T01:11:06Z	{"timestamp":"2023-06-26T01:11:06.879908916Z","level":"ERROR","fields":{"message":"Peer's feerate much too low. Actual: 4517. Our expected lower limit: 4772 (- 250)","log.target":"lightning::ln::channelmanager","log.module_path":"lightning::ln::channelmanager","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/a663e1f/lightning/src/ln/channelmanager.rs","log.line":6419},"target":"lightning::ln::channelmanager"}
> 2023-06-26T01:11:06Z	{"timestamp":"2023-06-26T01:11:06.713216316Z","level":"ERROR","fields":{"message":"Closing channel b0888fc28c942a1e2a8cc55285fd1918ae093237e22505590391aeb0dc260bfc due to close-required error: Peer's feerate much too low. Actual: 4517. Our expected lower limit: 4772 (- 250)","log.target":"lightning::ln::channelmanager","log.module_path":"lightning::ln::channelmanager","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/a663e1f/lightning/src/ln/channelmanager.rs","log.line":5188},"target":"lightning::ln::channelmanager"}
> ```

Can you please indicate if this happened in production or on our regtest setup?

**Comment by holzeis** [comment]
happened on production!

**Comment by bonomat** [comment]
Closing this as #835 landed
