### ISSUE TITLE
Add Settings screen

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#56]
The settings screen can be accessed by clicking on the three dots in the top menu of the `Wallet` and `Trade` screen.
There is already a placeholder screen linked to the settings screen.

For the MVP we create a simple combined settings screen for the wallet and the trading.

Solution proposal: 
A list view with two sections, one section for the wallet settings, one section for the trade settings. Depending on from which screen we open the settings the respective section is un-collapsed (e.g. if we click settings on the trade screen then the wallet settings are collapsed, the trade settings are un-collapsed when opening the settings screen.)

Note: We don't have to create this behavior in the Figma mock, it's good enough to just show all the settings (both sections un-collapsed) and add a comment.

**Comment by da-kami** [comment]
I'm having a hard time modelling this screen in detail, because we did not clearly specify what "Settings" are in scope for the MVP. 

Here's how this screen could look like on the surface:

![image](https://user-images.githubusercontent.com/5557790/215677805-6db20a04-ba09-4fa0-bbdb-3ae1469281b3.png)

I think we can come up with the actual entries once we implement and take further decisions what settings we want in the MVP!

**Comment by bonomat** [comment]
Looks good. Let's close it then :)
