### ISSUE TITLE
Metric for successful trades

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#564]
Afaik we don't have an easy way to track successful trades from our `coordinator` db: 

1. The `order` table in `coordinator` is actually the `orderbook`, i.e. it includes `orders` which might not have been filled yet
2. The `position` table shows positions with states `open` and `closing`. 
	- Afaik `closing` means that a position has been opened and closed, i.e. these were _two_ trades. 

We should add an extra table which tracks successful trades per trader

**Comment by klochowicz** [comment]
an alternative approach to consider, track 2 metrics (e.g. with autometics)

- `open_position`
- `close_position`

successful trade is the one where we successfully finished the processing of `close_position()` call 

we could also get fancy and check percentage of successfully opened, successfully closed positions etc.
