### ISSUE TITLE
Recover app position state based on DLC state

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#568]
I had a brainstorming session with @luckysori and we've settled on:
- removing `PositionState` from the **app** db.
- deriving `PositionState` from the `Order`(local order on the app)
- during startup, reconciling the `Order` state (simple heuristic: if you just started the app, and the order is filled but the position is still open, set the Order to failed.

The above will simply throw the ball back to the user. We can try to reconcile periodically or query the other party whether they are still acting on it.

Any feedback to the heuristic above would be appreciated - right now I'm just operating under our beta constraint that the Orders are not filled in between app restarts.

_Originally posted by @klochowicz in https://github.com/get10101/10101/issues/558#issuecomment-1530043286_

**Comment by holzeis** [comment]
Closing in favor of https://github.com/get10101/10101/issues/568. @klochowicz please reopen if you think we should keep it.
