### ISSUE TITLE
The publicly hosted instance of bors-ng is deprecated and will go away soon

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#571]
The publicly hosted instance of bors-ng is deprecated and will go away soon.

  If you want to self-host your own instance, [instructions are here][instructions].
  For more help, visit [the forum].

  If you want to switch to GitHub's built-in merge queue, visit [their help page][gh].

  [instructions]: https://github.com/bors-ng/bors-ng#how-to-set-up-your-own-real-instance
  [the forum]: https://forum.bors.tech
  [gh]: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

**Comment by bonomat** [comment]
Bors is still deprecated so this is still relevant :)
