### ISSUE TITLE
JIT - Channel Fee

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#577]
We know that our on-boarding procedure causes friction because the user has to make changes in their wallet they are sending from (i.e. change the max acceptable routing fee). 
The reason for this is that we are charging a 2% routing fee. This fee is hardcoded in the invoice created by the app. 

We don't want to offer channel opening for free because (a) it is meant to be a business model in the future and (b) we have on-chain expenses which we need to cover. We don't need to be profitable from day 1 but we should charge something from day 1.

I see three steps forward: 

- 1. Reduce the channel routing fee 0.5% (for now to) which seems to be acceptable in most apps. #579 
- 2. Use different flow: (1) LSP creates channel, (2) node pays invoice. This is based on trust but given we control both sides (coordinator and app) we can just send a payment from the node to the coordinator up-on channel creation. We can then increase the channel opening fee again to whatever amount we want. Payment routing will not be affected by this anymore. 
- https://github.com/get10101/10101/issues/843

I propose to tackle this in 3 steps: 

1. do 1. now
2. work on 2 next - imho this is a great approach as the fee will be shown as a payment in the app
3. work on 3 once the spec are finalized: see issue https://github.com/get10101/10101/issues/843

I see 1. as a quick fix and not a solution so I would like to avoid a prolonged time of having 1. done but not 2.

**Comment by klochowicz** [comment]
@bonomat do we need this for the MVP, ie. next 2 weeks? or can I remove the label for this issue?

**Comment by bonomat** [comment]
> @bonomat do we need this for the MVP, ie. next 2 weeks? or can I remove the label for this issue?

Yes, i think at least point 2 should be done. 
We might need to do https://github.com/get10101/10101/issues/604 as well.

**Comment by bonomat** [comment]
Ticket is up for grabs, I don't have the capacity to work on this at the moment :(
