### ISSUE TITLE
Compose the wallet from more purposeful structs rather than implementing all traits on one struct

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#584]
At the moment we implement traits on the wallet and then pass the whole wallet in whenever we need certain functionality (e.g. the `FeeEstimator` and `ChainMonitor` in the `ChannelManager`).

It would be cleaner to create smaller dedicated structs that implement the necessary crates, that are initialized and passed in as needed and can be composed into being the wallet.

**Comment by holzeis** [comment]
FeeEstimator has been decoupled, others still to go!

**Comment by klochowicz** [comment]
ideally, we would also move towards using `ldk-node` package when it matures enough - moving some of the functionality to external crates

**Comment by da-kami** [comment]
@luckysori we discussed this in the past - if you want to re-open feel free to do so :)
