### ISSUE TITLE
Force-closing an LN-DLC channel fails

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#591]
### Context

A force-closure of the channel can happen in 2 ways:

- _Automatically_: e.g. LDK will do so if the parties cannot agree on a channel fee rate.
- _Manually_: e.g. We instruct our coordinator to force-close all LN-DLC channels so that we can introduce breaking changes.

### Manual force-closure

We know how to handle the manual case. We just need to call the right APIs provided by `rust-dlc`. We must also write a test to verify this. 

- [x] Implement manual force-closure of LN-DLC channel (see https://github.com/get10101/10101/pull/612).

### Automatic force-closure

It appears to be more challenging to handle the automatic case, as it seems like LDK will eagerly publish the commitment transaction to force-close the channel in a lot of cases, even if the split transaction and the glue transaction are missing.

In our experience, when LDK fails on the commitment transaction publication it still removes the channel from the `ChannelManager`, so we're left in a state where it's hard (perhaps impossible) to recover the funds. In theory we should be able to recover the funds with the information stored in the `ChannelMonitor`, but we haven't verified this yet.

- [ ] #779

---

Related to #51, which focuses on the effect of force-closure of the LN-DLC channel on the DLC channel branch i.e. buffer transaction and CET/refund transaction.

**Comment by holzeis** [comment]
blocks #580

**Comment by holzeis** [comment]
It's fair to say that the manual force-closing is also incomplete, as only the coordinator is able to force-close. Furthermore, we only asserted that the coordinator gets their funds back. Tests are still missing for the app.

**Comment by luckysori** [comment]
> It's fair to say that the manual force-closing is also incomplete, as only the coordinator is able to force-close. Furthermore, we only asserted that the coordinator gets their funds back. Tests / Assertions are still missing for the app.

This bit should be fixed with #771.

**Comment by luckysori** [comment]
Closing as #771 has covered half of this and https://github.com/get10101/10101/issues/779 covers the rest.
