### ISSUE TITLE
Add suggestion to Tweet when order got submitted

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#599]

**Comment by klochowicz** [comment]
I've researched this topic a bit, and there's no easy way to directly publish to tweet (no packages to do so)
We can use `share_plus` package, which will nudge to share our message - the user still needs to click where they want it to be shared.

I tried also creating and adding a screenshot, but that didn't work so far (descoped that part, as this is not essential).

**Comment by holzeis** [comment]
Proposal for the tweet message:

> Just opened a #selfcustodial position using #DLC with @get10101 🚀. The future of decentralised finance starts now!
