### ISSUE TITLE
Prototype fixes after interview with Paul

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#6]
- [x] Align *all* the Bitcoin amounts to be in `sats`! We still have amounts that are in Bitcoin which is super confusing. We noticed a Bitcoin value in the funding flow, but make sure to check the prototype overall.
- [ ] After the user traded we display two trades but only one order. This might be confusing. The problem here is that the orders tab content is not scrollable. We can consider enabling that.
- [x] The `$` sign of Stable Sats wallet is not aligned with the `sats` of the other wallets. (note: I aligned that already in the prototype)
- [ ] There was some confusion because other wallet deposits are not wired anywhere; we should at least wire them to the `Not part of your task` placeholder screen so it is clear to the user that these components can be clicked but it's not part of the prototype setup.
- [ ] Make sure that the values of our position make more sense. Users do focus on these values and if two screens (immediately after each other) don't align we have unnecessary confusion and the user focuses on the wrong things. Notable in the `Buy` flow we have to make sure that the values align (it's market order, price aligns, ...); the closing should also be somewhat aligned.

Other notes, might need alignment:

- [ ] When the user tried to fund the stable sats wallet, the user tried to use the Stable Sats Wallet's `quick actions` that one sees when clicking the `Stable Sats Wallet` tile on the home screen. For the `Trading Wallet` we wired that into the funding workflow, but for the `Spending Wallet` we did not. 
Note: If this is not enabled on purpose, because the user should use `Move funds between wallets` then we should explicitly state that Otherwise we should allow funding from external.
- [ ] Make sure it is more clear that the user has to do a Market order. It's nice to show that Limit orders are possible, but it is somewhat unclear that one cannot do them. Maybe good enough to mention this.

**Comment by 1010Tom** [comment]
This was feedback on the old prototype and is obsolete now.
