### ISSUE TITLE
Play with the color gradient of the wallet

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#60]
Our current wallets look like this: 

<img width="609" alt="image" src="https://user-images.githubusercontent.com/224613/215404026-200e717f-bc2e-4a30-9a4e-0b2954005b64.png">

<img width="609" alt="image" src="https://user-images.githubusercontent.com/224613/215404055-9ca681c3-fc03-429c-8be3-2e0c3213af0f.png">

This ticket is about playing around with this gradient. 

For reference the initial feedback on this was that it is too colorful

**Comment by bonomat** [comment]
Note: please play with the styles: `WalletTileGradien_Yellow`

**Comment by da-kami** [comment]
To finally do something about this and close this Figma issue (for now) I opted to remove the Gradient and use the low-saturation colors that we used for the stable-sats mock. 

I updated the Figma mock accordingly.

For reference this is how the colors look:

![image](https://github.com/get10101/10101/assets/5557790/20336308-09ff-4766-ad06-5c848a632185)
