### ISSUE TITLE
Add on-boarding wizard

### ISSUE THREAD

**Issue by 1010Tom** [get10101/10101#61]
When starting the application for the first time we should greet the user with a friendly on-boarding wizard explaining what 10101 is all about .

Emphasis should be on the app being self-custodial; it's important that the user understand what that means and how awesome this is to have. 
DLCs on Lightning is what enables the self-custodial trading. We should mention that this is the first (and only) product for self-custodial trading on Bitcoin to date.

**Comment by da-kami** [comment]
We could consider adding this towards the end of Q3 if we consider to open up the application by then.
I'm happy to work on the mocks in one of the next iterations :)
