### ISSUE TITLE
Add a button to add funds on regtest

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#611]
Add a way of easily funding the app using public regtest.

We don't expect people to use our faucet.

**Comment by holzeis** [comment]
Is this necessary if we are asking users to tweet an invoice that we can pay? That would implicitly give us some more exposure on twitter.

On the other hand it might be hard to coordinate that payment as the user needs to be online at the same time we are paying the invoice.

**Comment by klochowicz** [comment]
> Is this necessary if we are asking users to tweet an invoice that we can pay? That would implicitly give us some more exposure on twitter.
> 
> On the other hand it might be hard to coordinate that payment as the user needs to be online at the same time we are paying the invoice.

I don't think the twitter idea was serious. It would be a severe hurdle for people about to use it, especially our current target audience.
