### ISSUE TITLE
iOS status bar is not visible

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#628]
We obscure the status bar, both on light and dark system theme.

![IMG_F4420D64634C-1](https://github.com/get10101/10101/assets/8319440/92c99d36-3b8d-460c-a75c-7b508c8efbc9)

Probably the best way is changing the background to purple (or a little lighter colour).

**Comment by bonomat** [comment]
Still relevant and potentially an easy ticket.

**Comment by holzeis** [comment]
Reopening this issue. As the status bar is still not visible on the latest version 1.2.3 (1937)

**Comment by klochowicz** [comment]
> Reopening this issue. As the status bar is still not visible on the latest version 1.2.3 (1937)

The status bar  was visible on an iphone 14 pro when testing today with local signing, but curiously not in the 10101 test app 🤔

**Comment by bonomat** [comment]
Mhm... 
it's definitely working for me right now in the simulator

![image](https://github.com/get10101/10101/assets/224613/42a377ab-9ad3-4e38-8524-baaa60008c87)

**Comment by bonomat** [comment]
No so fun fact : in this PR it did not work: https://github.com/get10101/10101/pull/1197

**Comment by bonomat** [comment]
For documentation reasons: this explains why this is happening: https://stackoverflow.com/questions/53819118/flutter-where-should-i-call-systemchrome-setsystemuioverlaystylesystemuioverla

**Comment by holzeis** [comment]
Fixed with https://github.com/get10101/10101/commit/3f708abf18fef4657d5758b80391227a7a1d18ed
