### ISSUE TITLE
Opening a new position on test ends up immediatly in a negative pnl

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#634]
It is weird that our positions opened on test do have immediately a negative pnl. This is different on mainnet. 

![Image](https://github.com/get10101/10101/assets/382048/2feaede1-5601-4404-848b-9e7df45a0a45)

**Comment by holzeis** [comment]
I believe this is because we are using the testnet quotes for our test setup.

```
Network::Mainnet => "www.bitmex.com".to_string(),
Network::Testnet => "testnet.bitmex.com".to_string(),
```

Does anything speak against using the mainnet bitmex quotes also for our test setup?

**Comment by luckysori** [comment]
> Does anything speak against using the mainnet bitmex quotes also for our test setup?

Give it a go and see if the experience is better. I'm all for it.

**Comment by holzeis** [comment]
Closing this ticket as it appears that it was simply a very volatile market that resulted into this.
