### ISSUE TITLE
Sync failed due to HTTP connection error (429 Too Many Requests)

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#658]
Using the blockstream.info we quickly run into rate limits, resulting into failed http request due to too many requests. This problem will only get worse, the more transaction we have to monitor.

![Image](https://user-images.githubusercontent.com/382048/239538438-be89ded3-6235-4829-83f0-df1f2403f6e2.png)

Some requests go through, but have a very bad response time of between 13 - 31 seconds.

![Image](https://user-images.githubusercontent.com/382048/239538299-ffee0b86-0a89-41bf-95f5-bb31219e1e53.png)

There are two approaches to address this issue. (Note, we might want to pursue both approaches) 

1. ~Debounce the esplora requests, to prevent running into a rate limit on the API. (also hoping that this will improve the response times)~
- [x] ~Add a delay of 250ms when syncing script hashes~

2. Setup our own public infrastructure to monitor the blockchain.
- [ ] #659 - In a first step we could circumvent the rate limit by setting up our own esplora instance and connect to a public electrs instance. This might though just move the error to esplora.
- [x] Setup Electrs & bitcoind - If running our own esplora against a public electrs instance does not resolve the issue, we will have to setup our own electrs and bitcoind instances.

**Comment by holzeis** [comment]
Removing MVP label as adding a delay of 250ms in between syncing script hash requests seemed to have fixed the issue.

**Comment by holzeis** [comment]
Adding MVP label again as the 250ms result in too long delay during wallet syncs. We need to setup our own esplora instance to circumvent that issue.

**Comment by bonomat** [comment]
Should have been resolved as we are now using our self-hosted esplora.
