### ISSUE TITLE
Setup mainnet esplora

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#659]
Setup our own mainnet esplora to address the issues mentioned in #658.

https://github.com/Blockstream/esplora

**Comment by bonomat** [comment]
I looked into it a bit. It is my understanding that the simplest way to do it is to run the [docker file directly](https://github.com/Blockstream/esplora/#how-to-run-the-explorer-for-bitcoin-mainnet) which also includes a bitcoind node.

**Comment by bonomat** [comment]
Done with https://github.com/get10101/10101/pull/1218
