### ISSUE TITLE
Follow-up work to #612

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#664]
Look at the PR description in https://github.com/get10101/10101/pull/612 for context.

This is primarily a reminder for myself that I don't want to forget about the corners we cut when working on #612.

**Comment by holzeis** [comment]
I am removing MVP as the (my) follow up remarks are definitely not critical for MVP :)

**Comment by luckysori** [comment]
[Tibo's recent updates](https://matrix.to/#/!YOUZSBmuJuaGzmxzaA:matrix.org/$Q9MYQy4v7LGbxZfibE2XZy-RYYo5KIlkVZkZjx3cOy4?via=matrix.org) to the forks we are using of `rust-dlc` and `rust-lightning` should be very relevant here.
