### ISSUE TITLE
Wallet history

### ISSUE THREAD

**Issue by 1010Tom** [get10101/10101#67]
Scope:

1. HistoryListItem in the "transaction history" list of the wallet. 
2. When clicking on one item details for the transaction should be shown. 
    - Please check https://github.com/get10101/10101/issues/66 for details!

The wallet's history consists of three different items (in order of importance to be implemented): 

- Lightning payments (send/receive)
- Trade related items; i.e. Filled orders - when we trade we basically move funds out of the wallet and lock it in a channel
    - Order that moves funds into the channel (i.e. opens / updates a position)
    - Order that moves funds back into the wallet (i.e. closes the position); we might want to add some metadata here, because these entries could serve as trade history for the time being :)
- Bitcoin transactions (send/receive)

The model that is exposed on the API should reflect this; I think it would be best to expose one complete history that is assembled internally.

This should include an extra screen/layover for the transaction details.

**Comment by da-kami** [comment]
It would be great if we can achieve a similar look and feel throughout all the list items - and have similar behavior for them when e.g. clicking on them. 

I propose three steps of information:

1. The list tile shows the most important information
2. When taping on the list tile, the tile [expands](https://pub.dev/packages/expandable) (downwards) to show additional information
3. (optional) we show a button `More details` when expanded that would jump to a child-screen with even more information.

For reference, the `PositionListItem` already has an `ExpandablePanel`, see https://github.com/get10101/10101/blob/main/mobile/lib/features/trade/position_list_item.dart

---

Look of the `OrderListItem`:

![image](https://user-images.githubusercontent.com/5557790/221098610-5524b108-84ba-415f-a88d-83a730c64850.png)

Ticket that tracks adding order information in `ExpandablePanel`: https://github.com/get10101/10101/issues/163

**Comment by da-kami** [comment]
Please refer to the detail mocks and explanation here: 

https://github.com/get10101/10101/issues/66#issuecomment-1442859824

If there are any questions please ping me here!

**Comment by da-kami** [comment]
basic version of wallet history is implemented.
