### ISSUE TITLE
Initial wallet sync in app takes 4 minutes

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#677]
Our initial splash screen of death it is due to the [initial wallet sync](https://github.com/holzeis/10101/blob/a6561ba547924fd7e2356c162bfbcf07da6ef455/mobile/lib/main.dart#LL292C7-L292C7): it takes about 4 minutes until everything is up and running

**Comment by bonomat** [comment]
Not a bug anymore but I think syncing shouldn't take 4 minutes 😅

https://github.com/get10101/10101/pull/679 makes it better but I'll leave it open for now.

**Comment by holzeis** [comment]
I think this can only be fixed by using bdk 1.0.0.

**Comment by bonomat** [comment]
This has been fixed.
