### ISSUE TITLE
Dropping connection without noticing?

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#681]
Weird thing is happening: 

I manually connected to a peer: 

```
curl -X POST -H "Content-Type: application/json" -d '{"pubkey": "031fe264e70b544b4469027ca557ce97bb3f1d0f3ed9e2f4c6565c2e942dad6a79", "address": "212.90.86.105:9735"}' http://localhost:8000/api/admin/connect -v
```

checked that the peer is connected with.

```
curl -X GET http://localhost:8000/api/admin/peers  | jq .
```

And after 1 minute or so I called it again and the connected peer is gone. 

Nothing in the logs indicates that the connection was lost.

**Comment by holzeis** [comment]
Closing this ticket, as it might be fixed with our deadlock fix. Please reopen if its happening again.
