### ISSUE TITLE
Make it clear where the sats for "funding" the stable sats wallet come from

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#7]
Currently it is unclear where the funds that are being `stabalized` are coming from.

---

My thoughts:

I think we have to add a specific `Move between wallets` screen to achieve this.
We can consider modelling this together with funding the wallet from an external wallet, which would basically mean that upon clicking `Receive` the user has to decide if they want to receive from another 10101 wallet or an external wallet.

**Comment by 1010Tom** [comment]
This was feedback on the old prototype and is obsolete now.
