### ISSUE TITLE
Model receive funds screen

### ISSUE THREAD

**Issue by 1010Tom** [get10101/10101#70]
Should be very similar to the initial funding screen. Only the wording should be slightly different.

**Comment by da-kami** [comment]
At the moment the Figma prototype does not distinguish between the initial funding step and receive screen. 
For the MVP I don't think it will be necessary to distinguish here, but we can see how it goes. I would not give this ticket a very high priority and come back to it later.

**Comment by da-kami** [comment]
I don't think we have to change this for the MVP - and potentially it can always be the same, just triggered from different places. 
I am closing this ticket for now, if you disagree please re-open @1010Tom
