### ISSUE TITLE
Receive funds

### ISSUE THREAD

**Issue by 1010Tom** [get10101/10101#71]
should use the same as https://github.com/get10101/10101/issues/69 just with a different wording. 

Depends on https://github.com/get10101/10101/issues/70

Sub tickets:
- [x] https://github.com/get10101/10101/issues/178
- [ ] https://github.com/get10101/10101/issues/180
- [x] https://github.com/get10101/10101/issues/195

// edit: added sub ticket link

**Comment by da-kami** [comment]
I don't really understand what makes this ticket different than #70 - is this supposed to be for on-chain?
I assigned myself to both tickets for now :)

**Comment by bonomat** [comment]
> I don't really understand what makes this ticket different than #70 - is this supposed to be for on-chain? I assigned myself to both tickets for now :)

Sorry for late reply, #70 was only about modelling the flow in our figma mocks (see the label?) while this ticket here is about implementing it

**Comment by bonomat** [comment]
Closed in favor of: https://github.com/get10101/10101/issues/215
