### ISSUE TITLE
Too Many Requests-Sync failed due to HTTP connection error Too Many Requests

### ISSUE THREAD

**Issue by AravindVikram** [get10101/10101#710]

**Comment by AravindVikram** [comment]
connection error

**Comment by bonomat** [comment]
Hi @AravindVikram , thank you for creating this ticket. We will look into it.

**Comment by holzeis** [comment]
@AravindVikram You did not provide a lot of context, but I guess this might be related to this ticket?

https://github.com/get10101/10101/issues/658

**Comment by holzeis** [comment]
This is still happening and depends on us running an esplora instance.

**Comment by holzeis** [comment]
still happening.. we have now a synced esplora instance, once this is hooked up in production we can close that ticket.

**Comment by holzeis** [comment]
@bonomat Assigning this ticket to you since you are working on setting up esplora on our production environment.

**Comment by bonomat** [comment]
- [ ] setup coordinator
- [ ] update build settings for app
