### ISSUE TITLE
Share on twitter encourages the user to close the app while an order is executed

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#714]
Although our app should be able to withstand a lost in connection during order execution, it's still a bit risky to provoke that behavior actively through the app.

Ideally we ask the user to share on twitter once the order has been executed.

**Comment by klochowicz** [comment]
I would have just hid the button for now if it causes any problems. 
Later makes no sense, because we might need to put more effort into it than it's worth 🤔

**Comment by bonomat** [comment]
We could just add the button to the open position and leave it there at all times.

**Comment by holzeis** [comment]
We should probably improve the UX here so that the users understands that the order is in filling and the app should not be closed. On the successful execution, the user could get a notification that the position has been opened - here the user could share on twitter.

**Comment by Restioson** [comment]
> On the successful execution, the user could get a notification that the position has been opened - here the user could share on twitter.

By notification, do you mean a system notification like a push notification or some other app feedback?

**Comment by Restioson** [comment]
Maybe it would make sense to forbid the user from leaving the order creation screen while it is being filled, if this could cause problems? Some kind of progress bar (one of the ones that is stripy and just moving to indicate no absolute amount of progress) could be used to indicate that the app is busy doing something and shouldn't be closed. This depends on how long it might take the order to be filled, though. I just think that personally, as a user, I don't expect _not_ to be able to close the app after clicking the confirm order button. To me, that seems "done".

**Comment by Restioson** [comment]
Looks like we can use [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) to send a local notification after an order is filled, if we want, but it is quite verbose and a lot of set up if this is the only use-case for it

**Comment by holzeis** [comment]
I like the idea of informing the user that the order is still being executed and the popup / app should not be closed while its in execution.

I think we did it the other way initially, because we couldn't guarantee that you will get a match immediately. But this is how we currently do it. Either you have a match immediately or the order goes to failed.

So yeah, lets do it how you suggested! 👍

**Comment by holzeis** [comment]
In regards to the notification, I originally thought of an overlay popup similar to the order successfully submitted notification.

**Comment by bonomat** [comment]
> I guess what I mean is that after I see this big green check and "submit order success" with a close button, I think that I can immediately close the app, since it doesn't convey that anything is still 'in progress'. That's what this is communicating to me as a user.
> After the order is filled, the same screen could replace the loading bar/spinner with a share button and the success display.

Afair the initial reason for going with the current approach was because of technical reasons: we did not have the events in place yet to be able to tell the app to close the dialog. That being said, I think it's a good idea. Let's go for it :)
