### ISSUE TITLE
Failing test: `ln_collab_close`

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#717]
Probably because of our tendency to skip CI due to #355, we have introduced a regression which causes the `ln_collab_close` test to fail, as reported by @klochowicz in #715.

I was able to reproduce this by running

```
cargo test -p ln-dlc-node -- tests::just_in_time_channel::channel_close::ln_collab_close --exact --ignored
```

which runs into

```
thread 'tests::just_in_time_channel::channel_close::ln_collab_close' panicked at 'assertion failed: `(left == right)`
  left: `1000`,
 right: `0`', crates/ln-dlc-node/src/tests/just_in_time_channel/channel_close.rs:77:5
```

This happens because we are mining an unexpected number of blocks. The test has always only mined:

- 1 block to fund the coordinator's on-chain wallet.
- 1 block to confirm the close transaction.

Somehow I get 4 extra blocks some time after mining the first one.

The logs only show one instance of

```
2023-05-31T06:20:43.353410Z DEBUG ln_dlc_node::tests::bitcoind: Mining n_blocks=1
```

which appears to match the explicit call to `bitcoind::mine` when funding the coordinator.

**Comment by klochowicz** [comment]
@luckysori I've opted for the simple "fix" right now, as it's more important to have the test running and checking than fixing the test code. 
It would be good to understand *why* we mine additional blocks though.

**Comment by klochowicz** [comment]
I believe that I found the problem, whilst hunting down other things: #722
