### ISSUE TITLE
Failed to submit order: Could not post order to orderbook

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#759]
Currently the maker only sends a new order upon receiving a new quote from bitmex. These orders are only valid for 1 minute, if the orders are quickly taken, users will have to wait some time to get the next order. The more users are on the system the more congestion we will get.

For our test setup we can certainly improve that experience easily, by e.g. simply creating multiple orders. How we want to deal with mainnet may require more thought though. (as we are currently not hedging our trades, we may have to limit the number of orders anyways)

**Comment by holzeis** [comment]
The following two might be viable approaches for fixing that.

1. Find a match upon posting a limit order
2. Post multiple orders e.g. 10x long and 10x short.

**Comment by klochowicz** [comment]
we could also create a new order as soon as we know the previous one got taken, like we've done in ItchySats?

**Comment by klochowicz** [comment]
test

**Comment by klochowicz** [comment]
@holzeis I went with the simplest solution for the time being, until we have more comprehensive tests. 5x (long,short) pairs being created (the number is configurable).
