### ISSUE TITLE
Do not use remote oracle for testing

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#763]
We should either mock the oracle or use a test oracle running locally. This is to ensure that our testing (such as CI) is not blocked by the public test oracle being unavailable.

**Comment by klochowicz** [comment]
That would be great. I could not run the test without internet recently :( 

@holzeis, would you mind sharing the docker compose file for the oracle? 
I've got some changeset locally to allow passing in the oracle address and pk, it should be quite trivial to remove this dependency.
