### ISSUE TITLE
Can't fund wallet through just in time channel

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#764]
On regtest we get regularly no route issues due to `no hop data found` errors. This seems to happen not deterministically, meaning that sometimes it works right away and sometimes it doesn't.

The assumption is that upon opening a channel a node announcement of some sorts needs to happen for the payment to get successfully routed.

This is very likely also the issue that our `onboard_from_lnd` is failing every now and then.

**Comment by bonomat** [comment]
Related to https://github.com/get10101/10101/issues/774

**Comment by holzeis** [comment]
Note, in production this issue seems to be solely related to our liquidity or connectivity.

**Comment by klochowicz** [comment]
All end-to-end tests use the funding step now on regtest, let's monitor whether they fail at all due to this issue - I will update it if I spot any failures due to this reason.

**Comment by klochowicz** [comment]
I managed to replicate the issue for `no_route` when paying an invoice *after* the funding (see: #880 )

**Comment by bonomat** [comment]
> From #999:
> 
> This consistently fails on an android emulator for me. Invoice is still payable manually using the faucet. ![image](https://user-images.githubusercontent.com/6688948/255915992-0abd64b7-68d3-46ab-abed-be904b03cd46.png)

Does it work for you natively?

**Comment by Restioson** [comment]
> Does it work for you natively?

Yes, it does

**Comment by bonomat** [comment]
Very interesting. Thanks for sharing.

**Comment by holzeis** [comment]
@Restioson can you check the nodeinfo on the lnd node? Is synced_to_graph true?

**Comment by Restioson** [comment]
In my case, it actually _was_ an android setup issue, since in android the REGTEST_FAUCET environment variable is not set up correctly
