### ISSUE TITLE
Upgrade to latest `rust-dlc` and `rust-lightning`

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#768]
With our debugging frenzy around https://github.com/get10101/10101/issues/692 we diverged significantly from upstream[^1] `rust-dlc` and `rust-lightning`.

We introduced our own fix in https://github.com/get10101/10101/pull/756, but since then Tibo has already fixed the same issue on latest `rust-dlc` and `rust-lightning`. By upgrading to latest, we will also be able to use the latest API for force-closing LN-DLC channels, as well as get some fixes surrounding that use-case. Furthermore, we will re-introduce some other fixes related to reconnecting during a DLC channel protocol.

[^1]: By upstream we of course mean the branches and forks maintained by Tibo.

**Comment by holzeis** [comment]
@luckysori can you point me to tibos fix of the deadlock? I am a bit worried of a regression, removing our fix (that proved to be working) for a different fix.
