### ISSUE TITLE
Upgrade to `bdk:1.0.0-alpha.6`

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#788]
The main reason is so that we can rewrite our on-chain wallet to not block every operation when the sync is on-going.

Then we can safely tackle #1750.

**Comment by klochowicz** [comment]
Blocked until it's released (hopefully soon, as PRs are open and only await reviews)

We can see the progress of the milestone here:
https://github.com/orgs/bitcoindevkit/projects/14

**Comment by luckysori** [comment]
I think we can start working on this already, even if the release isn't ready yet. Other projects such as Mutiny have already updated to a recent patch.

I'm removing the `blocked` label. Feel free to disagree and put it back on.

**Comment by klochowicz** [comment]
I agree that's not blocked; however yesterday we have agreed this is not our immediate priority.

**Comment by luckysori** [comment]
> I agree that's not blocked; however yesterday we have agreed this is not our immediate priority.

Yeah, we don't have to add it to the iteration straight away.

**Comment by luckysori** [comment]
Almost ready: https://github.com/p2pderivatives/rust-dlc/pull/141.

**Comment by klochowicz** [comment]
> Almost ready: [p2pderivatives/rust-dlc#141](https://github.com/p2pderivatives/rust-dlc/pull/141).

🤔are you sure you linked the right ticket? the one you mentioned is about LDK, not BDK

**Comment by luckysori** [comment]
I somehow thought this ticket depended on a newer version of LDK, but I don't think that's right.

I do think we want this so at least removing the stale label is still correct :D

**Comment by bonomat** [comment]
Wait for https://github.com/get10101/10101/issues/710 and see if the situation got improved.

**Comment by luckysori** [comment]
See #1750.

**Comment by holzeis** [comment]
Probably needed to fix https://github.com/get10101/10101/issues/1960

**Comment by bonomat** [comment]
We will need to switch to master of rust-dlc

**Comment by Restioson** [comment]
It may be best if we can get this before we look at getting a finished, fully-integrated WASM build. Otherwise, we will be stuck adapting our use of BDK to WASM twice - once in 0.28, and once in 1.0.0-alpha.5. It seems like there has been a decent number of changed since then so if it could be avoided that'd be good.

For now this isn't on the critical path for WASM as we still need to implement a WASM friendly DB.
