### ISSUE TITLE
Panic on reading scorer from disk

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#797]
My app started to crash after a restart because the scorer file was broken.

xcode://organizer/crashes/downloadPoint?adamId=1671686549&platformId=iOS&installPlatformId=iOS&analyticsPointId=DUp8-dcHhayUiR7pI4Hsm&bundleId=finance.get10101.app

Luckily this can be easily fixed by simply deleting the scorer file.

**Comment by klochowicz** [comment]
it might be a good idea to automatically delete the file if it's corrupt!

**Comment by holzeis** [comment]
happened to me again! had to manually delete the scorer file

**Comment by Restioson** [comment]
> xcode://organizer/crashes/downloadPoint?adamId=1671686549&platformId=iOS&installPlatformId=iOS&analyticsPointId=DUp8-dcHhayUiR7pI4Hsm&bundleId=finance.get10101.app

I don't have xcode; is there a way to view this on linux?

**Comment by holzeis** [comment]
> it might be a good idea to automatically delete the file if it's corrupt!

How would you check if the file is corrupt? The panic is thrown when trying to read the file. I could "catch" the panic with https://doc.rust-lang.org/std/panic/fn.catch_unwind.html. But the docs also say that this will not catch any panic.

> Note that this function might not catch all panics in Rust. A panic in Rust is not always implemented via unwinding, but can be implemented by aborting the process as well. This function only catches unwinding panics, not those that abort the process.

Anyhow handling the panic is only patching the symptom and not fixing the issue.

**Comment by holzeis** [comment]
I think the issue comes down to the FilesystemPersister implementation, which should hopefully get fixed with https://github.com/get10101/10101/issues/831

**Comment by da-kami** [comment]
> I think the issue comes down to the FilesystemPersister implementation, which should hopefully get fixed with #831

Since this ticket is still part of the iteration: Is it worth to implement a workaround for now that e.g. deletes the file if we detect it is corrupted?
We could also just change to SQLite, might be better invested time...

**Comment by holzeis** [comment]
I think so too.. lets fix it by implementing a `DatabasePersister` 👍

**Comment by klochowicz** [comment]
I'm not sure how deep anyone has analyzed the crash log, but Scorer should create a new one if it can't read for whatever reason.
If it crashed, it likely points to a bug in LDK or other upstream library. I'm not that sure whether changing the way we persist would improve anything.

**Comment by klochowicz** [comment]
Unassigning myself due to ticket no longer being part of the iteration.

**Comment by klochowicz** [comment]
Findings that I've done so far:
- upon failure when reading from file, we should have created a new one.... (should not panic!)
- the backtrace attached by @holzeis points to a panic in `Duration`, which is super weird. I could not even track the exact spot where it fails, but I haven't dug deep.

**Comment by bonomat** [comment]
I can reproduce this error locally with prod-environment on my phone: 

```
2023-07-12T14:06:26.912975Z  INFO native::logger: Initialized logger
flutter: | 2023-07-12 16:06:27.225 | LogLevel.INFO | Initialized logger
flutter: | 2023-07-12 16:06:27.282 | LogLevel.INFO | App has already data in the seed dir. For compatibility reasons we will not switch to the new app dir.
flutter: | 2023-07-12 16:06:27.282 | LogLevel.INFO | App data will be stored in: /var/mobile/Containers/Data/Application/BFE4D7F4-EB60-4444-B316-317BE9C67DCD/Library/Application Support
flutter: | 2023-07-12 16:06:27.282 | LogLevel.INFO | Seed data will be stored in: /var/mobile/Containers/Data/Application/BFE4D7F4-EB60-4444-B316-317BE9C67DCD/Library/Application Support
2023-07-12T14:06:27.287989Z DEBUG native::config::api: Parsing config from flutter config=Config { coordinator_pubkey: "022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156", esplora_endpoint: "https://blockstream.info/api", host: "34.30.20.202", p2p_port: 9045, http_port: 80, network: "mainnet", oracle_endpoint: "http://127.0.0.1:8081", oracle_pubkey: "16f88cf7d21e6c0f46bcbc983a4e3b19726c6c98858cc31c83551a88fde171c0" }
2023-07-12T14:06:27.301295Z DEBUG native::db: Database migration run - db initialized
flutter: | 2023-07-12 16:06:27.311 | LogLevel.DEBUG | Parsing config from flutter config: Config { coordinator_pubkey: "022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156", esplora_endpoint: "https://blockstream.info/api", host: "34.30.20.202", p2p_port: 9045, http_port: 80, network: "mainnet", oracle_endpoint: "http://127.0.0.1:8081", oracle_pubkey: "16f88cf7d21e6c0f46bcbc983a4e3b19726c6c98858cc31c83551a88fde171c0" }
flutter: | 2023-07-12 16:06:27.314 | LogLevel.DEBUG | Database migration run - db initialized
2023-07-12T14:06:27.314771Z DEBUG native::event::event_hub: Publishing event Init("Starting full ldk node")
flutter: | 2023-07-12 16:06:27.331 | LogLevel.DEBUG | Publishing event Init("Starting full ldk node")
2023-07-12T14:06:27.41475Z  INFO ln_dlc_node::on_chain_wallet: Creating the wallet network=Bitcoin
flutter: | 2023-07-12 16:06:27.415 | LogLevel.INFO | Creating the wallet network: Bitcoin
Installing and launching...                                        28.8s
2023-07-12T14:06:27.663803Z  INFO ln_dlc_node::ldk_node_wallet: Started on-chain sync
flutter: | 2023-07-12 16:06:27.664 | LogLevel.INFO | Started on-chain sync
2023-07-12T14:06:27.89505Z ERROR native::api: Aborting after panic in task info=panicked at 'overflow when subtracting duration from instant', library/std/src/time.rs:424:33
flutter: | 2023-07-12 16:06:27.895 | LogLevel.ERROR | Aborting after panic in task info: panicked at 'overflow when subtracting duration from instant', library/std/src/time.rs:424:33
   0: std::backtrace::Backtrace::create
   1: native::api::run::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::option::expect_failed
   8: <std::time::Instant as core::ops::arith::Sub<core::time::Duration>>::sub
   9: <lightning::routing::scoring::ChannelLiquidity<T> as lightning::util::ser::Readable>::read
  10: <T as lightning::util::ser::MaybeReadable>::read
  11: <std::collections::hash::map::HashMap<K,V> as lightning::util::ser::Readable>::read
  12: <lightning::routing::scoring::ProbabilisticScorerUsingTime<G,L,T> as lightning::util::ser::ReadableArgs<(lightning::routing::scoring::ProbabilisticScoringParameters,G,L)>>::read
  13: ln_dlc_node::disk::read_scorer
  14: ln_dlc_node::node::Node<S>::new
  15: ln_dlc_node::node::Node<S>::new_app
  16: native::ln_dlc::run::{{closure}}
  17: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  18: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
  19: tokio::runtime::park::CachedParkThread::block_on
  20: tokio::runtime::context::BlockingRegionGuard::block_on
  21: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  22: tokio::runtime::runtime::Runtime::block_on
  23: native::ln_dlc::run
  24: native::api::run
  25: native::api::run_in_flutter
  26: native::bridge_generated::bridge_generated::wire_run_in_flutter_impl::{{closure}}::{{closure}}
  27: <flutter_rust_bridge::handler::ThreadPoolExecutor<EH> as flutter_rust_bridge::handler::Executor>::execute::{{closure}}::{{closure}}
  28: std::panicking::try::do_call
  29: ___rust_try
  30: std::panicking::try
  31: std::panic::catch_unwind
  32: <flutter_rust_bridge::handler::ThreadPoolExecutor<EH> as flutter_rust_bridge::handler::Executor>::execute::{{closure}}
  33: <F as threadpool::FnBox>::call_box
  34: threadpool::spawn_in_pool::{{closure}}
  35: std::sys_common::backtrace::__rust_begin_short_backtrace
  36: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
  37: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  38: std::panicking::try::do_call
  39: ___rust_try
  40: std::panicking::try
  41: std::panic::catch_unwind
  42: std::thread::Builder::spawn_unchecked_::{{closure}}
  43: core::ops::function::FnOnce::call_once{{vtable.shim}}
  44: std::sys::unix::thread::Thread::new::thread_start
  45: <unknown>

```

**Comment by klochowicz** [comment]
thanks for the logs @bonomat - it's more detailed than what we had from TestFlight.
This seems to point to a bug in rust-lighting; perhaps we should report it? If for some reason we can end up with partial data that then is can cause an overflow on read, one simple solution would be to use `checked_sub` instead of panicking, and returning an error....

**Comment by bonomat** [comment]
At least 2 users have reported that their app is crashing and can't be started anymore. I believe it still has to do with the scorer. Let's go for the other solution I was proposing and roll out a new version asap.
