### ISSUE TITLE
Add separators to min/max/recommended fund amount

### ISSUE THREAD

**Issue by Restioson** [get10101/10101#803]
Similar to how `AmountText` separates by `,`, we should separate these too, otherwise it is very difficult to see what these mean: 
![image](https://github.com/get10101/10101/assets/6688948/893d9207-0c6f-4bfb-8572-4cbe45c28954)

**Comment by klochowicz** [comment]
Alternatively, we could just say e.g. "50k sats" ?

**Comment by klochowicz** [comment]
it would be good that the solution could be scalable to tackle formatting on the wallet history and the top screen, e.g. right now we use the `k` suffix in the history,.

**Comment by Restioson** [comment]
The solution in #813 is using the same formatting as AmountText; I think if we want to use `k` everywhere that's where it should be implemented. Or are there cases where we want more precision?
