### ISSUE TITLE
Customise separators for AmountText

### ISSUE THREAD

**Issue by Restioson** [get10101/10101#804]
`AmountText` currently seems to force `,` as the thousands separator and `.` as the decimal separator. While this is the international convention, in some locales (such as South Africa, for example :sweat_smile:) other conventions are used. For instance, here, a space is used for thousands separator, while `,` is used for decimals. For example, 100 000,234453 would be currently formatted as 100,000.234453 by 10101 (particularly, the comma as thousands separator looks very weird to me). It's not too confusing since a lot of South Africans prefer to just set the system format to `.` anyway since some software doesn't know about the comma as separators, but it still might be nice to have for better localisation.

**Comment by klochowicz** [comment]
I would put it down the list after we localise the app itself - for the MVP I would say we should stick to a single convention for as long as we can.

I guess the same goes for dates / times formatters? 
- for a lot of countries, 24h convention on the candlestick can be confusing. 
- wallet / trade history will have to use dates and times, and they vary *a lot*
