### ISSUE TITLE
Replace file storage with sql database

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#831]
We are using disk storage in multiple places.

 - [ ] bdk wallet
 - [ ] rust-dlc
 - [ ] rust-lightning covered with #797 

This ticket might need to be split up for each individual component.

**Comment by klochowicz** [comment]
🤔 are you referring to `sled` db as file storage in some of the items listed above?

**Comment by holzeis** [comment]
> 🤔 are you referring to `sled` db as file storage in some of the items listed above? 
> 

Yes

**Comment by klochowicz** [comment]
> > 🤔 are you referring to `sled` db as file storage in some of the items listed above?
> 
> Yes

but sled is a database, not file storage....

**Comment by holzeis** [comment]
We could think about implementing a Database Persister for `rust-lightning`, but it would still remain a key value store, which is not suitable for postgres. Instead, we will probably need a no-sql database for that.

Closing this ticket as not planned at the moment.
