### ISSUE TITLE
Allow force-close of LN-DLC channel at any point

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#842]
Once https://github.com/p2pderivatives/rust-dlc/issues/113 is fixed we can update to latest `rust-dlc#ln-dlc-channels` to be able to force-close channels in practically every state.

This update _will_ include breaking changes to `rust-dlc` data models, so subchannels opened before the update will not be deserialisable after the update.

**Comment by luckysori** [comment]
Tibo is currently working on this on our behalf.

**Comment by klochowicz** [comment]
@luckysori reckons that we should wait first until Tibo adds new states for rust-dlc, as that work is well underway.
