### ISSUE TITLE
Manual publication of spendable outputs claim TX via app

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#848]
We have at least one instance of a user who ran into #798.

To recover their funds I think we need to serialize the `SpendableOutputDescriptor` printed in the logs and feed it back to their app so that it can publish the corresponding claim transaction. For this we will need to add a kind of dev tool that can accept the serialized descriptor to then call `spend_spendable_outputs` on it and broadcast the transaction.

Such functionality could appear in a `Dev tools` tab that doesn't currently exist.

**Comment by holzeis** [comment]
I wouldn't bother with that issue as #844 should allow us to publish any missed `spendable_outputs` in the future. The effort invested in implementing that for only one case does not stand to comparison with the lost money.

As such I suggest to close that ticket.

**Comment by luckysori** [comment]
Fair enough, I tend to agree!
