### ISSUE TITLE
Show realized pnl upon successfully closing a position

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#871]
Currently we are showing a unrealized pnl on a successfully closed position. That should actually be the realized pnl.

![Image](https://user-images.githubusercontent.com/382048/250012820-28e7ebaf-d504-4865-8a59-bc11ea4cdaf1.png)

**Comment by da-kami** [comment]
I think the easiest solution is to just rename `Unrealized P/L` to `Realize P/L` if we are in a closing scenario - I am not sure the app is aware of which scenario it is though.

---

We can also solve this by calculating the realized P/L based on the execution price of the order. But I am not sure it's worth doing this before we cleanup the model (see below...).

---

To *really* solve this I think we would have to cleanup the model properly - the position should be closely coupled to the DLC (i.e. subchannel).

My vision for this is to only have sub-channels and load meta-data for them from our database.
Our database then does not contain any position "state" (such as opened, closed...) but this always comes from the DLC. The database however would contain any metadata that the DLC does not store itself, but we load this metadata base on the DLC.
This should include the proper association of the DLC (and position metadata) to it's orders.

**Comment by da-kami** [comment]
see: https://github.com/get10101/10101/issues/895

**Comment by Restioson** [comment]
Assigning my self for #897; further work as per @da-kami's comment I'm not sure I can do on my own since I'm still a little unfamiliar with how the Rust side of 10101 works. I can try it with some mentorship though if it's not too time critical
