### ISSUE TITLE
Add transaction details to transactions in wallet history

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#872]
Upon clicking a transaction one should see some details to the transaction. There are different types of transactions for which a details view is required.

- [ ] On chain transaction (potentially add a link to mempool)
- [ ] Off-chain transaction (payment or received)
  - [ ] Invoice description (moved from #886)
- [ ] Position transaction (open and close)
- [ ] JIT Channel opening fee (potentially add a link to the funding transaction on mempool)
- [ ] Order matching fee

Figma mock: 

https://www.figma.com/file/Sr3SfZ46sZstKjSwftmTtc/10101-v1-(incl-bitcoin.design)?type=design&node-id=7375%3A45885&mode=design&t=tFOk1Qr2JvlNIaBY-1

E.g. like this

https://github.com/get10101/10101/assets/224613/1e989c69-6ba3-4c32-9117-f7f2ba850024

**Comment by Restioson** [comment]
With reference to the 'fee' row in the lightning payment example - is it not the case that lightning fees are per-channel and not per-transaction?

**Comment by holzeis** [comment]
> With reference to the 'fee' row in the lightning payment example - is it not the case that lightning fees are per-channel and not per-transaction?

You are paying fees for outgoing transactions. The amount of fees is defined through the route (channels) you are using.

**Comment by Restioson** [comment]
> > With reference to the 'fee' row in the lightning payment example - is it not the case that lightning fees are per-channel and not per-transaction?
> 
> You are paying fees for outgoing transactions. The amount of fees is defined through the route (channels) you are using.

Ah, I see, thanks!

**Comment by Restioson** [comment]
Do we want to model other timestamps than just the time we 'first learned' about this payment? E.g invoice creation timestamp

**Comment by Restioson** [comment]
With #1213, we will model all information required to fulfill this ticket. Now, onto prettifying it as per the Figma :)

**Comment by Restioson** [comment]
Nit on figma: "you sent -1000" sats would imply that you _received_ 1000 sats, wouldn't it? Maybe we can convey this in a different way?

**Comment by Restioson** [comment]
> Nit on figma: "you sent -1000" sats would imply that you _received_ 1000 sats, wouldn't it? Maybe we can convey this in a different way?

Thought: we could have outgoing transactions have red amount text and incoming have green?
