### ISSUE TITLE
Cannot open new position in app

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#881]
When trying to open a new position I get the following error: 

```
Failed to execute trade for order Some(c0076864-9fe3-4d71-80ab-1b6c9896e138): TradeResponse: Could not post trade to coordinator: {"error":"Could not handle trade request: Could not propose dlc channel: Invalid state: Received sub channel offer but a non closed sub channel already exists"}  
```

- Version: 1.0.20
- Build: 1376
- Node id: `0380c43e047ff232e5171dbf01e551963f07488c067a3cdd03d9b86ddbdbe00f85`

**Comment by bonomat** [comment]
Might be related to https://github.com/get10101/10101/issues/399 and https://github.com/get10101/10101/issues/310 which allegedly was fixed in https://github.com/get10101/10101/pull/484

**Comment by bonomat** [comment]
I upgraded my app to 1.0.21 and was able to open a new position.

**Comment by holzeis** [comment]
@bonomat I am closing this ticket as you got it working again. Please reopen if there is still something to action.
