### ISSUE TITLE
Position model based on the DLC with associated orders

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#895]
Recently this topic came up several times, so I decided to create a ticket that sums my vision up:

In ItchySats we always had the problem that the application state was independent of the actual DLC state - and it could diverge leading to a "wrong state" when displaying information.

In 10101 we should overcome this by:

Only have sub-channels and load meta-data for them in our database.
Our database then does not contain any position "state" (such as opened, closing...) but this always comes from the DLC. 
The database however would contain any metadata that the DLC does not store itself, but we load this metadata base on the DLC.
This should include the proper association of the DLC (and position metadata) to it's orders.

I imagine this when we load positions:

1. We load the subchannel data first
2. We load the metadata associated with the subchannel based on the subchannel-id
3. Depending on the state of the subchannel we might do different calculations
4. We build the position objects and and provide them to the application

What does this mean for the creation lifecycle of a position:

1. An order gets matched
2. We request execution
5. Once the order was filled we safe the metadata of the position associated to the subchannel-id. Additionally we associate the order with this metadata in our database.

At the moment we base the position creation / deletion on channel messages being exchanged (i.e. the finalized messages). 
I think this model is OK to *trigger* doing something, but we should act based on the subchannel *state* rather than on the messages. So, we should load the state once a message happend and then act.

**Comment by da-kami** [comment]
CC @luckysori @holzeis 

Please have a look when you have a time - I think we should refine this and start working on it soon - the shortcuts in the current model will become problematic soon :)

**Comment by holzeis** [comment]
see also https://github.com/get10101/10101/issues/530

I think that's a technical debt that we should address. However, I don't see an immediate need for that - the referenced tickets are not critical to justify tackling this immediately. Do you see any immediate issues from our current design that will prevent us achieving our Q3 goal?

**Comment by da-kami** [comment]
Since this is basically a duplicate of #530 I'll close this ticket.

@luckysori if you want to incorporate any of the information I collected here into #530 please do so.

---

@holzeis :

> However, I don't see an immediate need for that - the referenced tickets are not critical to justify tackling this immediately. Do you see any immediate issues from our current design that will prevent us achieving our Q3 goal?

I agree, but I would advise not to push this out for too long. If it won't get priority in Q3 I would recommend to at least do it in Q4.

Note that properly associating the `Order` to the `Position` could be done separately as well.

I think at the moment model changes are still a quite low hanging fruit to fix/change. It might become harder if we built on top of the wrong model for longer.
Additionally, cleaning up this model may change our view on the feature scope of https://github.com/p2pderivatives/rust-dlc
