### ISSUE TITLE
Got a message for a channel from the wrong node! 

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#902]
Weird looking error in production: 

```bash
Got a message for a channel from the wrong node! No such channel for the passed counterparty_node_id 02e12fea95f576a680ec1938b7ed98ef0855eadeced493566877d404e404bfbf52
```

I looks like the channel was force-closed because of this. 

https://itchysats.grafana.net/goto/K3N9-LrVg?orgId=1

**Comment by bonomat** [comment]
Unfortunately I'm not sure what happened here. It could be that this was not our fault. I've tried to reach out to the other user but can't be sure that we get a response.

**Comment by luckysori** [comment]
Could it be that they changed their seed but kept the channel data around?

**Comment by holzeis** [comment]
> Could it be that they changed their seed but kept the channel data around?

I doubt it, the node has quite some channels open.

> Unfortunately I'm not sure what happened here. It could be that this was not our fault. I've tried to reach out to the other user but can't be sure that we get a response.

I guess it can always happen that somebody force closes on us. It's unfortunate, but lets see if we get a response. If not, I would close that ticket at the end of this iteration.

**Comment by bonomat** [comment]
We never got a response and don't know what happened.
