### ISSUE TITLE
`Open` label on the position is confusing

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#903]
User feedback: 

> This is a minor wording issue: "Open" in the UI expands this box, but could also indicate this position is open/active. "Expand" or "View Details" would avoid the confusion.

As we can see, `open` was confusing to the user. 

Given we don't have `closed` positions, I propose to simply remove this label.

**Comment by klochowicz** [comment]
are you sure we don't want to keep closed positions for historical reasons? I always found it very useful to be able to see through historical positions, and how they went. (wallet history does not substitute it, because we there might be other transactions in between the open / close position ones).

**Comment by holzeis** [comment]
I think this ticket is not about whether we want to keep a history of positions, but that the label on top of the position card (open) currently doesn't make much sense. Removing that label is easy and can be done quickly.

I would create a separate ticket for showing a history of closed positions.

**Comment by bonomat** [comment]
> are you sure we don't want to keep closed positions for historical reasons? 

In the danger of starting a whole new discussion: 

In the concept of a combined position I don't see a `closed position` being a useful thing. What you want to see is your trade executions, ideally with PnL per trade. The original idea was to show this kind of information in the `History` tab which has been removed from the scope for now.

**Comment by klochowicz** [comment]
> > are you sure we don't want to keep closed positions for historical reasons?
> 
> In the danger of starting a whole new discussion:
> 
> In the concept of a combined position I don't see a `closed position` being a useful thing. What you want to see is your trade executions, ideally with PnL per trade. The original idea was to show this kind of information in the `History` tab which has been removed from the scope for now.

that would work indeed! thank you for the explanation, it makes sense.

**Comment by klochowicz** [comment]
this seems to be fixed in the issue linked above.
