### ISSUE TITLE
Exception thrown when interacting with trade bottom sheet

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#905]
Every time we edit the quantity or the margin on the trade bottom sheet, we get the following message in the logs:

```
Another exception was thrown: setState() or markNeedsBuild() called during build.
```

We appear to be doing something wrong, even if it doesn't fully blow up.

---

Reproducible on Linux by running `just run`.

**Comment by bonomat** [comment]
I think this is a known error right @da-kami ?

**Comment by luckysori** [comment]
Oh yeah, I somehow failed to find https://github.com/get10101/10101/issues/402 when I searched before.

It has been closed automatically so I guess we don't want to look into this at the moment. I will close this one too then.
