### ISSUE TITLE
Charge order-matching fee for limit orders

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#910]
In https://github.com/get10101/10101/issues/838 we mentioned an order-matching fee for the maker. PR https://github.com/get10101/10101/pull/863 only dealt with the app side.

The example value suggested for the maker was `0.15%`, half of the taker's.

For now only the maker binary should be able to create limit orders, which is why this topic is also known as the "order-matching fee for the maker".

**Comment by da-kami** [comment]
For me this means that the coordinator will have to distinguish how much to charge each party involved in the trade.
I suppose the decision can be based on the order type - if it is a limit order the fee will be different than if it is a market order.

I would avoid talking about maker and taker if it can be avoided and rather just use e.g. the order type as criteria which implies maker and taker.

**Comment by bonomat** [comment]
Yes, the maker will need a channel with the coordinator to pay this fee.

**Comment by bonomat** [comment]
depends on https://github.com/get10101/10101/issues/926

**Comment by luckysori** [comment]
I think we still want this eventually.
