### ISSUE TITLE
Show user if the coordinator is offline

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#915]
If the coordinator is offline the app is practical only in view mode usable, but the user does not get any information about that.

We should show that the coordinator is offline and disable functionalities like 
- send & receive payment
- open or closing a position

The force close channel button should always be enabled though, informing the user that she has always a way out.

**Comment by klochowicz** [comment]
Closely related to https://github.com/get10101/10101/issues/860

as for force-close channel button - I thought it's not enabled on mainnet?

**Comment by holzeis** [comment]
> as for force-close channel button - I thought it's not enabled on mainnet?

not yet, but it should be considered when implementing that feature. don't panic should always be possible eventually ;)
