### ISSUE TITLE
Inform user in the app if she is running on an outdated version

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#916]
It happened that a user was running on an outdated version. It might help if the app tells the user directly that a new version is available.

We could event go so far to disable some functionalities if the app is not on the latest version.

**Comment by klochowicz** [comment]
nice idea. were you thinking of checking with the coordinator whether the versions match, or directly checking our latest releases on github?  (the latter might be a bit annoying for the users, especially if the review from Apple sometimes takes takes 1-2 days... :/ )

**Comment by holzeis** [comment]
I would have gone with the coordinator..  👍

**Comment by klochowicz** [comment]
I propose the following workflow (trying to keep it simple)

1. the app at startup performs a GET request to the coordinator to query the version.
2. if it does not match the version of the app (in particular, if the app is running lower version), display a notification to the user that they might not be running the latest version and they might want to upgrade).

I would not even try to disable anything, a prompt at startup should be enough. 

of course there's some big assumptions there:
- we ignore hotfixes and patches, e.g. 0.20.1-3 should be simplified to 0.20.1 for this purpose.
- we assume that we normally deploy coordinator when we release the app to the appstore

**Comment by bonomat** [comment]
Verified manually: 
- expiring a build on testflight does not prevent a user from using this build. It just cannot be installed anymore
- also written here: https://developer.apple.com/help/app-store-connect/test-a-beta-version/stop-testing-a-build
> Internal testers and external testers will no longer be able to install this build.

**Comment by Restioson** [comment]
Self-assigning this

**Comment by Restioson** [comment]
I suppose we also need to give the coordinator to a way to query its own version. It seems so far that versions are only tracked in the mobile app's pubspec.yaml?
