### ISSUE TITLE
Setup own instance of p2p derivatives oracle

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#92]
In the context of #47 we stumbled upon the issue that we could not find a working oracle. Neither oracle.p2pderivatives.io nor api.suredbits.com was working.

In order to unblock #47 this ticket is for running our own instance of a p2p derivatives oracle.

https://github.com/p2pderivatives/p2pderivatives-oracle

**Comment by bonomat** [comment]
@holzeis : imho you managed to set one up. Can you document it here?

**Comment by holzeis** [comment]
I managed to setup an instance of the p2p derivatives oracle on my homelab cluster. You can reach the oracle here

https://oracle.holzeis.me

I used the default release configuration from the p2p derivatives oracle repository -> https://github.com/p2pderivatives/p2pderivatives-oracle/blob/develop/test/config/default.release.yml

which can attest by default to `BTCUSD` and `BTCJPY` from https://min-api.cryptocompare.com.
