### ISSUE TITLE
Add channel capabilities to the maker

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#926]
The PR https://github.com/get10101/10101/pull/785 removed the channel capabilities from the maker. 

This was useful because we could test another service opening channels with the coordinator besides LND. 

We will also need this in the long run.

**Comment by da-kami** [comment]
I assume that we want to charge fees, as mentioned in #910, so I think this ticket will be a necessity, because otherwise the maker will not be able to pay fees.
Just pointing this out because the description reads like the ticket might not be mandatory.

**Comment by bonomat** [comment]
Note: for the time being we don't have DLCs in this channel, which means, a single sided channel is not a problem. However, ideally we can think about how we can achieve a dual-funded channel with this. 
JIT might not be ideal because I assume the channel size between maker and coordinator will be quite big and this will un-balance the coordinator's in-bound liquidity enormously.
