### ISSUE TITLE
Add `diesel` migration check(s) to CI

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#963]
Checks include (for both mobile/native and coordinator):

1. `diesel migrations run` should pass without errors
2. `diesel migrations redo --all` should pass without errors
3. `schema.rs` file should not have any git changes after we ran and redid the migrations.

---

Note that for the coordinator we have to spin up the `db` container and run the command like this:

```
diesel migration redo --all --database-url=postgres://postgres:mysecretpassword@localhost:5432/orderbook --migration-dir ./coordinator/migrations
```

---

for the app we can use a tempfile:

```
DATABASE_URL="sqlite:///tmp/database.sql" diesel migration redo --all --migration-dir ./mobile/native/migrations
```

**Comment by klochowicz** [comment]
I guess we should then check whether `schema.rs` would change after running such check on the CI?

**Comment by da-kami** [comment]
> I guess we should then check whether `schema.rs` would change after running such check on the CI?

Yes, this should be an additional check.

Additionally we should add a check that runs without errors for `run` the migrations and then `redo --all` for both coordinator and app. That way we make sure everything works properly.
