### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#968]
1. Merge
	2. https://github.com/get10101/10101/issues/932
	3. https://github.com/get10101/10101/issues/943
	4. https://github.com/get10101/10101/issues/944
5. Merge freeze
6. Release testflight version
7. 24h testing
8. Release into production

**Comment by holzeis** [comment]
blocked by 

- https://github.com/get10101/10101/issues/1002
- https://github.com/get10101/10101/issues/1006

**Comment by bonomat** [comment]
Regtest-Testflight release uploaded :)
Build 1686

**Comment by bonomat** [comment]
> Regtest-Testflight release uploaded :) Build 1686

I think I miss-configured the build 🙈

New build incoming.

**Comment by holzeis** [comment]
mine too 🚀

**Comment by bonomat** [comment]
done https://github.com/get10101/10101/pull/1020

**Comment by bonomat** [comment]
Done
