### ISSUE TITLE
Post new orders to Bitmex

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#974]
After a position has been opened.

- We can not replicate a single trade as it is too small. min 100$ on Bitmex.

Trading Strategy Proposal:
- Upon a change in the trading volume update the position on bitmex accordingly.

e.g. The following query gives all open positions which haven't expired yet. Note, that expired positions although not closed can be force closed at the price at expiry. So we can look at them as being closed at the price at expiry.

```
select direction, sum(quantity), sum(collateral) from positions where expiry_timestamp >= NOW() and position_state='Open' group by direction;
```

hint: get inspired by https://github.com/get10101/automaker

**Comment by da-kami** [comment]
I assume that the BitMEX position will be posted by the maker not the coordinator.
I assume that the maker is not concerned about any DLCs just yet, but is just notified by the coordinator about order matches and trade execution success.

That said, I don't think it makes much sense to have multiple "positions" for the same trading pair on the maker. I think the maker should just have a combined position - and if said position reaches the enough volume to be hedged on BitMEX then we hedge it. In case the position of the maker falls below 100 again we just stop hedging on BitMEX again.

CC @holzeis (the description adder)

**Comment by bonomat** [comment]
I agree, the maker should have a single - combined position. This simplifies the hedging strategy enormously.

**Comment by luckysori** [comment]
> Note, that expired positions although not closed can be force closed at the price at expiry. So we can look at them as being closed at the price at expiry.

I guess with this you mean that we can just treat them as realised PNL. No need to hedge based on them.

**Comment by bonomat** [comment]
>I guess with this you mean that we can just treat them as realised PNL. No need to hedge based on them.

Yes. That is what I meant :)
