### ISSUE TITLE
Background Tasks

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#976]
This is an R&D epic to evaluate how we could run some tasks in the background on iOS and Android.

Some tasks need to happen continuously regardless if the user has opened the app or not. e.g. rollover a position at expiry.

**Comment by klochowicz** [comment]
do we need this for 1.3.0? I feel with #1044 we could push it further down the track?

**Comment by bonomat** [comment]
It's a research topic to understand what it would take or if it is even possible.

**Comment by klochowicz** [comment]
Seems like we could trigger background tasks with FCM.

basic background task handler (that only displays the notifications) is here: https://github.com/get10101/10101/pull/1167
On top of this, we could create messages with different payload to trigger relevant actions that should be done in the background.

Note: as with running on a separate Isolate, not everything could be possible. Apparently http requests, and some DB access is possible, but should be researched further.
