### ISSUE TITLE
Show JIT Channel fee as fee in the wallet history

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#982]
Currently the JIT Channel fee is only shown as payment with the payment hash as description. We should align that with the order matching fees. e.g.

- [ ] Dedicated icon (or the same as for order matching)
- [ ] Description that the fee was for opening an inbound channel.

![Screenshot 2023-07-23 at 06 34 06](https://github.com/get10101/10101/assets/382048/3ba0c4bb-27f4-4064-b9f8-f74fdcf0c81a)

**Comment by Restioson** [comment]
Self-assigning since it relates nicely to my work in #1054; might save this specific ticket for a follow-up PR, though
