### ISSUE TITLE
Receive screen validation is changing inconsistently 

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#983]
Tested on the latest test version. 

1. Fund wallet with 56300 sats
2. Opened and closed a few positions
3. Opened and closed the app a couple of times in between.
4. Tried to receive funds, which shows me initially that I can receive up to 66,113
5. Enter some amount and the value what I can receive up to changes to 0.

![Screenshot 2023-07-23 at 09 03 57](https://github.com/get10101/10101/assets/382048/7dfe4f42-608d-4e78-be50-ad034ba22b3a)

**Comment by da-kami** [comment]
I think it would be best to action this ticket https://github.com/get10101/10101/issues/1008, reproduce the bug in a test and *then* add a fix.

**Comment by Restioson** [comment]
Trying to reproduce this locally right now and it seems to work for me. Here is my history:

![image](https://github.com/get10101/10101/assets/6688948/2e3d1560-8e4d-4b06-be42-2983e85fd9e2)
![image](https://github.com/get10101/10101/assets/6688948/877a119b-016a-4b85-b867-5870ea5ba803)

The latest payment is after receiving money.

If you fund with 56 300 sats and then later transfer out 22 413 sats to get to 33 887 sats, it is my understanding that you should be able to receive 22 413 sats, correct?

**Comment by Restioson** [comment]
New test case.

Wallet history:
![image](https://github.com/get10101/10101/assets/6688948/d4afe2ef-9887-40cc-9ab4-304ea42dc00b)

Initial allowance:
![image](https://github.com/get10101/10101/assets/6688948/c2a357ce-ae65-41e2-bcfa-5233bc35bbd1)

Updated allowance:
![image](https://github.com/get10101/10101/assets/6688948/b8d9c109-b35d-4906-a5f7-b8d9e967bcff)

**Comment by Restioson** [comment]
Is anyone able to reproduce this? I can't from a clean setup

**Comment by Restioson** [comment]
> It is definitely reproducible that the receivable amount is changing once an amount is entered.

Yes, I think we can action that swiftly but the other half of the ticket (which is somewhat more important I'd argue) I can't reproduce yet

**Comment by holzeis** [comment]
Got ya! Well I think this might have only been a special case of the bug.

With can't receiving I meant the amount I can receive is 0. purely uk validation.

**Comment by klochowicz** [comment]
@holzeis I've updated the ticket name, please doublecheck if it still conveys the problem

**Comment by holzeis** [comment]
Sounds good 👍

**Comment by Restioson** [comment]
After logging all the key values, here are the ones that change in order to change the amount to receive:

![image](https://github.com/get10101/10101/assets/6688948/5341c050-5004-441a-8c01-f3a38e83301e)

**Comment by Restioson** [comment]
I think blocking the loading of the UI on the channel info call would be bad, so we should rather somehow defer displaying the max amount to receive until all relevant info. Maybe a loading spinner could be displayed (but where?)

**Comment by Restioson** [comment]
There's a bit of asymmetry between the design of ChannelInfoService and WalletInfoService. Specifically, WalletInfoService keeps a cached copy in Flutter which refreshes regularly, so the create invoice screen can simply read the cached values without them changing in most cases. On the other hand, the ChannelInfoService keeps no cached copy, so the create invoice screen has to request it and cache its own copy. During the request, dummy data is shown.

Is there a reason for these two different approaches? Another potential fix would be to align ChannelInfoService to WalletInfoService's design.

**Comment by Restioson** [comment]
> Maybe you can change the text slightly and split the dynamic values out which can be replaced with spinners in case they are not yet loaded?

This would definitely be possible - in that case would you prefer not to go the `ChannelInfoService` route? This might be overall cleaner. It might still have the jump if a transaction happens as you open the screen, but this would happen anyway, as the widget is rebuilt when the channel info is updated regardless

**Comment by Restioson** [comment]
Unassigning this since #1094 includes a fix
