### ISSUE TITLE
On-chain transaction from closing channel is shown as outgoing

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#985]
It's weird how the on-chain transaction of a collab closed channel is depicted in our wallet history. Currently its shown as outgoing on-chain transaction which is incorrect. I guess it is an outgoing off-chain transaction and an incoming on-chain transaction. Although, I guess it would be nice to show that special case differently.

![IMG_3BC769AFF881-1](https://github.com/get10101/10101/assets/382048/e8727bc0-766d-4d45-a316-e2a9c0456df9)

**Comment by Restioson** [comment]
Do we want to model the closing of a channel as its own transaction type, perhaps?

**Comment by holzeis** [comment]
> Do we want to model the closing of a channel as its own transaction type, perhaps? 

I think that's a good idea.

**Comment by Restioson** [comment]
Seems related to #1111 then

**Comment by holzeis** [comment]
@Restioson i think you tackled this right?

**Comment by Restioson** [comment]
Probably fixed yes, all on-chain had the wrong direction
