### ISSUE TITLE
No candle stick chart

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#997]
I can't see the candle stick chart in the latest testflight release

- main
- `0a9c34d369df825c1fb5c93a7951c444e4e48703`
- 1681
- 1.0.21

![image](https://github.com/get10101/10101/assets/224613/9d2cb3c3-155f-4fcb-a9a1-c7cd1ad14bab)

**Comment by klochowicz** [comment]
I cannot see it locally either :(

**Comment by Restioson** [comment]
Oops, seems like I created a dupe in #1002. I can either move info to here or we could close this in favour. My bad :see_no_evil:

**Comment by bonomat** [comment]
duplicated of #1002
