### ISSUE TITLE
"Pay invoice using 10101 faucet" does not work on Android

### ISSUE THREAD

**Issue by Restioson** [get10101/10101#999]
This is the error when trying to fund using 10101 wallet:
![image](https://user-images.githubusercontent.com/6688948/255640209-4630b2f9-ecea-48ca-ba22-7e8149675f56.png).

This is not super high priority as android is not a target for now (?), but maybe it is a symptom of another issue.

**Comment by Restioson** [comment]
@klochowicz @da-kami: opened this issue to collect discussion here, as it isn't really relevant to #899. Feel free to close if deemed irrelevant or out of scope

**Comment by bonomat** [comment]
Imho it's not an issue of android. I have the same locally on native and simulator. We definitely had other tickets about this before, e.g. this is related: https://github.com/get10101/10101/issues/764

**Comment by Restioson** [comment]
Should this be closed in favour of #764 then?

**Comment by bonomat** [comment]
Closing this in favor of #764
